### ISSUE TITLE
Подключение на проект только i-bem.js

### ISSUE THREAD

**Issue by Jekins** [bem/bem-forum-content-ru#1024]
Всем доброго времени суток.
Очень понравилась работа вашего фреймворка i-bem.js. У нас на новом проекте пока-что используются наименования классов по БЭМ и сейчас налаживается работа фронтенда. В качестве работы с js хотелось бы выбрать ваш фреймворк, так как он наиболее полно дает возможности модульной разработки js кода, но пока-что никак не удается найти способ работать именно с ним. Во всех примерах, что мы нашли, включается в разработку автоматическая сборка HTML и вообще, разделение кода страниц на отдельные папки и файлы. Этот вариант нам не подходит, так как серверной частью у нас будет заниматься PHP фреймворк  Symfony и собираться страницы будут шаблонизатором Twig.
По-этому, прошу у вас помощи разобраться, как внедрить во фронт проекта ваш фреймворк для модульного js, при этом оставив файловую структуру и все остальное (кроме нейминга) своим.

P.S. на начальном этапе, весь css и js у нас будет собираться каждый в один файл грантом.

**Comment by Guria** [comment]
https://github.com/bem/bem-core-dist
где то должны быть ссылки на cdn

**Comment by tadatuta** [comment]
Все ссылки на статику начинаются с `https://yastatic.net/bem-core/`, потом версия, потом платформа и собственно подключаемый файл. Например, `https://yastatic.net/bem-core/3.0.1/desktop/bem-core.no-autoinit.js`.

Еще вместо версии можно использовать `latest` — указывает на актуальную стабильную версию. Разумеется, использовать `latest` в продакшене нельзя, но может быть удобно в процессе разработки.

**Comment by Jekins** [comment]
Спасибо, вроде работает)

**Comment by Jekins** [comment]
Подключил сразу с bem-components, все работает. Но я видел, что у вас готовится к релизу 4 версия bem-core и там достаточно много изменений, хотелось бы сразу писать на новом коде, а не править его по всему проекту через пару месяцев. Есть сейчас возможность так же скачать (https://ru.bem.info/libs/bem-components/v2/#Загрузка-в-виде-архива) только bem-components с bem-core 4 версии?

**Comment by Guria** [comment]
Компоненты основанные на `bem-core@v4` придётся немного подождать, а сам `bem-core@v4.0.0-rc1` можно использовать прямо сейчас.

**Comment by Jekins** [comment]
Спасибо, тогда подождем
