### ISSUE TITLE
Атрибуты в имени которых есть символы (xlink:href)

### ISSUE THREAD

**Issue by 942547** [bem/bem-forum-content-ru#1027]
Как-бы прописать блоку атрибут xlink:href: ?
Обычный способ attrs: {xlink:href: '#name'}, даёт ошибку

Или

Возможно есть другой способ подключить Matherial Buttons - http://tympanus.net/codrops/2015/09/14/creating-material-design-ripple-effects-svg
Как бы это сделали вы?

**Comment by Guria** [comment]
Нужно указать в формате валидного js объекта, т.е. ключ поместить в кавычки: `{ "xlink:href": "#name" }`

**Comment by 942547** [comment]
Спасибо!
