### ISSUE TITLE
Почему не происходит клик?

### ISSUE THREAD

**Issue by Jekins** [bem/bem-forum-content-ru#1031]
Есть код в рамках модуля (не знаю, как обратиться в рамках БЭМ к хрефу, поэтому по старинке):
```
var
	afishaLoc = '#afisha',
	loc = window.location.hash;

if(loc == afishaLoc) {
	$('a[href="' + afishaLoc + '"]').parent('li').click();
}

this.bindTo('item', 'click', function(e){
	console.log('Click!');
}
```
Условие выполняется, но клик почему-то не происходит. li имеет класс block-name__item

**Comment by tadatuta** [comment]
Потому что подписка на клик происходит позже, чем собственно сам клик.

Но я интуитивно могу предположить, что задачу в принципе нужно решать не так.
Так что если будут подробности могу помочь с более правильным вариантом.

**Comment by Jekins** [comment]
И правда, что-то тупанул.

Ну здесь смысл такой:
Есть меню, в котом один из пунктов при клике не ведет на другую страницу, а здесь же вызывает функцию из другого блока (появляется панель). Так же, при клике в урле должен проставиться hash, что бы урл можно было бы скопировать и кому-то отдать и если его откроют,  то должна вызваться функция, которая происходит при клике на этот пункт меню.

Как-то так это сейчас работает, но боюсь это не совсем по БЭМовски, знаний по БЭМ фреймворку пока мало:
```
modules.define('menu-list', ['i-bem__dom', 'side-panel'], function(provide, BEMDOM, SidePanel) {

provide(BEMDOM.decl(this.name,
    {
        onSetMod : {
            'js' : {
                'inited': function() {
		    	var
		    		afishaLoc = '#afisha',
		    		locHash = window.location.hash,
		    		locPathName = window.location.pathname;

                	this.bindTo('item', 'click', function(e){
                		var
                			itemHref = $(e.currentTarget).find('a').attr('href');

		    		locHash = window.location.hash;
		    			
		    		this.findElemInstances('item').delMod('active');
            			this.setMod($(e.currentTarget), 'active', true);

                		if (afishaLoc == itemHref) {
                			window.location.hash = itemHref;
            				SidePanel.activate();
                			return false;
                		} else if (afishaLoc == locHash && itemHref == locPathName) {
                			history.pushState("", document.title, window.location.pathname + window.location.search);
                			SidePanel.deactivate();
                			return false;
                		}
                	});

                	if(locHash == afishaLoc) {
                		setTimeout(function(){
					$('a[href="' + afishaLoc + '"]').parent('li').click();
				},0);
			}
                }
            }
        }
    }
));
```

**Comment by tadatuta** [comment]
Предлагаю сделать проще:
1. Добавить этому кастомному айтему либо микс с дополнительной сущностью, либо просто модификатор, чтобы его можно было легко однозначно сматчить.
2. Знание про добавление/удаление хеша в урле унести в блок панели. При этом вместо написания методов `activate`/`deactivate`, использовать стандартную БЭМ-предметную область, т.е. выразить состояние панели через модификаторы. Это позмолит а) включать/выключать/переключать панель через стандартные setMod/delMod/toggleMod + прописать реакцию на изменение этих модификаторов декларативно (как раз в качестве этой реакции и менять хеш) + бонусом будет возможность подписаться на событие переключения панели снаружи, если потребуется.
3. В итоге в самом коде `menu-list` не придется перебирать айтемы через `$('a[href="' + afishaLoc + '"]').parent('li')`, а реакция на клик будет всего лишь тоглить модификатор на `side-panel`.

**Comment by Jekins** [comment]
Как сматчить елемент по модификатору?
К примеру, мне нужно у ссылки элемента блока, у которого стоит модификатор с определенным значением дернуть href, а потом на него повесить другой модификатор:

```
<ul class="block-name">
    <li class="block-name__item">
        <a href="/link-1.html">Link 1</a>
    </li>
    <li class="block-name__item block-name__item_toggle_on">
        <a href="#param">Link 2</a>
    </li>
    <li class="block-name__item">
        <a href="/link-3.html">Link 3</a>
    </li>
</ul>
```

В jQuery, это примерно так работает, а вот как по бэму, не понятно:

```
var
    item = '.block-name__item',
    $link = $(item).children('a'),
    active = 'block-name__item_active';

$link.on('click', function() {
    var
        hrefLink = $(this).attr('href');

    $(this).closest(item).addClass(active);

    console.log(hrefLink); 
});
```

**Comment by tadatuta** [comment]
Чтобы найти элемент с нужным модификатором, можно использовать кеширующий `elem()` (https://ru.bem.info/libs/bem-core/v2.8.0/desktop/i-bem/jsdoc/#jsdoc-elem-1) или некеширующий `findElem()` — https://ru.bem.info/libs/bem-core/v2.8.0/desktop/i-bem/jsdoc/#jsdoc-findElem-1

Код на jQuery можно переписать в терминах i-bem.js так:
```js
modules.define('block-name', ['i-bem__dom', 'jquery'], function(provide, BEMDOM, $) {

provide(BEMDOM.decl(this.name, {
    onSetMod: {
        js: {
            inited: function() {
                this.bindTo(this.elem('item', 'toggle', 'on'), 'click', function(e) {
                    var link = $(e.target),
                        item = $(e.currentTarget),
                        hrefLink = link.attr('href');

                    this
                        .delMod(this.elem('item'), 'active')
                        .setMod(item, 'active');

                    e.preventDefault(); // если не нужно переходить по ссылке
                });
            }
        }
    }
}));

});
```

**Comment by Jekins** [comment]
Вот, это то что нужно было, теперь понял, спасибо

**Comment by Jekins** [comment]
Правда в этом случае ``` hrefLink = link.attr('href') ``` возвращает undefined

**Comment by tadatuta** [comment]
> если сделать клик удаленно...

Тут возникает подозрение, что задачу нужно в принципе решать чуть по-другому. Расскажи про нее в более высокоуровневых терминах, попробую помочь с решением.

А задачу про тоггл, если, конечно, я ее правильно понял, нужно решать на уровне блока, тогда это выглядит как:
```js
var _this = this;

this.bindTo('item', 'click', function(e) {
    this.elem('item').each(function() {
        _this.toggleMod($(this), 'toggle', 'on', 'off');
    });

    e.preventDefault();
});
```

**Comment by Jekins** [comment]
Саму задачу я уже выполнил, но хочется все сделать максимально в методах бэма, что бы понять, каким образом строиться логика выполнения. Сделать надо следующее:
Есть обычно меню, в котором одна ссылка не выполняет переход, а отрывает панель, вместе с этим проставляя в урл хэш. Этот хэш необходим, что бы при переходе на страницу с ним в урле, сразу открывалась панелька. Соответственно для открытия панельки есть функци выполняемая по клику на пункт меню, которую вы писали выше, а при заходе на страницу и наличии хеша в урле, происходит клик по пункту меню открывающему панель.
