### ISSUE TITLE
Как работать с блоком next-tick?

### ISSUE THREAD

**Issue by Jekins** [bem/bem-forum-content-ru#1037]
У меня есть json файл, в который прилетают данные и формируют массив ```[id1, id2, id3]``` и так далее, мне необходимо следить за изменениями в этом массиве и при появлении в нем очередного значения, выполнять функцию. Как я предполагаю, для отслеживания необходим блок next-tick, но документация по нему очень маленькая и совсем не понятно, как с ним работать в данной ситуации. Можете помочь и направить?

**Comment by tadatuta** [comment]
`next-tick` — это кроссплатформенная реализация https://nodejs.org/api/process.html#process_process_nexttick_callback_arg и, кроме как отложить выполнение функции до конца текущего событийного цикла, этот модуль не делает.

Решение нужно искать где-то в районе слов «данные прилетают». Как именно они прилетают?

**Comment by Jekins** [comment]
Ок, значит не правильно понял его предназначение, решил, что next-tick, это выполнение функции с определенными временными промежутками.
По поводу задачи: данные прилетают с сервера в json файл и формируют массив ```[id1, id2, id3]```. То есть запросив один раз данные из json`a можно получить одни значения и запросив через пол часа, можно получить другие значения. Вот мне и нужен инструмент, который переодически будет проверять файл json на наличие изменений. Если в bem-core такого нет, тогда буду искать во вне.

**Comment by tadatuta** [comment]
Я правильно понял, что речь о том, что браузер просто запрашивает данные c сервера по HTTP и нужно организовать поллинг по временному интервалу?

Если так, то должно хватить чуть ли не
```js
setInterval(function() {
    $.get('http://site.com/data.json').then(function(data) {
        // забираем данные
    });
}, 60 * 1000);
```
