### ISSUE TITLE
Применение верстки, взаимодействие с сервером

### ISSUE THREAD

**Issue by karalkou** [bem/bem-forum-content-ru#1039]
Добрый день!
В вёрстке в зависимости от задач периодически пишу логику, в которой необходим ajax.
1. Сейчас я эмулирую ajax-ответы от сервера у себя в js-файлах. А для программиста оставляю закомментированный кусок чернового ajax-запроса.
2. Программист получает от меня мой js-полотенчик
3. И изменяет часть кода (убирает эмуляцию и дописывает необходимые ему куски ajax-запроса)
Проблема в том, что ему каждый раз, как он получает от меня верстку, приходится вручную проделывать вышеописанные танцы.

Подскажите, как можно обойти эту проблему и не тратить нелишнее время?

**Comment by tadatuta** [comment]
@karalkou нужно больше вводных.
Правильно ли я понял, что вопрос про то, что есть некий сервис, который развивается и флоу выглядит так:
1. Делается верстка
2. Код попадает другому разработчику, он его модифицирует, результат его работы не возвращается к верстальщику
3. Верстальщик что-то доделывает со своим изначальным кодом
4. Другой разработчик вынужден повторять пункт 2 столько раз, сколько раз делаются доработки?

Или речь про разные проекты?

**Comment by karalkou** [comment]
@tadatuta да, правильно.
Второй разработчик модифицирует код и переносит на бой. 
В принципе логично было бы по завершению работы программиста получать от него измененный код. И так и происходит. Но в процессе этой круговерти постоянно случаются накладки. Люди нервничают, седеют)

**Comment by sefus** [comment]
Я думаю JS должен быть у всех одинаковый и обработка Ajax в верстке будет полноценная. Адрес источника данных для Ajax-запроса не нужно хардкодить в JS, а вынести а параметр или куда-то в data-атрибут. У программиста этот адрес будет ссылкой на скрипт или ресурс в сети, а вы можете рандомно подставлять в него разные ответы от сервера, сохраненные в статические файлы.

**Comment by karalkou** [comment]
@sefus мы как раз пришли к такому же выводу) 
Ребят, спасибо!
