### ISSUE TITLE
hasMod у любого из элементов

### ISSUE THREAD

**Issue by Jekins** [bem/bem-forum-content-ru#1051]
Доброго времени суток.

В доме имеем картину что-то типо:
```html
<ul class="block">
    <li class="block__item">Элемент 1</li>
    <li class="block__item block__item_mod">Элемент 2</li>
    <li class="block__item">Элемент 3</li>
</ul>
```

Как сделать проверку наличия модификатора 'mod' у любого из элементов 'item'? Подобные вещи ```this.hasMod('item', 'mod')``` или ```this.hasMod(this.elem('item'), 'mod')``` возвращают false, все другие обращения к элементам, возвращают ошибки. Пример такой проверки нигде не могу найти, поэтому если есть какое-то место с такими примерами, буду рад за ссылку, а пока, спрашиваю здесь.

**Comment by tadatuta** [comment]
```js
var _this = this;
this.elem('item').each(function() {
    _this.hasMod($(this), 'mod');
});
```

PS: на всякий случай скажу, что можно просто выбрать все элементы с данным модификатором:
```js
this.elem('item', 'mod');
```

**Comment by Jekins** [comment]
Мм, значит все же через each делается, думал есть какая-то сокращенная запись. Ок, спасибо

**Comment by tadatuta** [comment]
будет в bem-core v4 (comming soon)
