### ISSUE TITLE
Есть ли какой-нибудь инструмент(аналог csscomb) для форматирования .styl-файлов?

### ISSUE THREAD

**Issue by karalkou** [bem/bem-forum-content-ru#1054]
Хочется привести в нормальный вид старые .styl-файлы проекта (как минимум, сделать группировку свойств).
csscomb, насколько я знаю, не поддерживает .styl.
В качестве линтера можно использовать stylint, но цель - отформатировать автоматически.
Может, кто-нибудь подскажет хорошее решение?

**Comment by tadatuta** [comment]
Когда последний раз искали, ничего не было. Возможно, что-то появилось в мире postCSS.

**Comment by karalkou** [comment]
@tadatuta спасибо
