### ISSUE TITLE
Проблема с Git Bash

### ISSUE THREAD

**Issue by Index1** [bem/bem-forum-content-ru#1071]
Добрый день, начал изучать BEM и тут сразу же возникла проблема с Git Bash, дошёл до момента, когда мы в файле hello.js вставляем js код (https://ru.bem.info/platform/tutorials/quick-start-static/#Реализация-блока-hello), но когда я обновляю страницу, hello.js автоматически обновляется и вставленный мною код исчезает, можете подсказать, в чём причина того, что код автоматически загружается каждый раз, после обновление страницы.

**Comment by tadatuta** [comment]
Привет!

Нужно чуть больше подробностей.

Пока могу предположить, что речь идет о том, что обновляется код в `desktop.bundles/hello/hello.js`, а туториал говорит о том, что код блока нужно написать в `desktop.blocks/hello/hello.js`.

Если так, то причина в том, что папка `desktop.blocks` — это исходники, а `desktop.bundles` — это результаты сборки из исходников.

**Comment by Index1** [comment]
Не заметил, благодарю за помощь :)
