### ISSUE TITLE
jsx и bemjson

### ISSUE THREAD

**Issue by vitkarpov** [bem/bem-forum-content-ru#1084]
Коллеги!

Для описания БЭМ-дерева мы используем bemjson (или bemtree, который позволяет создавать полный bemjson страницы по частям, что по сути — то же самое, верно?) Однако, по своей природе json — довольно многословный формат представления данных, а html (jsx) более лаконичный.

Есть какие-то трансляторы jsx -> bemjson? Наверняка, кто-то думал в эту сторону, имеет ли это практичный смысл?

**Comment by tadatuta** [comment]
https://www.npmjs.com/package/html2bemjson

**Comment by vitkarpov** [comment]
Это про чистый html. Я скорее про:

```html
<Popup mix="Foo" params="{{ "foo": this.ctx.foo }}">
  <MyBlock title="Hello, world!" />
</Popup>
```

**Comment by tadatuta** [comment]
```js
require('html2bemjson').convert(`
<Popup js={{ "foo": this.ctx.foo }}>
  <MyBlock title="Hello, world!" />
</Popup>
`);
/*
{ tag: 'popup',
  attrs: { js: '{{', '"foo":': '', 'this.ctx.foo': '', '}}': '' },
  content: { tag: 'myblock', attrs: { title: 'Hello, world!' } } }
*/
```

Насколько я понимаю, нужно лишь добавить поддержу `{{}}` в атрибутах?

**Comment by vitkarpov** [comment]
Это да, но не только. В данном примере должен получиться:

```js
({
  block: 'popup',
  js: { "foo": ... },
  content: {
    block: ''my-block",
    title: 'Hello, world!' 
  }
})
```

Т.е. идея в том, чтобы описывать именно БЭМ-дерево, а не HTML, более лаконично.

**Comment by vitkarpov** [comment]
Под капотом, шаблонизатор все равно будет работать с bemjson, а человек — с jsx

**Comment by vitkarpov** [comment]
Я почему про это подумал (не только я, идея очевидная). Кажется, что компонентный подход стал популярный в последнее время, с распространением реакта, во многом благодаря тому, что дерево компонентов описывается, условно в привычном для многих XML (HTML), нет?

**Comment by tadatuta** [comment]
Если это правда кто-то будет использовать, то сделать можно, дело не хитрое.
Но что-то есть у меня сомнения.

Если запилю, вы действительно будете использовать у себя на проектах?

**Comment by vitkarpov** [comment]
Пока это просто вброс — интересно, что народ думает

**Comment by vitkarpov** [comment]
Мне кажется, что для ребят, который привыкли «верстать статичный HTML», а так же для тех, у кого «реакт головного мозга», такой интерфейс будет привычнее — соответственно, порог вхождения уменьшится (просто мысли, не факт)

**Comment by zxqfox** [comment]
> Мне кажется, что для ребят, которые привыкли «верстать статичный HTML», а так же для тех, у кого «реакт головного мозга», такой интерфейс будет привычнее

Да, но порог это врядли уменьшит, и вероятно, будет больше путаницы.
Но минусов в том, чтобы уметь собирать из `bundle.bem.xml` вместо `bundle.bemjson.js`, я не вижу ;-).

**Comment by vitkarpov** [comment]
> Но минусов в том, чтобы уметь собирать из bundle.bem.xml вместо bundle.bemjson.js, я не вижу ;-).

Лишь бы толк был, а не «еще один стандарт», как в известном меме :)

**Comment by awinogradov** [comment]
@vitkarpov это невозможно. Можно только конвертировать bemjson в jsx. Обратно без дополнительных знаний не получится, потому что на одном уровне jsx находится несколько уровней bemjson. Например не сущесвует возможности отличить value в jsx от `{ block: 'b', value: value }`, `{ block: 'b', attrs: {value: value} }`, `{ block: 'b', mods: {value: value} }`, `{ block: 'b', mix: {block: 'b2', value: value} }`. Самое важное во всем этом, что правила конвертации для каждого блока уникальны.

**Comment by awinogradov** [comment]
Это касается безусловно плоской записи. Если есть желание писать примерно так:
``` jsx
<BEM block='b1' mods={{ mod1: 'val1' }} attrs={{ value: 'val' }} mix={{}}>content</BEM>
```
То сделать действительно легко, как и сказал @tadatuta, но кажется в этом нет смысла. Ибо в реальном коде это превратится в:
``` jsx
<BEM 
    block='b1' 
    mods={{ mod1: 'val1' }} 
    attrs={{ value: 'val' }} 
    mix={{}}>
        content
</BEM>
```

**Comment by vitkarpov** [comment]
@awinogradov это да — придется вводить дополнительные соглашения, например, введя пространство имен для зарезервированных атрибутов:

```js
<Popup bem-mix="..." bem-mods="..." bem-js="...">
```

ну или запретить использовать эти атрибуты в качестве кастомных, для АПИ своего компонента :)

Я уверен, что найдутся и другие неоднозначные моменты.

**Comment by awinogradov** [comment]
@vitkarpov я могу рассказать как мы решаем это в Лего)

**Comment by vitkarpov** [comment]
«это» — что именно? :) Упрощаете синтаксис bemjson?

**Comment by awinogradov** [comment]
Реализуем интерфейс на jsx в React для бэм-компонентов.

**Comment by vitkarpov** [comment]
Это история про jsx-адаптер?

**Comment by awinogradov** [comment]
Я не знаю что это такое) Но история есть и длинная)

**Comment by vitkarpov** [comment]
Ну, я имею ввиду, что можно писать jsx, вместо bemjson, который, по капотом, bemhtml умеет понимать?

**Comment by vitkarpov** [comment]
Если это другая история — конечно, интересно послушать :) Если это укладывается в рамки форума, конечно.

**Comment by awinogradov** [comment]
> можно писать jsx, вместо bemjson, который, под капотом, bemhtml умеет понимать в рантайме?

Именно так ;)

> Если это другая история...

Почему другая если проблема одна?)

**Comment by vitkarpov** [comment]
Не, задача та же, я про то, что эту историю я знаю. Нормальный ход!
Согласен с тем, что компилировать, возможно, смысла и нет, если можно научить шаблонизатор понимать другой формат описания входных данных.

А есть в этом реальная польза, в смысле, все радостно начинают писать xml вместо bemjson?

**Comment by awinogradov** [comment]
Нет, но мы решили инкапсулировать весь многогранный мир БЭМ за простым API в jsx для React-пользователей. Условно мы живем в чужом стеке по его правилам, что дает понимание как работать с компонентами разработчикам, которые уже знакомы с React. Кроме того такая инкапсуляция позволяет защитить разработчика от разного рода фривольностей. При таком подходе он может модифицировать компонент только так как это позволяет пропсы. Влезть внутрь и поменять bemjson он не может.

**Comment by vitkarpov** [comment]
> в jsx для React-пользователей

Ммм, кажется, я не совсем понимаю — надо уточнить. А если нет Реакта?

Условно, я хочу фрилансер, и хочу сверстать простой лендинг на БЭМ. Хочу побить всю страничку на компоненты, продумать их АПИ, далее описать страничку в xml (как в старые добрые времена), и получить HTML в браузер — не важно, статичную верстку один раз, или накладывать шаблоны на сервере в рантайме.

Мне не нужно, что бы jsx компилировался в `React.createElement` и все такое.

**Comment by vitkarpov** [comment]
> Кроме того такая инкапсуляция позволяет защитить разработчика от разного рода фривольностей.

А всякие миксы и мода `js`?

**Comment by awinogradov** [comment]
> А всякие миксы и мода js?

Миксы деградировали до нативного `className`. `js` мода отвалилась, ибо нужна только для `i-bem`.

> Мне не нужно, что бы jsx компилировался в React.createElement и все такое.

Мы превращаем jsx в bemjson. Так как bem-xjst понимает именного его.

**Comment by awinogradov** [comment]
> Мне не нужно, что бы jsx компилировался в React.createElement и все такое.

Это невозможно) Вернее как, если кастомно по своему реализовать компиляцию. По одной простой причине: `jsx` нужен чтобы коротко описывать `React.createElement`.

``` jsx
<div className='test'>text</div>
```
Компилируется в:
``` js
React.createElement('div', { className: 'test' }, 'text');
```

**Comment by vitkarpov** [comment]
> Мы превращаем jsx в bemjson. Так как bem-xjst понимает именного его.
> jsx нужен чтобы коротко описывать React.createElement

Что-то не совсем пойму, давай попробую сформулировать, а ты меня поправишь.

Есть такой bemjson:

```js
({
  block: 'popup',
  content: [{
    block: 'button',
    text: 'Hello, world!'
  }]
})
```

сейчас это дело принимает шаблонизатор и выдает html.

Хочется:

```js
<Popup>
  <Button>Hello, world!</Button>
</Popup>
```

по-прежнему, это дело принимает шаблонизатор и выдает html.

Если jsx компилирует в `React.createElement`, то и рендерить это дело должен реакт — при чем здесь `bemhtml`?

**Comment by vitkarpov** [comment]
> Если jsx компилирует в React.createElement, то и рендерить это дело должен реакт — при чем здесь bemhtml

Т.е. задача не в том, чтобы по bemhtml-шаблонам получить jsx и скормить его реакту (это задача про «научить реакт понимать bemhtml»), а в том, чтобы позволить человеку писать jsx вместо bemjson.

Что я упускаю?

**Comment by vitkarpov** [comment]
> jsx нужен чтобы коротко описывать React.createElement

Наверное, лучше вообще абстрагироваться от jsx и говорить xml :)

**Comment by Yeti-or** [comment]
```
({
  block: 'popup',
  theme: 'action',
  mods: {'action': 'action'},
  action: {text: 'install me now'},
  content: {
    block: 'button',
    mix: {block: 'popup', elem: 'button', mods: {'action': 'yes'}},
    attrs: {name: 'id-4'},
    name: 'Hello, world!', 
    text: 'Hello, world!'
  }
})
```

**Comment by tadatuta** [comment]
> Наверное, лучше вообще абстрагироваться от jsx и говорить xml

Примерно лет 6 назад в Лего появился скрипт, превращающий XML в BEMJSON ;)

**Comment by zxqfox** [comment]
@tadatuta Вот. Практика показывает, что это плохой путь! Ну или не практика. И не показывает. И не такой уж плохой.

**Comment by Yeti-or** [comment]
да всё просто по кругу идёт 🌀

**Comment by Yeti-or** [comment]
@vitkarpov можешь мой `bemjson` перевести в `jsx`?

**Comment by Yeti-or** [comment]
я не набрасываю если что

**Comment by vitkarpov** [comment]
> Примерно лет 6 назад в Лего появился скрипт, превращающий XML в BEMJSON ;)

@tadatuta а почему это произошло? Насколько я понял, потому что умирал xslt и все переписывалось на JavaScript, а какой родной формат представления данных в JavaScript — json. Т.е. сам по себе xml не плох, а именно в сочетании с xslt-шаблонами, верно?

**Comment by vitkarpov** [comment]
@Yeti-or ты к тому, что в значениях многих атрибутов json и не очень ясно как это вытянуть в плоский список атрибутов?

**Comment by tadatuta** [comment]
@vitkarpov нууу, не знаю... сам по себе XML, конечно, неплох, но возможность в BEMJSON сделать `[].map()` и прочие JS-штуки — это приятно :)

**Comment by vitkarpov** [comment]
> сделать [].map() и прочие JS-штуки

Ну, с jsx это как раз можно сделать:

```js
{this.ctx.users.map(user => {
  return <User name={user.name} />
})}
```

лучшее из обоих миров :)

**Comment by vitkarpov** [comment]
Спасибо всем за обратную связь, в целом, я понял что и как 👍
