### ISSUE TITLE
project-stub: обновить в документации код добавления модификатора к блоку

### ISSUE THREAD

**Issue by dmitrylebedev** [bem/bem-forum-content-ru#1086]
Привет.
Ещё одна маленькая бага, https://ru.bem.info/platform/tutorials/start-with-project-stub/#Миксы-блоков-и-элементов

При добавлении к блоку модификатора, если писать как предложено, то он не добавляется:

```javascript
elem: 'item',
mods: { new: item.new ? 'yes' : undefined },
```

Если для элемента писать так, то всё ок:

```javascript
elem: 'item',
elemMods: { new: item.new ? 'yes' : undefined },
```

**Comment by Yeti-or** [comment]
@godfreyd

**Comment by tadatuta** [comment]
Исправлено, спасибо @dmitrylebedev!
