### ISSUE TITLE
Методология: Новые документы «Быстрый старт» и «CSS»

### ISSUE THREAD

**Issue by vithar** [bem/bem-forum-content-ru#1105]
Опубликовали два новых документа по методологии

Быстрый старт:
https://ru.bem.info/methodology/quick-start/

БЭМ для CSS:
https://ru.bem.info/methodology/css/

Приятного чтения :)

**Comment by dima117** [comment]
> Название элемента характеризует смысл («что это?» — «пункт»: item, «текст»: text)

Наверно, правильнее будет написать "характеризует его роль в родительском блоке", иначе получается что "элемент" - это то же самое, что "блок".

**Comment by webhive** [comment]
Стало лучше. Но в "БЭМ для CSS" я уже упоминал это - вот этот блок "Рассмотрим систему приоритетов стилевых селекторов: ... " - я по прежнему утверждаю, что его надо выкинуть и оставить только описание к чему приведёт наличие имени тега в CSS файле. Всю эту бодягу с пунктами значимости и читать тяжело и она мало что даёт к пониманию. Если человек интересуется БЭМ - это уже подразумевает, что такие моменты и так понятны, а тут вы непонятно зачем жуете очевидные вещи. Как вариант если жалко потраченного на это словоблудие времени вынесите его по ссылке - типа для особо любопытных. Вот прям этот абзац как заноза - читаешь текст как у вас на главной написано "за чашкой кофе" и тут бац упираешься в необходимость запомнить несколько цифр, загрузить в голову и связать несколько понятий, потом по тексту просчитывать в голове специфичность и коэффициенты (буэээ), а потом тебе говорят вывод и ты думаешь - "ну блииин - зачем мне были все эти цифири в голове"?

**Comment by godfreyd** [comment]
Здравствуйте! Не думаю, что запомнить два числа одного порядка (10 и 11) такая сложная вещь для читателя. Документ написан не только для опытных программистов, но и для людей, вчера вошедших в прекрасный мир фронтенда, и не знакомых с системой приоритетов стилевых селекторов. Мы же не о таких числах (2 718 281 828 и −50521) говорим.

**Comment by webhive** [comment]
Тут речь не только о запомнить, а и о держании в уме всего этого контекста. И ладно бы оно было действительно нужно, но всё это наворочено ради тривиального вывода.     

> Куда страшнее, если читатель не поймет, почему .button_active не переопределит CSS-правила в селекторе button.button.

Встройте туда jsfiddle или codepen и покажите на примере. Так это и делается. 
Ну а вообще если развивать именно вашу мысль, то тогда почему нет расчёта коэффициентов для случая id селектора? Будьте последовательны - выносите мозг по полной. Ну и справочник по html и css неплохо бы встроить, а то будет куда страшнее если неопытный фрнтендер что-то забудет или упустит.  

> Мы хотели написать документ как для опытных программистов, так и для людей, вчера вошедших в прекрасный мир фронтенда, и не знакомых с системой приоритетов стилевых селекторов.

Таким людям БЭМ ещё рано. Если почитать ваш форум я думаю станет очевидно, что даже разработчики в целом согласны, что порог вхождения достаточно высок. И даже при наличии хорошей документации он будет высоким. Человек, "не знакомый с системой селекторов" просто не поймёт вообще, что за проблемы вы решаете и чем именно ваш подход лучше. Ваша целевая аудитория (уж простите, что указываю)  это разработчики которые уже столкнулись с определёнными проблемами и ищут как их обойти, либо команды крупных проектов, которые упёрлись в определённый потолок и устали перелопачивать код под безумные фантазии маркетологов. Т.е. это достаточно опытные люди.   

Какие примеры ни приводи, а человеку, который вчера научился считать до 10-ти вы не сможете объяснить понятие допустим логарифма или квадратного корня.

**Comment by tadatuta** [comment]
@godfreyd, Серег, давай действительно выпилим кусок про вычисление специфичности. Можно ограничиться ссылкой на чью-нибудь внешнюю доку.
