### ISSUE TITLE
bemdecl из html

### ISSUE THREAD

**Issue by usacom** [bem/bem-forum-content-ru#1106]
Пытаюсь настроить enb на простую сборку js и css, без bemhtml. Возможно ли получать bemdecl на лету, на основе html, при помощи этого:

https://github.com/bem-contrib/html2bemjson

Попытался написать даже свою технологию для enb, но как я понимаю, она смотрит только на уровни переопределения, когда уже есть готовый bemdecl.

Вроде, даже json адекватный выходит, если ручками прогнать. Но как сагрить на все это сборщик?

**Comment by tadatuta** [comment]
https://github.com/tadatuta/bem-project-stub-he — оно чуть подпротухло, но смысл, думаю, будет понятен. Если нужно, могу освежить.

**Comment by zxqfox** [comment]
@tadatuta кажется, что нам такое было бы здорово иметь для гульпа. мы можем расчитывать на html2bemjson? Можте быть в bem-sdk унести и тестами покрыть?

**Comment by tadatuta** [comment]
@zxqfox там даже какое-то количество тестов есть: https://github.com/bem-contrib/html2bemjson/tree/master/test

А унести — всегда пожалуйста, мне не принципиально, где оно будет лежать.

**Comment by usacom** [comment]
Да, спасибо, разобрался. Теперь прямо накрыло экстазом от бема. 
Но, что действительно стоит освежить, так это документацию enb. Как написать свою технологию. Разобравшись это становится невероятно легко, но для людей впервые видящих enb могут быть(обязательно будут) сложности. 
Вот мне, то, что моя технология ждет ответа от `file-provider` именно по ключу `destTarget` настолько не очевидно...что просто нечего добавить. А еще сбивают с толку технологии направленные на html, замешанные в цикл сборки. Ведь не первый раз присматривался к бему. Скорее всего, мог бы принять его намного раньше, если бы воспринимал его именно как сборщик, методологии и шаблонизацию отдельно. А так все выглядит очень монолитно. 

В итоге имею сборщик и методологию с шаблонизатором blade.php. Тулзы для развертки шаблона blade в декларацию:
https://github.com/pbelyaev/laravel-blade-parser
https://github.com/bem-contrib/html2bemjson

Теперь проект задышал полной грудью, эмоции от использования непередаваемые.
