### ISSUE TITLE
Можно ли задавать модификатор на блок и от него перебивать стили внутренних эелементов (каскадом)

### ISSUE THREAD

**Issue by m11z** [bem/bem-forum-content-ru#1109]
Заказчик утверждает что это не бэм: https://yadi.sk/i/_C_xzUD4uazU7
Есть у меня список постов на одной из страниц который идет обычном списком вниз, 1 пост 1 ряд.
Я с помощью --inline модификатора для главной страницы переделал данный блок постов в ряд, по 4 поста в ряд теперь.
Это БЭМ или нет? И если нет как правильно? Вешать класс на каждую вьюху?

**Comment by tadatuta** [comment]
Это самый БЭМовый БЭМ из всем БЭМовых БЭМов :)

Специально для заказчика мы описали этот случай на bem.info: https://ru.bem.info/methodology/faq/#Почему-нежелательно-использовать-вложенные-селекторы («вложенность уместна, чтобы менять элементы в зависимости от состояния блока или заданной ему темы»).

**Comment by m11z** [comment]
Спасибо за подробный ответ. Вопрос закрыт :)

**Comment by vithar** [comment]
Мне тут не нравится ```.posts--inline .title__text```. В идеале блок влияет только на свои элементы и не трогает другие блоки.

**Comment by vithar** [comment]
И не нравится ```.posts__img-holder img```. По БЭМ не бывает DOM-нод без классов, я бы заменил на ```.posts__img```.

**Comment by m11z** [comment]
@vithar, да, вы правы данные 2 елемента неуместны.
