### ISSUE TITLE
Можно ли так определять модуль в YM (т.е. для элемента, а не для блока)?

### ISSUE THREAD

**Issue by beergreezen** [bem/bem-forum-content-ru#1112]
Ребята, можно ли так?
```javascript
modules.define('finolog-programm-list__list-item', ['i-bem__dom', 'BEMHTML', 'jquery'], function(provide, BEMDOM, BEMHTML, $ ){
   provide(BEMDOM.decl(this.name,{
       //методы экземпляра блока
       onSetMod:{
           'js': {
               'inited': function(){
                   
               }
           }
       }
   }));
});

Вроде, ничего криминального. Но не хочет работать
```

**Comment by tadatuta** [comment]
С точки зрения `ymodules` ничего криминального, но с точки зрения `i-bem.js` элементы по умолчанию не имеют JS-представления.

В текущей версии `bem-core` 3.x можно пуститься во все тяжкие и прикрутить https://ru.bem.info/libs/bem-core/v2.8.0/desktop/i-bem/#Модификатор-elem-instances-элемента-dom-блока-i-bem но я бы рекомендовал использовать отдельный блок вместо элемента.

А в будущей версии 4.x (она уже совсем вот-вот выйдет) элементы будут иметь полноценную JS-реализацию в БЭМ-терминах.
