### ISSUE TITLE
Проблемы с настройкой gemini

### ISSUE THREAD

**Issue by AEIlin** [bem/bem-forum-content-ru#1114]
Привет !
Просьба помочь с настройкой gemini.
Есть компьютер на Ubuntu. На нём есть nginx с тестовыми примерами для gemini. Поднят тутже selenium hub. К hub-у подключён node с виртуалки. Виртуалка - virtualBox - win7 - ie11.
Запускаю gemini тест - на виртуалке открывается окно браузера - с светло зелёным экраном. Как я понял - это цвет какого-то джеминевского калибратора. Но дальше тесты не запускаются. Через какое-то время Gemini падает с ошибкой, что не удалось запустить ie11 - ETIMEDOUT.
gemini.conf http://pastebin.com/7meB32Wt
тест http://pastebin.com/CNW10GyS
конфигурация Selenium node http://pastebin.com/tR6yDxcn
вресия selenium 2.53.1
gemini 4.4.1, 4.8.0, 4.9.0

Пробовал делать скриншоты, используя nightwatch.js и там всё проходило отлично.
Продублирую, на всякий случай в issue

**Comment by tadatuta** [comment]
Закрываю в пользу https://github.com/gemini-testing/gemini/issues/582
