### ISSUE TITLE
Чуваки, сделайте уже как-надо сетку (ветку) bem-grid, чтобы не вспоминать про bootstrap!

### ISSUE THREAD

**Issue by weynemeynen** [bem/bem-forum-content-ru#1115]

**Comment by kompolom** [comment]
А как надо?

**Comment by weynemeynen** [comment]
на master OK!
переключаюсь на ветку bem-grid, обновляю страницу,
всё висит, жду 5-10 мин,
вижу: Failed to load resource: net::ERR_EMPTY_RESPONSE http://localhost:8080/desktop.bundles/index/index.min.css

**Comment by Yeti-or** [comment]
какой репозиторий ты имеешь ввиду?

**Comment by weynemeynen** [comment]
конечно: https://github.com/bem/project-stub/tree/bem-grid

**Comment by Yeti-or** [comment]
@awinogradov take a look

**Comment by weynemeynen** [comment]
Спрашивал уже Антона об этом пол года назад, глядя прямо в глаза.
Похоже он забил на это своё детище, детище недоношенное.
А идея нужная.

**Comment by Yeti-or** [comment]
в смысле забыл вот оно живет развивается: https://github.com/theprotein/sharps

**Comment by weynemeynen** [comment]
это замечательно!
почему об этом знаете только вы?
а то, что в project-stub не работает - факт.

**Comment by tadatuta** [comment]
@weynemeynen 

> почему об этом знаете только вы?

1. Прежняя ссылка https://github.com/bem-contrib/bem-grid редиректит в новый репозиторий
2. В репозитории есть документация, где буквально за 2 простых шага ставится либа

> то, что в project-stub не работает - факт

Обновил ветку `bem-grid` в `project-stub`:  https://github.com/bem/project-stub/tree/bem-grid

**Comment by weynemeynen** [comment]
Вот теперь ОК!
Только надо в package.json добавить "sharps"
иначе `enb make`: _Error: Cannot find module 'sharps'_

**Comment by tadatuta** [comment]
> Только надо в package.json добавить "sharps"

Так ведь я же сразу добавил: https://github.com/bem/project-stub/blob/bem-grid/package.json#L23

**Comment by weynemeynen** [comment]
@tadatuta :)
