### ISSUE TITLE
Задание стилей элементов через модификатор блока

### ISSUE THREAD

**Issue by hrenly** [bem/bem-forum-content-ru#1131]
Отвечает ли требованиям BEM задание стилей для элементов через модификатор блока. Или же нужно создавать модификаторы элементов?

**Comment by tadatuta** [comment]
См. вторую часть ответа https://ru.bem.info/methodology/faq/#Почему-нежелательно-использовать-вложенные-селекторы

**Comment by hrenly** [comment]
Т.е. 

> Например, вложенность уместна, чтобы менять элементы в зависимости от состояния блока

**Comment by tadatuta** [comment]
Ага, оно :)

**Comment by hrenly** [comment]
Спасибо
