### ISSUE TITLE
Как получить данные этого метода в requeste? Дабы использовать в другом модуле

### ISSUE THREAD

**Issue by bemdev** [bem/bem-forum-content-ru#1135]
modules.define('clients', function(provide){

  provide({

    getClients: function(){

      /* Получаем список суб-клиентов агенства (или представителей) */

        var sendQ = {
           "method": "GetClientsList",
           "token": ""
        };

        var options = {
          url: "САЙТ",
          method: "POST",
          headers: {
              'Content-Type': 'application/json; charset=utf-8',
              'Authorization': 'Bearer'
          },
          json: true,
          body: sendQ
        };

        var clients = '';

        request(options, function (err, res, body) {
          var clients = body["data"];
          var client = clients.map(function(a){
            return a.Login;
          });
          // console.log(body);

          if(client[0] != false){
            console.log('Client list getty - OK - '+client[0]);
          }else {
            console.log('some problems');
          };
          return
        });

      return

      /* Список получен переходим к дальнейщим действиям */
    }

  });
});

не судите строго я только начинаю понимать эти технологии :В

**Comment by tadatuta** [comment]
@bemdev удалось разобраться?

**Comment by bemdev** [comment]
ну как сказать, через промис прикидывая дальше но как то это не нравится
почему я немогу сделать модуль который при вызове вернет мне сразу
значение и в другом модуле я его уже как нить обработаю, а сам модуль
зарекваирить не проблема же. 

и еще есть вопрос, может будет время посмотрите
https://ru.bem.info/forum/1137/
