### ISSUE TITLE
При динамическом создании select'а не появляется текст на button'е внутри него: ни пустой, ни значение специализированного поля text блока select

### ISSUE THREAD

**Issue by kvmamich** [bem/bem-forum-content-ru#164]
Получаю следующую картину: после полной загрузки страницы и окончания инициализации js созданный динамически select не работает вообще. В обоих случаях bemjson один и тот же. В динамически созданном select'е в button'е отсутствует текстовый элемент, видимо, из-за этого весь блок select превращается в ~~тыкву~~ нерабочий компонент. Может быть, я что-то упустила, но никак не могу понять, что именно.

Код (выкачивала [project-stub](https://github.com/bem/project-stub), изменения внесены минимальные): https://github.com/kvmamich/bem-dynamicselect
Скриншот: https://raw.githubusercontent.com/kvmamich/bem-dynamicselect/master/screenshot.png

**Comment by tadatuta** [comment]
@kvmamich проблема с зависимостями. дело в том, что у разных модификаторов `_mode` разные шаблоны, а в https://github.com/kvmamich/bem-dynamicselect/blob/master/common.blocks/dynamic-select/dynamic-select.deps.js#L10 они не попали.

Я [сделал PR](https://github.com/kvmamich/bem-dynamicselect/pull/1/files) с некоторыми комментариями к коду.

**Comment by kvmamich** [comment]
Большое спасибо!
Оказалось не слишком очевидным то, что если не указываешь `mode`, то не попадает ни один шаблон.
