### ISSUE TITLE
Блок внутри элемента это тру?

### ISSUE THREAD

**Issue by campykid** [bem/bem-forum-content-ru#186]
Есть блок с элементами саджеста, сверстан как нумерованный список, а элементы списка, собственно элементы. Нужно что-бы цвет содержимого отличался от цвета цифр списка. Для этого решено оборачивать элементы тэгом и задавать другой цвет. Чем отталкиваясь от БЭМ методологии следует считать эти теги? Сейчас обертка выглядит как блок, это допустимо? Или нужно заставить их быть модификаторами?

```html
<ol class="input__samples" role="list">
    <li class="input__sample link link_pseudo_yes i-bem link_js_inited" role="listitem">
         <div class="sample-inner">sample</div>
    </li>
    <li class="input__sample link link_pseudo_yes i-bem link_js_inited" role="listitem">
         <div class="sample-inner"> sample2</div>
    </li>
</ol>
```

**Comment by tadatuta** [comment]
@campykid С конкретной описанной задачей можно справиться без создания дополнительных оберток средствами CSS (см., например, http://css-tricks.com/numbering-in-style/).

По сути вопроса ответ такой: вкладывать блоки в элементы можно, но в данном конкретном случае по смыслу больше подходит вложенный элемент `input__sample-inner`, т.к. он не имеет смысла в отрыве от своего родительского блока.

**Comment by zxqfox** [comment]
Вполне. В том и прелесть.

Можно еще съэкономить вложенность и намиксовать блок на элемент, или элемент на блок (чаще второе):
```js
{ block : 'input', elem : 'samples', content : [
  { block : 'sample', mix : [
    { block : 'link', mods : ... },
    { block : 'input', elem : 'sample' }
  ], content : 'sample 1' },
  ...
] }
```

**Comment by campykid** [comment]
Спасибо за ответы. Решил задачу через CSS :D
