### ISSUE TITLE
Почему не инициализировался блок?

### ISSUE THREAD

**Issue by Guria** [bem/bem-forum-content-ru#188]
* Простейший bemjson:
```
([
  {
    block: 'page',
    content: [
      { block: 'test', mods: { foo: 'bar'}, js: true}
    ]
  }
]);
```

* блок рендерится в `<div class="test test_foo_bar i-bem" data-bem="{&quot;test&quot;:{}}"></div>`
* `page` из `bem-core` автоматом тянет `i-bem__dom_init_auto` и в собранном `.js` присутствует.

Однако блок не инициализировался:
(https://gist.github.com/6bb4a5dc7d97cba5fa67)
(http://bl.ocks.org/Guria/raw/6bb4a5dc7d97cba5fa67/)

**Comment by zxqfox** [comment]
`modules.define('kg-menu', ['i-bem__dom']` — потому что kg-menu !== test

**Comment by Guria** [comment]
посыпаю голову пеплом. спасибо

**Comment by zxqfox** [comment]
;-) шыт случается

**Comment by Guria** [comment]
Чтоб добавить полезности этому фейл посту, предлагаю дополнить список [Чтобы привязать блок к HTML-элементу, необходимо:](https://ru.bem.info/libs/bem-core/v2.5.1/desktop/i-bem/docs/#Синтаксис-привязки-блоков) в начале следующим пунктом:
* Объявить сам блок в js технологии:
```
пример объявления блока block
```
Если нет возражений, PR с меня.
cc @innabelaya @tadatuta

**Comment by tadatuta** [comment]
@Guria я за
