### ISSUE TITLE
Планируется ли порт bem-tools на io.js ?

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-forum-content-ru#196]
Как известно, был создан форк NodeJS -> io.js
Планируется ли разработка bem-tools на нём?

IO обгоняет Node по скорости, если исходить из этой статьи http://www.quora.com/Is-IO-js-faster-than-Node-js

**Comment by apsavin** [comment]
bem-tools в своем текущем виде заморожен и не развивается (enb победил).
Но, в любом случае, что мешает запускать bem-tools под io?

**Comment by matmuchrapna** [comment]
присоединюсь к вопросу @apsavin, так как IO пока обратно совместимо с Node.JS

**Comment by tadatuta** [comment]
мы планируем гонять в `travis` тесты в том числе и в `io.js`
