### ISSUE TITLE
Подскажите как елементу блока добавить модификатор при наведении

### ISSUE THREAD

**Issue by serhioone** [bem/bem-forum-content-ru#198]
Сейчас вешаю на блок .bindTo(this.elem('item'), 'mouseover', function (e) {})
Подскажите пожалуйста как теперь на этот элемент повесить модификатор?

Заранее спасибо

**Comment by verybigman** [comment]
this.setMod(this.elem('item'), 'modName', 'modVal')

**Comment by serhioone** [comment]
В данном случае он добавит класс всем элементам item, а нужно только тому на котором произошло событие

**Comment by apsavin** [comment]
В функцию приходит событие, в нем есть ссылка на элемент.

**Comment by tavriaforever** [comment]
`this` - блок
`$(e.target)` - элемент на котором случилось событие
```
modules.define('block-name', ['i-bem__dom', 'jquery'], function(provide, BEMDOM, $) {
    provide(BEMDOM.decl(this.name, {
        onSetMod: {
            js: {
                inited: function() {
                    this.bindTo(this.elem('item'), 'mouseover', function(e) {
                        this.setMod($(e.target), 'action', 'wow');
                    });
                }
            }
        }
    }));
});

```

**Comment by serhioone** [comment]
А почему может не работать конструкция 
<code>
var item = $(e.currentTarget);
 this.toggleMod(item, 'type', 'current', '');
</code>

**Comment by tadatuta** [comment]
@serhioone стоит убедиться, что `this` указывает на нужный блок (например, вывести в консоль `this.domElem`) и что в `item` попал нужный элемент.
