### ISSUE TITLE
Взаимодействие блока с элементами

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-forum-content-ru#201]
Пытаюсь менять стиль блока, после нажатия на элемент в нём (ctrl). Но ничего, кроме ошибки "TypeError: g.handler.apply is not a function", не выходит.

```js
modules.define('b-map-filter-bar', ['i-bem__dom'], function(provide, BEMDOM) {

BEMDOM.decl(this.name, {
    onSetMod: {
        'js' : {
            'inited' : function() {
                this.setMod('display', true);
                console.log('init');

                this.__ctrl = this.elem('ctrl');

                this.__ctrl.on('click', this._onClick, this);
            }
        },
        'theme': {
            'tosecond': function() {
                this.__ctrl.text('Привет');
            },
            'tofirst': function() {
                this.__ctrl.text('Пока');
            }
        }
    },

    prevTheme: '',
    _onClick: function() {
        if(this.prevTheme === 'tosecond') {
            this.setMod('theme', 'tofirst');
            this.prevTheme = 'tofirst';
        } else {
            this.setMod('theme', 'tosecond');
            this.prevTheme('theme', 'tosecond');
        }
    }
});

provide(BEMDOM);

});
```

**Comment by zxqfox** [comment]
ЕМНИП, это 
```
  if(this.prevTheme === 'tosecond') {
            this.setMod('theme', 'tofirst');
 ...
```
можно записать проще:
```
  this.toggleMod([elem,] modName, modVal1[, modVal2][, condition]);
```
https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.vanilla.js#L444

В твоем случае:
```
  this.toggleMod('theme', 'tofirst', 'tosecond');
```

А ошибка странная, не знаю, что за `g.handler`. Это точно из этого кода? Может быть еще что-то на странице есть?

**Comment by belozyorcev** [comment]
ничего не подключено. Только сгенерированный JS.

**Comment by belozyorcev** [comment]
Если из контекста убрат this
```
this.__ctrl.on('click', this._onClick);
```
то _onClick ищет функцию на элементе

**Comment by Guria** [comment]
`this.prevTheme('theme', 'tosecond')`
а зачем вы переменную как функцию вызываете?
Правильно сказал @zxqfox, надо использовать `toggleMod`

**Comment by zxqfox** [comment]
Lol. Вы через jquery событие вешаете. Сделайте  `this.bindTo(elem, click, handler)`, и все будет ок)

**Comment by belozyorcev** [comment]
вообще не пойму из-за чего ошибка... Ничего не помогает

```js
modules.define('b-map-filter-bar', ['i-bem__dom'], function(provide, BEMDOM) {

BEMDOM.decl(this.name, {
    onSetMod: {
        'js' : {
            'inited' : function() {
                this.setMod('display', true);
                console.log('init');

                this.__ctrl = this.elem('ctrl');

                this.__ctrl.on('click', this._onClick, this);
            }
        },
        'theme': {
            'tosecond': function() {
                this.__ctrl.text('Привет');
            },
            'tofirst': function() {
                this.__ctrl.text('Пока');
            }
        }
    },
    
    _onClick: function() {
        this.toggleMod('theme', 'tofirst', 'tosecond');
    }
});

provide(BEMDOM);

});
```

**Comment by belozyorcev** [comment]
Сделал пока через "bindTo". Но хочется через "on"

```js
modules.define('b-map-filter-bar', ['i-bem__dom', 'b-map-sfl'], function(provide, BEMDOM, secondFilter) {

BEMDOM.decl(this.name, {
    onSetMod: {
        'js' : {
            'inited' : function() {
                this.setMod('display', true);
                console.log('init');

                // this.on('click', this._toggleTheme);
                // this.bindTo('click', this._toggleTheme);
                this.__ctrl = this.elem('ctrl');

                this.bindTo(this.__ctrl, 'click', this._toggleTheme);
                // this.__ctrl.on('click', this._toggleTheme, this);
            }
        },
        'theme': {
            'tosecond': function() {
                this.__ctrl.text('Какие здесь направления подготовки?');
            },
            'tofirst': function() {
                this.__ctrl.text('Посмотреть в другом районе?');
            }
        }
    },

    _toggleTheme: function() {
        // console.log(this);
        this.toggleMod('theme', 'tofirst', 'tosecond');
    }
});

provide(BEMDOM);

});
```

**Comment by belozyorcev** [comment]
@zxqfox на вэбинаре использовался метод "on"

http://youtu.be/1GWoMnYldYc?t=2h15m58s

**Comment by sipayRT** [comment]
> Lol. Вы через jquery событие вешаете.

ты что-то путаешь. Он правильно подписался

**Comment by apsavin** [comment]
оффтоп, но 
@belozyorcev не нужно сохранять `this.__ctrl`, так как `this.elem` кеширующий метод.
А если по теме - то `this.elem` возвращает jQuery объект, так что `on` - это метод из jQuery api и в него нельзя передать контекст. Используйте `bindTo`.

**Comment by belozyorcev** [comment]
Действительно :) В видео использовался метод для нахождения блоков, а не элементов :)

@apsavin. Спасибо за разъянения

**Comment by zxqfox** [comment]
> ты что-то путаешь. Он правильно подписался

@sipayRT Он подписался через [это](http://api.jquery.com/on/), и контекст там соотв (дом-нода). Нет?

**Comment by tavriaforever** [comment]
Я уже сам запутался в Ваших доводах.))
В вебинаре я использовал `on` для подписки на `BEM` событие, которое генерит блок `link` из `bem-components`. Я его ранее нашел и положил в в поле `this.__button`. 
Не сработал js потому что я вместо того, чтобы найти один блок `icon` с помощью метода `findBlockInside`, позвал метод `findBlocksInside`, который мне вернул массив из одного элемента. И я пытался у массива вызвать метод `setMod`, что и было ошибкой.

По поводу вашей ситуации, если подписываешься на BEM событие используешь `on`, если на ДОМ событие, тогда нужно использовать унифицированный метод из i-bem.js `bindTo`. 
jQuery метод `on` использовать не нужно.

**Comment by sipayRT** [comment]
> Он подписался через это, и контекст там соотв (дом-нода). Нет?

Нет :) он подписался через [это](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L1297)

**Comment by zxqfox** [comment]
@sipayRT Нет, в оригинальной версии у него было:
```js
this.__ctrl = this.elem('ctrl');
this.__ctrl.on('click', this._onClick, this);
```
И `this.__ctrl` (результат `this.elem(...)`) — это ровно jQuery-chain.
