### ISSUE TITLE
BEM channel, есть ли он ещё?

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-forum-content-ru#203]
Видел примеры с BEM.channel(), для реализации обмена данными между блоками, но не могу найти объяснение.

Или данного метода нету уже?

Можете на простом примере показать, как вызывать события между несколькими блоками в параллельных ветках DOM (но с общим родителем)?

**Comment by apsavin** [comment]
[Вот](https://github.com/bem/bem-core/blob/v2/common.blocks/events/__channels/events__channels.vanilla.js) что теперь вместо BEM.channel.
Если вы на bem-core, конечно.

**Comment by belozyorcev** [comment]
не совсем понимаю как его использовать.

Это необходимо блок events миксовать?

Допустим у меня есть block-1 и block-2
```
{
    block: 'block-1'
    mix: [{block: 'events'}]
    content: '...'
},
{
    block: 'block-2'
    mix: [{block: 'events'}]
    content: '...'
},
```

Мне нужно вызвать определённое действие с блоком 1 при событии в блоке 2

**Comment by apsavin** [comment]
нет, его нужно объявить в зависимостях в js-файлах для обоих блоках и использовать примерно так же, как раньше использовался BEM.channel.

**Comment by belozyorcev** [comment]
Буду пробовать что-то с этим делать)

**Comment by tavriaforever** [comment]
Пример использования

```
modules.define('block-1', ['i-bem__dom', 'events__channels'], function(provide, BEMDOM, channels) {
    provide(BEMDOM.decl(this.name, {
        onSetMod: {
            js: {
                inited: function() {
                    channels('proizvolnot-imya-kanala').emit('tydish', { yourName: 'developer' });
                }
            }
        }
    }));
});

modules.define('block-2', ['i-bem__dom', 'events__channels'], function(provide, BEMDOM, channels) {
    provide(BEMDOM.decl(this.name, {
        onSetMod: {
            js: {
                inited: function() {
                    // Handler for event in channel with some data
                    channels('proizvolnot-imya-kanala').on('tydish', function(e, data) {
                        console.log('My name is: %s', data.yourName);        
                    }, this);
                }
            }
        }
    }));
});
```

У обоих блоков по хорошему должна быть зависимость от блока events
block-1.deps.js
block-2.deps.js
```
({
    shouldDeps: [
        { block: 'events', elem: 'channels' } 
    ]
})
```

**Comment by belozyorcev** [comment]
@tavriaforever то что мне нужно было :) чтобы понять принцип использования. Спасибо (:

**Comment by belozyorcev** [comment]
А события знают о себе?

Например у меня оба блока подписаны на один канал и на одно событие, при этом они вызывают это событие.

Не получится ли так, что ```блок 1``` - отправит событие ```А``` и тут же на него ответ?

Т.е. меня какой из сценариев работает:
1) Информацию получают ```все - отправитель```.
2) Или ```все  + отправитель```

**Comment by veged** [comment]
@belozyorcev информацию получают все — ни в подписке, ни в бросании события сам блок никаким параметром не участвует

@tavriaforever по этим же причинам, нужно не забывать такие подписки удалять при деструкте блока:
```js
modules.define('block-2', ['i-bem__dom', 'events__channels'], function(provide, BEMDOM, channels) {
    provide(BEMDOM.decl(this.name, {
        onSetMod: {
            js: {
                inited: function() {
                    // Handler for event in channel with some data
                    channels('proizvolnoe-imya-kanala').on('tydish', this._onTydish, this);
                },
                '': function() {
                    channels('proizvolnoe-imya-kanala').un('tydish', this._onTydish, this);
                }
            }
        },
        _onTydish: function(e, data) {
            console.log('My name is: %s', data.yourName);        
        }
    }));
});
```

**Comment by zxqfox** [comment]
Tydish это не правильно. Правильно: Tydysch!
