### ISSUE TITLE
Не работает deps.js

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-forum-content-ru#208]
Указал в файлах ```*.deps.js``` и в папке ```__item``` и в папке ```b-filters```

```
({
    mustDeps : { elem : 'item-w' }
})
```
но файлы стилей элемента ```item-w``` не подгружаются

bemhtml
```
block('b-filters').elem('item').def()(function() {
        var ctx = this.ctx;
        applyCtx({ elem: 'item-w', content: ctx })
   })
```

bemjson

```
{
	block: 'b-filters',
	content: [
		// {
		// 	elem: 'item-w'
		// },
		{
			elem: 'cities',
			content: [
				{elem: 'head', content: 'Города'},
				{elem: 'item', content: 'Железноводск'},
				{elem: 'item', content: 'Кисловодск'},
				{elem: 'item', content: 'Лермонтов'},
				{elem: 'item', content: 'Невинномысск'},
				{elem: 'item', content: 'Пятигорск'},
				{elem: 'item', content: 'Ставрополь'},
			],
		},
    ]
}
```

если подключить в bemjson элемент, тогда всё заработает

**Comment by Guria** [comment]
* Почему папка `__item`, а не `__item-w`
* попробовать shouldDeps вместо mustDeps
* у самого элемента зависимость от себя же прописывать не надо

**Comment by belozyorcev** [comment]
у меня есть папка ```__item-w``` где находятся стили для обёртки откуда я и пытаюсь их подключить

```shouldDeps``` тоже не помогает

**Comment by Guria** [comment]
а файлы в папке `__item-w` полностью названы?
`b-filter__item-w.*`

**Comment by belozyorcev** [comment]
```b-filters__item-w.styl```

**Comment by Guria** [comment]
Я в `bemhtml` пока не разбирался. Что именно ваш фрагмент должен сделать с `bemjson`?

**Comment by apsavin** [comment]
bemhtml в любом случае не влияет на сборку css.

**Comment by belozyorcev** [comment]
Мне просто было лень менять все записи в ```bemjson```, поэтому сделал для этого обёртку в ```bemhtml```. Он строит список

**Comment by tavriaforever** [comment]
Нужна ссылка на исходник, так ответить не могу

**Comment by belozyorcev** [comment]
@tavriaforever @Guria @apsavin почему-то я не заметил, что файл был назван ```b-map-filters.deps``` вместо  ```b-map-filters.deps.js```
