### ISSUE TITLE
Как обратить к элементу родительского блока

### ISSUE THREAD

**Issue by serhioone** [bem/bem-forum-content-ru#224]
Добрый день, подскажите пожалуйста как правильно обращаться к элементу родительского блока? С учетом того что блок может быть разный
```html
<div class="block1">
    <span class="block1-element"></span>
    <div class="block2"></div>
</div>
```
Как из блока 2 получить block1-element?
Сейчас делаю так
```js
this.findBlockOutside('block1').elem('element')
```
Но проблема в том что блок может называться по другому

**Comment by Guria** [comment]
Надо понять вашу задачу. Сейчас не понятно почему дочернему блоку понадобилось что-то от родительского, а не наоборот. Скорее всего у вас ошибочно выполнено разделение на блоки и элементы.

**Comment by zxqfox** [comment]
Наверное, лучше всего не напрямую это делать, а через управляющий блок и/или события.

**Comment by serhioone** [comment]
В данном случае block2 это календарь а block1-element это label куда необходимо подставлять значение выбранной даты

**Comment by Guria** [comment]
В данном случае календарь должен просто бросить событие 'date-changed', а родитель будучи подписан на него изменять свой элемент.

**Comment by serhioone** [comment]
А не подскажите как это можно реализовать? Интересует как родительский блок подписать на событие дочернего, и как правильно бросить событие changed

**Comment by zxqfox** [comment]
@serhioone Я бы дочернему навесил элемент и из родительского, зная что элемент может использоваться только для контрола календаря, работал бы с элементом. В элементе, который знает про календарь, на который он навешивается, работал бы с блоком календаря через .getVal. Но это форма какая-то получается ;-)

Можно и прямо из родительского подписаться на события блока внутри (если он всегда будет в этом блоке) и при изменении менять элемент:
```js
// block1:
onSetMod: js: inited:
  this._calendar = findBlockInside('calendar');
  this._calendar.on('changed', this._dateChanged, this);
_dateChanged:
  this.elem('element').text(this._calendar.getVal());
// block2:
getVal:
  return this,_input.getVal();
```

**Comment by Guria** [comment]
* примиксовать элемент родительского блока на дочерний.
* подписаться на событие дочернего
```js
this.findBlockInside('elem-with-block', 'block2').on('changed', function(e, data){
  // здесь меняете текст лейбла. если не изменяет 
}, this) // передаём в качестве контекста родительский блок
```
* дочерний при смене даты выполняет
```js
this.emit('change', newValue)
```

**Comment by zxqfox** [comment]
;-) да.

**Comment by Guria** [comment]
Ну и конечно читаем [FM](https://ru.bem.info/libs/bem-core/v2.5.1/desktop/i-bem/docs/#БЭМ-события)

**Comment by serhioone** [comment]
Судя по всему у нас используется bem-bl сборка а там судя по всему нет метода emit =(

**Comment by serhioone** [comment]
Есть еще какие способы узнать что дочерний блок изменился? или что в нем было выполнено действие?

**Comment by tadatuta** [comment]
@serhioone В `bem-bl` метод называется `trigger()`. В `bem-core` его переименовали в `emit()`, чтобы было консистентно для браузера и `node.js`.

**Comment by serhioone** [comment]
Спасибо большое, все больше и больше нравится бэм
