### ISSUE TITLE
bem server и enb

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#244]
Решил переехать с `bem-tools` на `enb`. Склонировал `project-stub`, запустил сборку - страничка собралась. Запускаю dev сервер коммандой `npm start` и  вижу привычный вывод bem server. Сборка проходит, но при изменении bemjson, index.html не меняется.
Если делаю `./node_modules/.bin/enb make` то html меняется. 
Вопрос: Как правильно запустить dev сервер используя enb?

**Comment by dab** [comment]
@kompolom `./node_modules/.bin/enb server`

**Comment by kompolom** [comment]
Спасибо. Мне кажется, было бы неплохо отразить это [в быстром старте](https://ru.bem.info/tutorials/quick-start-static/)

**Comment by dab** [comment]
@kompolom там написано что сервер запускается с помощью `npm start`, идем в [https://github.com/bem/project-stub/blob/bem-core/package.json#L34](`package.json`).

**Comment by kompolom** [comment]
В общем, у меня в `package.json` оказалось написано `bem server`, похоже, просто не самую последнюю ветку склонировал.
