### ISSUE TITLE
Не работает инициализация по модификатуру

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-forum-content-ru#245]
Пытаюсь подключить Яндекс карту в проекте.
За основу взял следующий пример: https://github.com/zloylos/ymapsbem

Но вот почему-то не работает инициализация по декларации ```{ name: 'this.name', modName: 'api', modVal: 'ymaps' }```
```js
modules.define('map', ['i-bem__dom', 'loader_type_js', 'jquery'], function(provide, BEMDOM, loader, $) {
    provide(BEMDOM.decl({ name: this.name, modName: 'api', modVal: 'ymaps' }, {
        onSetMod: {
            'js': {
                inited: function () {
                    this.loadMapsApi();
                }
            }
        },
    }));
});
```
Но если декларацию делать только по блоку, то всё работает
```js
modules.define('map', ['i-bem__dom', 'loader_type_js', 'jquery'], function(provide, BEMDOM, loader, $) {
    provide(BEMDOM.decl(this.name, {
        onSetMod: {
            'js': {
                inited: function () {
                    this.loadMapsApi();
                }
            }
        },
    }));
});
```

bem-stub собирал через генератор

**Comment by zxqfox** [comment]
А модификатор-то есть на дом-ноде? ;-) Мало информации, чтобы сказать в чем причина.

**Comment by belozyorcev** [comment]
Разобрался с проблемой.

в примере используется
```{ name: this.name, modName: 'api', modVal: 'ymaps' }```

пересмотрел документацию. Вместо ```name``` должно быть ```block```
```{ block: this.name, modName: 'api', modVal: 'ymaps' }```

всё заработало
