### ISSUE TITLE
Сборка BH на клиенте

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#248]
Хочу использовать bh.js на клиенте.  на сервере используется bh.php. Для сборки используются `bem-tools`. И что то я никак не соображу как подключить все это в браузер...
Вот так пытаюсь подключить в deps.js блока

    ({
    tech: 'bh',
    mustDeps: [
      {
        tech: 'bh',       
      }
     ],    
    })

**Comment by verybigman** [comment]
По-моему, должно быть как-то так:
``` js
({
    tech: 'js',
    mustDeps: { tech : 'bh', block : 'block-name' }    
})
```

Но как по-мне, если таких блоков много, лучше написать merge в make файле сборщика и сливать технологии там.

**Comment by kompolom** [comment]
Спасибо за код. Сейчас попробую.

> написать merge в make файле сборщика и сливать технологии там.

Вот тут не понял, что это и зачем.

**Comment by verybigman** [comment]
Вот тут есть пример для bemhtml https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L63-L90

**Comment by belozyorcev** [comment]
Попробуй так
```
({
    mustDeps: { tech : 'bh.js', block : 'block-name' }    
})
```

**Comment by kompolom** [comment]
Спасибо всем за ответы, но все равно bh не доступен на клиенте. 
я так понимаю что в случае успеха технологию можно будет проверить через `modules.isDefined('bh');`  ?

**Comment by tadatuta** [comment]
@kompolom чтобы собрать BH на клиент, потребуется соответствующая технология для сборки.
готовой для `bem-tools`, кажется, нет, но по смыслу можно:

1. Взять технологию из https://github.com/bem/bem-components/pull/434/files
2. Сделать технологию browser.js+bh по аналогии с https://github.com/bem/bem-core/blob/v2/.bem/techs/browser.js%2Bbemhtml.js

Подробнее про технологии bem-tools можно узнать тут (ориентироваться нужно исключительно на `v2`): https://ru.bem.info/tools/bem/bem-tools/tech-modules/

Если потребуется помощь — пиши.

**Comment by kompolom** [comment]
> Вот тут есть пример для bemhtml https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L63-L90

Применительно к bh.js шаблоны куда соберутся? в `_index.js` ?

**Comment by kompolom** [comment]
Я пересел на `enb`  теперь у меня есть модуль `bh` на клиенте, но нет шаблонов

**Comment by andrewblond** [comment]
@kompolom какая технология написана в депсах: `bemhtml`, `bh`, `bh.js`? И какая указана тут https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L67? Они должны совпадать.

```js
({
    mustDeps: { tech : 'bh.js', block : 'block-name' }    
})
```

Ещё уточню, что в `bem-core` и `bem-components` везде указано `bemhtml`, поэтому на своём проекте удобнее всего указывать точно так же.

**Comment by kompolom** [comment]
Тоесть, в депсах пишу bemhtml, а пеально подключастя bh шаблоны?

**Comment by andrewblond** [comment]
> Тоесть, в депсах пишу bemhtml, а реально подключастя bh шаблоны?

Да ))

**Comment by kompolom** [comment]
Магия....

**Comment by apsavin** [comment]
Что за треш, зачем так сделали?

**Comment by zxqfox** [comment]
Да никто не использует BH просто

**Comment by kompolom** [comment]
Зачем сделали понять можно. Но вот как догадаться простому сметрному что для технологии `bh` нужно писать `bemhtml`...

**Comment by apsavin** [comment]
Нет, я не могу понять, зачем так делать, мне кажется, это полная жесть.

**Comment by zxqfox** [comment]
Да ну, смешно вроде. У вас просто нет чуства юмора...

**Comment by apsavin** [comment]
Какой нафиг юмор? Как такие вещи ревью проходят?

**Comment by zxqfox** [comment]
Да у меня истерика. Я не знаю :fire: :smile_cat:

@tadatuta Что за жесть? ;)))

**Comment by tadatuta** [comment]
@apsavin так сделали потому что в клиентском коде исторически был `BEMHTML.apply()`.
текущее решение позволяет добавить поддержку BH без поломки обратной совместимости.

**Comment by andrewblond** [comment]
На самом деле в `bem-components` сейчас нет ни одного блока, которые явно зависят от шаблонизаторов в `js` технологии. А все зависимости с `tech: bemhtml` написаны для тестов, поэтому для пользователей нет никакой разницы.

Всё так же можно собирать с депсами `tech: bh`, но нужно не забывать менять это тут  https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L67, т.к. `project-stub` не учитывает все варианты.

Но, если такие блоки появятся, то в `js`-коде будет подключаться `BEMHTML` модуль. В зависимостях можно будет прописать и `tech: bemhtml` и `tech: bh`, чтобы работало и так и так. Но BH нужно будет собирать с опцией `mimic: 'BEMHTML'`.

Почему `BEMHTML`, а не `BH`? Потому что `BH` умеет мимикрировать под `BEMHTML`, а `BEMHTML` нет.

**Comment by apsavin** [comment]
@tadatuta О какой обратной совместимости речь? Если авторы проекта меняют bemhtml на bh, они в любом случае заморачиваются, ничего страшного, если еще и конфиг сборки поменяют.

@andrewblond Если можно настроить сборку клиентских шаблонов bh, как клиентских шаблонов bh, а не bemhtml - именно так и нужно советовать людям, пожалейте их.

Вообще, если bemhtml в depsByTech может означать "клиентские шаблоны", а не bemhtml - то, наверное, нужно подумать о том, чтобы как-то эту ситуацию обрулить покрасивее.

**Comment by tadatuta** [comment]
@apsavin 

> О какой обратной совместимости речь? Если авторы проекта меняют bemhtml на bh, они в любом случае заморачиваются, ничего страшного, если еще и конфиг сборки поменяют.

Речь о том, что у нас есть огромная кодовая база, где в клиентском JS уже было написано `BEMHTML.apply()` и мы не можем «просто так взять и» переписать все эти блоки. При этом, учитывая, что шаблоны на BEMHTML и BH на одних и тех же входных данных дают полностью одинаковый результат, дать возможность бесплатно перейти на новый шаблонизатор было можно. Собственно @andrewblond все уже написал выше.

**Comment by apsavin** [comment]
@tadatuta но при этом можете "просто так взять и" переписать шаблоны для них на bh?

**Comment by tadatuta** [comment]
@apsavin да. это минорное изменение — добавление новой фичи. оно не требует сломать то, что работало.

**Comment by tadatuta** [comment]
@apsavin ну и еще раз: для новых проектов нет необходимости делать именно так.
эта фича нужна существующим проектам, для которых ее существование понятно и оправдано.

это тот тип девелопмента, когда реалии заставляют писать адовые юзерагенты, чтобы не взрывать сниффинг на кривых регекспах. мы бы рады обладая сегодняшним опытом и заранее зная как все будет, написать сразу хорошо. но возможности не учитывать существующую кодовую базу у нас нет. при этом, вроде как, никто из тех, кто начинает с чистого листа, пострадать не должен был.

**Comment by apsavin** [comment]
Видимо, мне не понять. 
Как может быть переписывание шаблонов с bemhtml на bh "минорным изменением"?
Этого нельзя было сделать исключительно на уровне компании?
__Если вы сделали костыль для себя, зачем советовать другим им пользоваться?__
bemhtml - это "какие-то клиентские шаблоны" в зависимостях навсегда?
На мой взгляд, когда ты пишешь bemhtml, а собирается bh - это и есть ситуация, когда что-то сломано.

**Comment by apsavin** [comment]
Вижу апдейт, пожалуй, после него самым важным оказывается вопрос, выделенный жирным.

**Comment by tadatuta** [comment]
@apsavin 
> Как может быть переписывание шаблонов с bemhtml на bh "минорным изменением"?

не переписывание, а дописывание рядом. а потом одной строкой в конфиге можно включать то один, то другой. например, сейчас Серп для старых браузеров под кодовым названием Бабуля благодаря наличию 2 полностью идентичных наборов шаблонов позволил на большом реальном проекте с реальной нагрузкой доказать, что скорость выполнения BEMHTML и BH практически одинаковая, хотя на синтетических тестах некоторый разрыв.

> Если вы сделали костыль для себя, зачем советовать другим им пользоваться?

текущая реальность такова, что:
1. мы внутри компании используем тот же код, который отдаем наружу.
2. есть необходимость писать клиентский js так, чтобы он мог работать с разными шаблонизаторами одновременно.

как бы ты решил эту задачу, если нужно сохранить обратную совместимость?

**Comment by apsavin** [comment]
Дописывание рядом == переписыванию по трудозатратам.

Ты немного лукавишь, так отвечая на вопрос про советы. Судя по дискуссии выше, вполне можно было объяснить, как настроить **новый** проект на использование bh, не прибегая к этому хаку.

Разумеется, в описанных тобой условиях задача не разрешима. Но можно:

1. переопределить какую-то часть на уровне компании. 
2. заложить, например, в версию 3 bem-core что-нибудь поизящнее и поочевиднее.

**Comment by tadatuta** [comment]
> Дописывание рядом == переписыванию по трудозатратам.

Усилия по написанию шаблонов — да, одинаковые. Но очень разные по стоимости внедрения. Я говорю именно о том, что в терминах semver называется минорным изменением по сравнению с мажором.

> Судя по дискуссии выше, вполне можно было объяснить, как настроить новый проект на использование bh, не прибегая к этому хаку.

И да, и нет. Прямо сейчас для пользователя bem-core/bem-components действительно можно.
Но если завтра мы опубликуем еще пачку блоков, где будет использоваться шаблонизация на клиенте, окажется, что вариант без хака будет работать только для одного шаблонизатора.

> переопределить какую-то часть на уровне компании.
> заложить, например, в версию 3 bem-core что-нибудь поизящнее и поочевиднее.

вся эта история находится в районе `enb-bh` и нигде больше. `bem-core` вообще ничего про это не знает. вот [вся мимикрия](https://github.com/enb-bem/enb-bh/commit/e40685b289570dcb1aa933edb33ff239a71c369c).

**Comment by apsavin** [comment]
Если библиотеки позиционируются, как работающие с любыми шаблонами, я думаю, нужно что-то придумывать, чтобы не прибегать к таким хакам. По крайней мере на новых проектах. Именно это я имел в виду, когда писал про bem-core v3.

Если закладывается такой неочевидный хак - нужно его максимально подробно, с пояснениями, почему так, описать в [документации](https://ru.bem.info/tools/bem/enb-bh/) к enb-bh.

**Comment by zxqfox** [comment]
@apsavin Штука, видимо, в том, что `<нечто>.apply(<bemjson>)` это стандартный способ вызова, который работает и в bemhtml, и в bh, и поэтому становится возможным мимикрация. Предложи как это описать?

**Comment by apsavin** [comment]
мимикрация)
В enb-bh нужно описать и проблему, и почему такое решение, и как им пользоваться с примерами, и что можно собирать просто bh, но это будет грозить тем-то и тем-то. На вопрос "как именно это описать?" я не знаю, как можно ответить, не описав, собственно, все это дело. Но проблемы в создании такой статьи не вижу никакой.

**Comment by zxqfox** [comment]
В целом, я строго за отсуствие пробелов в доке, и поддерживаю такие обсуждения, но мне не очень понятно к чему это односится, тезисы в статье/доке представляю смутно, и сам написать статью не смогу, поэтому далее помолчу.

**Comment by tadatuta** [comment]
@apsavin мы тоже против всего плохого и за все хорошее ;)
код и документацию пишем с той скоростью, с которой у нас хватает сил это делать. сейчас у нас есть 2 документатора: @innabelaya и @Murdalay, их усилиями у нас есть прекрасная документация к `bem-components` на двух языках и в процессе написания документация к `bem-core`, обновление общей документации по методологии, туториалы и многочисленные правки и актуализация существующих текстов. рано или поздно они дойдут и до всего зоопарка технологий для ENB, которые пока приходится описывать единственному разработчику @andrewblond. описание обязательно появится, но обещать, что это будет вот прямо скоро я, к сожалению, не могу.

**Comment by apsavin** [comment]
@tadatuta я бы написал, но сам все еще на bem-tools.(
