### ISSUE TITLE
Организация блока (совет/рабочие практики)

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-forum-content-ru#257]
Вот хотел бы посоветоваться с бывалыми :)

У меня есть блок (псевдо-ссылка), при клике на который должна открываться форма.
Так вот...

Как правильней было бы (чтобы было реально поддерживать)?
- Использовать разные блоки - а связь организовывать через каналы?
- Форму замиксовать как элемент вызывающего блока?

П.Н.
Если использовать 2-й вариант, то как можно использовать конструкцию ```findBlockOn``` для нахождения блока на элементе?
Или просто использовать поиск? ```this.findBlockInside('form')```

**Comment by tadatuta** [comment]
@belozyorcev оба варианта годные. еще можно использовать просто события, не только каналы.

```js
/**
     * Finds blocks on DOM elements of the current block or its elements
     * @param {String|jQuery} [elem] Block element
     * @param {String|Object} block Name or description (block,modName,modVal) of the block to find
     * @returns {BEMDOM[]}
     */
    findBlocksOn : function(elem, block) {
        return this._findBlocks('', elem, block);
    }
```

Как видно, `findBlockOn()` первым опциональным параметром принимает имя элемента или jQuery-ссылку на него.

**Comment by belozyorcev** [comment]
Спасибо :) Для практики решил работать с ```BEMDOM.blocks()```
