### ISSUE TITLE
Баг или фича? *.deps.js

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-forum-content-ru#261]
Не получается подрузить блок ```textarea``` из библиотеки ```bem-components```, используя ```*.deps.js```

Участок кода в bemjson
```
{
    block: 'event-form',
    tag: 'form',
    content: [
        {
            elem: 'desc',
            content: [
                {
                    block : 'textarea',
                    mods : { theme : 'islands', size : 'm', focused : true },
                    placeholder : 'Расскажи о событии'
                }
            ]
        }
    ]
}
```

event-form.deps.js
```
({
    mustDeps: [
        {
            block: 'textarea'
        }
    ]
})
```

```textarea``` всегда подгружается после элемента ```desc```.

Пробовал зависимости прописать в у элемента - не помогает.
Пробовал в ```deps.js``` блока после ```textarea``` добавить элемент ```desc``` - не помогло.

**Comment by Guria** [comment]
А пробовал вынести `textarea` из `bemjson` в `bemhtml`/`bh` шаблоны?
ЗЫ. изучение собранного .deps.js в бандле может натолкнуть на мысли о том, что происходит.

**Comment by tadatuta** [comment]
@belozyorcev если опубликуешь код, попробую помочь разобраться

**Comment by belozyorcev** [comment]
@tadatuta @guria

Перевёл форму на ```bh```. Подключил зависимости в нужном порядке, всё заработало.

Есть подозрение, что в deps.js нужно было указать не только ```textarea```, но и все модификаторы. Т.е. ```deps.js``` должен был иметь следующую зависимость.
```
({
    mustDeps: [
        { block: 'textarea', mods: {theme: 'islands', size: 'm'} }
    ]
})
```
Тестировать не хочется :)  Т.к. уже всё перевёл на bh.

П.Н.
```bem-stub``` собирал через генератор
