### ISSUE TITLE
Не выставляется модификатор js_inited

### ISSUE THREAD

**Issue by 4ok** [bem/bem-forum-content-ru#281]
Что необходимо добавить, чтобы при dom ready выставлялся  модификатор js_inited, для кастомного блока?

Вот простейший bemjson:
 ```js
({
    block   : 'page',
    content : {
        block  : 'block-a',
        js     : true,
        content: 'Content here...'
    }
});
```

Модификатор не выставляется. Что еще нужно добавить?

**Comment by apsavin** [comment]
Зависимость от i-bem__dom_init_auto?
