### ISSUE TITLE
Создание блоков в enb

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#283]
в bem-tools есть команда `bem create`, а что есть в `enb` для автоматического создания блока?

**Comment by Guria** [comment]
На сколько я знаю, ничего :(

**Comment by kompolom** [comment]
каждый раз вручную пишете обертки?

**Comment by sipayRT** [comment]
Есть вот такая штука в разработке - https://github.com/f0rmat1k/bemy 
Ну и никто не запрещает поставить рядом bem-tools и использовать по старинке ;)

**Comment by zxqfox** [comment]
@kompolom Вообще, мне лично хочется `bem-tools`, который будет использовать `enb` как сборщик, и тогда bem make будет делать то же самое, что и enb make, и bem server, и bem create будет доступен, ну не рай, не? Но этого нельзя сделать, потому что саму команду `bem` поставляет `bem-tools`, и его много кто использует вместе с `enb` ;-(

Видимо, пока только `bemy`, но хочется рая, не знаю даже, как можно навалится и что-то придумать, что и волки сыты, и овцы целы.

**Comment by tadatuta** [comment]
@zxqfox с тех пор, как @andrewblond запилил js api в ENB, это вполне возможно сделать ;)

**Comment by zxqfox** [comment]
@tadatuta Только придется очень много вырезать, да? А политбюро одобряет?

**Comment by tadatuta** [comment]
@zxqfox вроде даже можно сделать полностью обратносовместимо. и, кажется, теперь в вопросе `bem-tools` я сам себе политбюро ;)

**Comment by zxqfox** [comment]
@tadatuta Так ;-) А ты одобряешь?

**Comment by tadatuta** [comment]
дык а чего б я иначе писал? ;)

**Comment by zxqfox** [comment]
Кажется, что это просто быстро, и можно смотреть при запуске наличие `.enb/make.js`. Пилим issue?

**Comment by f0rmat1k** [comment]
Если вы используете депсы enb, то вам может особенно сильно может пригодится bemy, т.к. тулза умеет создавать стректуру элементов и модификаторов. Мне этого очень не хватало, поэтому я ее написал. Во второей версии добавлена возможность рекурсивно переименовывать любые бем сущность с возможностью переименовывания внутри файлов.

**Comment by tadatuta** [comment]
Ссылка на тул, про который говорит @f0rmat1k: https://github.com/f0rmat1k/bemy

**Comment by vithar** [comment]
@tadatuta так что, bem-tools 2.0 будет? ;)

**Comment by zxqfox** [comment]
@vithar Hey hey! не сглазь! ;-)

**Comment by andrewblond** [comment]
@vithar, @zxqfox я тоже за версию `bem-tools@2.0.0`, но @tadatuta, почему-то считает это минорным изменением...

**Comment by zxqfox** [comment]
@andrewblond а зачем 2.0 если у нас 1.0 так и не вышло в релиз? Или чтобы не мешать с тем, что к 1.0 готовили?

В любом случае, мажорную версию надо трогать только если есть BC, если же их нет — то это остается на совести автора/команды. Разве нет? ;)

**Comment by andrewblond** [comment]
> а зачем 2.0 если у нас 1.0 так и не вышло в релиз? Или чтобы не мешать с тем, что к 1.0 готовили?

Да, чтобы не путать с тем 1.x, который пытались сделать.

> В любом случае, мажорную версию надо трогать только если есть BC, если же их нет — то это остается на совести автора/команды. Разве нет? ;)

Что такое ВС? =) Для пользователей минорная версия выглядит как "фича". На самом же деле переход на ENB предпологает, огромные усилия для тех кто сидит `bem-tools@0.x`, и логично сложность такого перехода отобразить в мажорности версии. Кроме того, при выходе `2.0`, можно чесно объявить `0.x` не поддерживаемой и окончательно устаревшей.

**Comment by zxqfox** [comment]
BC = Back compat

Да, согласен. Правда, логика конфигураций в бемтулзах совсем другая, и окончательно устаревшей её объявить не получится, пока большинство не перейдет на свежак.

Конфиги это единственное, что меня пугает сейчас в enb, если не думать о том, что там внутри.

**Comment by andrewblond** [comment]
> Правда, логика конфигураций в бемтулзах совсем другая, и окончательно устаревшей её объявить не получится, пока большинство не перейдет на свежак.

Как посчитать это большинство? )

**Comment by apsavin** [comment]
@zxqfox По-моему, сначала что-то объявляют устаревшим, а потом все переходят на новое, а не наоборот. Я сам до сих пор сижу на bem-tools, но согласен, что давно пора объявить этот инструмент официально неподдерживаемым. Мне почему-то даже кажется, что это уже было сделано.)

**Comment by zxqfox** [comment]
@andrewblond https://github.com/bem/bem-tools/blob/release-1.0.0/lib/insight.js Почему-то казалось, что это есть везде, но к сожалению, этого нет в 0.9, только в 1.0.

@apsavin «обычно» это точно такое же оценочное суждение, что и мое «большинство». ;-) Но я думаю, что лучше сначала дать достойную альтернативу, а уже потом резать к чертовой матери. Сейчас альтернатива есть исключительно для make/build в enb, какие-то тулзы в bemy, а все остальное — под вопросом.

**Comment by andrewblond** [comment]
> По-моему, сначала что-то объявляют устаревшим, а потом все переходят на новое, а не наоборот.

Я тоже придерживаюсь такого мнения :)

> Мне почему-то даже кажется, что это уже было сделано.)

@apsavin был вот такой [пост](https://ru.bem.info/blog/bem-tools-status-freeze/) в блог про статус `bem-tools`. Статус «заморожен», означает, что развития не будет, но и не говорит, что не нужно этим пользоваться.

**Comment by tadatuta** [comment]
@andrewblond что за набросы? ;)
про минорный релиз я говорил в контексте того, что make можно сделать полиморфным и ни у кого ничего не сломается.

**Comment by zxqfox** [comment]
@andrewblond в любом случае, сложно куда-то переходить, когда некуда. Нет полноценной замены.

**Comment by apsavin** [comment]
@zxqfox для make/build - есть, это enb.
Все остальное, как я понимаю, предполагается сохранить. Не зря @tadatuta сказал про минорный релиз)

**Comment by andrewblond** [comment]
> что за набросы? ;)

@tadatuta, терпи! ))

> про минорный релиз я говорил в контексте того, что make можно сделать полиморфным и ни у кого ничего не сломается.

Я понимаю, что так можно. Но, почему то сомневаюсь, что это будет кому-то нужно, и что не создаст проблем.

> Все остальное, как я понимаю, предполагается сохранить.

Да, смысл в том, чтобы `make` поменять на ENB, а все остальные команды оставить.

**Comment by zxqfox** [comment]
@apsavin @andrewblond Ну да, есть еще bemy, но надо понимать, что в этом случае конфигов станет еще больше... И технологии для create... Меня это все несколько удручает, на самом деле ;-) Поэтому и нет такого энтузиазма и хочется модульную сборку, для начала, чтобы можно было все портировать уже со свежим и правильно собранным (с точки зрения текущей ситуации) кодом.

p.s. Если будете на кодфесте в Нске — можно голосом обсудить.

**Comment by tadatuta** [comment]
На кодфесте будут @vithar и @veged, а со мной можно пересечься на след. неделе в Мск.

**Comment by zxqfox** [comment]
@tadatuta Я всю след неделю буду в Кмр (250км от Нска на восток) ;-) Вернуть только после кодфеста
