### ISSUE TITLE
BEM team, можете обратить внимание на issue?

### ISSUE THREAD

**Issue by apsavin** [bem/bem-forum-content-ru#286]
[Проблеме](https://github.com/bem/bem-tools/issues/563) уже больше года. Актуальна для bem-tools и enb, судя по всему. Попытка вкорячить bootstrap - первое, с чего начинают очень многие новички. У них все ломается и они думают, что "bem не работает".

**Comment by zxqfox** [comment]
> Даже с помощью Мурси.

Ну что ты такое говоришь, с Мурсей возможно все!

**Comment by tadatuta** [comment]
@apsavin попробую достучаться до @doochik

**Comment by apsavin** [comment]
У меня не получилось, как видишь, даже после личного общения. Наверное, у него нотификация отключена.

**Comment by mursya** [comment]
Ребята, причем здесь Мурся? Моя задача — не глазки строить, а процессы налаживать в меру наших сил. Команда у нас маленькая, а раньше была еще меньше. Если сравнить то, что было сделано снаружи (а сделано было уйма всего, и соответственно уйма пользователей приросла) и внутри (а внутри у нас большой пласт работы, который никуда не делся), то это какая-то невероятная масса человеческих усилий. Шантаж и требования, увы, работают меньше, чем понимание и помощь. Понимание важно, так как ребята работают в прямом смысле круглые сутки. Мы же все-таки одно сообщество, все знаем друг друга лично, все друг с другом общаемся, все друг другу помогаем. Почему бы не продолжать это отношение человеческое вносить в каждый маленький кусочек нашей общей работы? Ну вот нашли старый ишью, не можете достучаться до Леши, пишете на форум и призываете нас. Но зачем вот миллион этого эмоционального сверху? Еще и + Мурся. Мне льстит, но сириозли, лишнее это. Давайте с места в карьер. Изложите проблему, сколько к ней не подходят, предложите свою помощь, быть может? Мы сделаем все возможное от нас, чтобы помочь вам, не сомневайтесь. Часть старых вещей только с вашей помощью и поднимаем, так как новых тонна, и они перекрывают. А ваша поддержка только ускорит это, даст нам и моральные силы тоже. Вон на западе, aweeeeesooomeeeee, и поддержка коммьюнити в миллион ретвитов. А у нас часто и без спасибо хорошо :( Поймите, все это опенсорсные коммьюнити вещи часто на энтузиазме делаются, а его поддерживать нужно, и помогать, и самим вливаться! Ведь только вместе мы — действительно сила!

**Comment by apsavin** [comment]
@mursya При том, что, как бы ты ни старалась, баги есть баги. Я вижу, что делается очень много всего - и мне кажется, что из-за таких вот вещей часть твоей работы просто проходит зря. Я боюсь, что эта часть может быть значительной. Прости, если это прозвучало как-то не так.

Это не шантаж и не требования, это попытка привлечь внимание - и не только к этому конкретному ишью, а к подобным проблемам вообще. Меня лично - как пользователя/потребителя - не касается ни это конкретное ишью, ни количество проблем, с которыми могут столкнуться новички.

**Comment by zxqfox** [comment]
@mursya Пост эмоциональный, конечно, но если отбросить эмоции, получается примерно: хочется заведующего по проектам, чтобы баги/ишью были только актуальными, и остальные правились по мере возможности, хотя бы чтобы был фидбек по ним и понимаете, что происходит.

**Comment by mursya** [comment]
Саша, 

мы знаем про все наши проблемы, но не все в силах решить. Привлекать внимание нужно, но в иной форме, как я написала выше. Мне кажется, что так будет и приятнее читать, и приятнее отвечать, и не будет передавать дальше негатив в сообщество, с которым в том числе и я борюсь. Каждое негативное комментирование — повод для тролинга. Зачем? Давайте просто вместе решать проблемы!

**Comment by mursya** [comment]
Леша, 

если находится проект без ответа, просто напишите, что вот проект без ответа, он все еще нужен, ответьте пожалуйста. Мы сделаем.

**Comment by mursya** [comment]
к слову, @doochik обещал до вечера посмотреть. если не посмотрит, я завтра снова ему напишу

**Comment by zxqfox** [comment]
Да мы пишем ;-) Но речь изначально была не о нас, а о новичках, насколько я понимаю. И это ишью не исключение. Может быть начать раздавать репозитории внешним разработчикам? Для начала тех проектов, которые вам не особо нужны, например, а кем-то используются.

**Comment by apsavin** [comment]
Мне кажется, слишком много слов про эмоциональность и негатив.) Ребята, я же уже объяснил выше, что имел в виду. Мурся, прости еще раз, вижу, что со стороны все это может выглядеть не очень красиво.

**Comment by mursya** [comment]
Саша, вот все, что некрасиво, поправь :) 

Леша, говорить за новичков — похвально, НО лучше им все-таки подавать хороший пример. В плане коммуникации тоже. Напомнили про старые репозитории, мы глянули, что-то ответили, договорились. Иногда старый проект может быть проектом, который отдать нельзя :( Бывают и внутренние сложности. 

Давайте вместе со всем разбираться, в общем! Дружно

**Comment by apsavin** [comment]
Erase And Rewind)

**Comment by mursya** [comment]
@doochik ответил в ишью https://github.com/bem/bem-tools/issues/563 и не только он

**Comment by apsavin** [comment]
Да, прямо обсуждение развернулось.
