### ISSUE TITLE
Из руководства по модификаторам, светофор(ы)

### ISSUE THREAD

**Issue by Bumerang47** [bem/bem-forum-content-ru#300]
Данный блок, https://github.com/bem/bem-js-tutorial/tree/master/pure.bundles/003-element-modifier/blocks/traffic-light реализует светофор. Если светофоров, блоками вставить несколько, то мигать будет только один, последний. 
Вопрос: почему так? 
Получается Модификатор применяется только к одному блоку, последнему или всё зависит от реализации кода js в модификаторе...

**Comment by tadatuta** [comment]
@Bumerang47 Потому что переменная `timer` объявлена в замыкании в рамках модуля и все экземпляры блока ее «делят» — последний проинициализированный блок в реакции на изменение модификатора `status` вызывает `clearTimeout(timer);`, т.о. сбрасывая таймер предыдущего блока.

Чтобы этого избежать, достаточно класть `timer` в `this`:
```js
'status' : function(modName, modVal, oldModVal) {
    clearTimeout(this.timer);
    var nextStatus = {
        'stop' : 'slow',
        'slow' : 'go',
        'go' : 'stop'
        },
        _this = this;
    oldModVal && this.setMod(this.elem(oldModVal), 'status', 'off');
    this.setMod(this.elem(modVal), 'status', 'on');
    this.timer = window.setTimeout(function(){
        _this.setMod('status', nextStatus[modVal]);
    }, 2000);
}
```

И вынужден предупредить, что, к сожалению, туториал несколько устарел.
Я попробую сегодня немного обновить и запушить в отдельную ветку, но полноценное обновление займет какое-то время.

**Comment by tadatuta** [comment]
Вот коммит с обновлением: https://github.com/bem/bem-js-tutorial/commit/11b4c45b303da6ea480bb55376786bea9f95b266

**Comment by Bumerang47** [comment]
Спасибо, всё ясно. На форум срочно нужна кнопка "Спасибо" =) 

По ходу прохождения руководства, постараюсь чем ни будь помочь в обновлении старых примеров. Очевидные поправки буду PullRequest'ить

**Comment by tadatuta** [comment]
@Bumerang47 обновили руководство на сайте, заодно переехали в правильный репозиторий https://github.com/bem/bem-js-tutorial/
Теперь должно быть все хорошо.
