### ISSUE TITLE
BEMDOM.scope и modal

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#305]
Уже второй раз наступаю на грабли с `BEMDOM.scope`
По клику создается блок `modal`  *без* модификатора `visible` . Далее следует код

    var popupEl = BEMDOM.append(this.domElem, BEMHTML.apply(bemjson));
    this.popup = this.findBlockOn(popupEl, 'modal');
    this.popup.setMod('visible', true); 

В результате получаю 

  > Uncaught TypeError: Cannot read property 'append' of null

В данном случае `null` - `BEMDOM.scope`. 
Если создавать блок `modal` c уже установленным модификатором, то все работает нормально...

Создавать `modal` сразу видимым не пойдет, там анимация на появление...
Как бороться?

**Comment by Guria** [comment]
Какая версия bem-core и bem-components?
Обновись, кажется эта проблема решена.

**Comment by kompolom** [comment]
bem-core 2.5.1
bem-components 2.0.0

**Comment by tadatuta** [comment]
@kompolom актуальные версии bem-core 2.6.0 и bem-components 2.1.0

**Comment by kompolom** [comment]
Да, все верно. После обновления проблема ушла.  Просто сталкивался с ней около года назад, думал ее давно уже исправили...
