### ISSUE TITLE
Содержимое поста удаляется полностью после ошибки "Не удалось добавить пост"

### ISSUE THREAD

**Issue by Guria** [bem/bem-forum-content-ru#307]
После нажатия кнопки "Добавить" появился alert с сообщением "Не удалось добавить пост", после нажатия на ОК содержимое формы было очищено.
Я очень-очень расстроен, что форум так поступил с моим любовно составленным текстом сообщения для форума.

Сама ошибка, похоже, вызвана протухшей авторизацией. Мне пришлось обновить страницу и авторизоваться повторно, что бы я смог написать это сообщение. Но я уже был готов к подлости и скопировал текст сообщения в буфер перед отправкой.

**Comment by tadatuta** [comment]
// cc @tavriaforever

**Comment by zxqfox** [comment]
Oh my... I'm so sorry!

**Comment by tavriaforever** [comment]
Those damn alerts! Will fix in.

**Comment by belozyorcev** [comment]
:D @Guria ситуация точь-в-точь

**Comment by tavriaforever** [comment]
Починили, спасибо за фидбек!
