### ISSUE TITLE
snapsvg && ymodules

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#321]
Подскажите, есть у кого-нибудь готовый snapsvg  в виде ym модуля?

**Comment by Guria** [comment]
```bash
bower install git://github.com/adobe-webplatform/Snap.svg.git
```
```js
modules.define('snap', function(provide){
 /* borschik:include:../../libs/Snap.svg/dist/snap.svg.js */
  provide(Snap);
});

**Comment by kompolom** [comment]
@Guria  Спасибо за ответ. Запускать этот код пробовал?

**Comment by Guria** [comment]
Нет, еще. Snap оформлен в нормальную обёртку и провайдит себя в переменную в локальной области видимости. Наша обёртка разместит её в ymodules.
Пробуй, должно работать

**Comment by zxqfox** [comment]
https://github.com/adobe-webplatform/Snap.svg/blob/master/dist/snap.svg.js — вроде да.

Кстати, если они поддерживают AMD, может быть устроить флешмоб и PR всем разослать с if (modules) modules.define(...)?

**Comment by Guria** [comment]
Надо бота, который будет находить обёртки для AMD на гитхабе и предлагать PR с modules :)

**Comment by kompolom** [comment]
> Пробуй, должно работать

Пробовал... Поэтому тут есть этот пост ))

**Comment by Guria** [comment]
Т.е. мой вариант тоже не сработал?

**Comment by kompolom** [comment]
@Guria, не тоже. Я так с самого начала и пробовал.
1. `window.document`  внезапно становится `indefined`
2. Snap  `undefined` Зато в this появляется window и snap.... 
3. Где то в недрах  он пытается найти `window.Snap`

**Comment by Guria** [comment]
@kompolom Пара минут в дебаггере.
Проверенный вариант:
```js
modules.define('snap', function(provide){
  this.document = window.document;
  /* borschik:include:../../libs/Snap.svg/dist/snap.svg.js */
  provide(this.Snap);
});
```
```js
modules.require(['snap'], function(snap){
console.dir(snap)
})
> Snap v0.3.0
```

**Comment by zxqfox** [comment]
@kompolom ну. подсунь ему свой `var window = {}`. не успел ;)

@Guria :+1:

**Comment by Guria** [comment]
Хм. Теперь у меня в демо проекте есть Snap. :) Чего полезного с ним сделать можно?
