### ISSUE TITLE
Ошибка при отображении второго блока с форматированием кода на форуме

### ISSUE THREAD

**Issue by Guria** [bem/bem-forum-content-ru#322]
@tavriaforever
На гитхабе:
![](https://api.monosnap.com/rpc/file/download?id=8D41TYrsFMRxOTogoPmu825ZeoCPse)
На форуме:
![](https://api.monosnap.com/rpc/file/download?id=3aqSKwriz8ZgISe6y8MMMIIShKVaGj)

**Comment by Guria** [comment]
<pre>
  ```bash
  bower install git://github.com/adobe-webplatform/Snap.svg.git
  ```
  ```js
  modules.define('snap', function(provide){
   /* borschik:include:../../libs/Snap.svg/dist/snap.svg.js */
    provide(Snap);
  });
</pre>

**Comment by sipayRT** [comment]
хм... знаю по себе, что между двумя кусками кода должна быть пустая строка. У меня в sublime в предпросмотрщике тоже без пустой строки все ломается :(

**Comment by Guria** [comment]
Упс. Ложная тревога. Не в строке дело было. Забыл закрыть второй блок кода.
