### ISSUE TITLE
Битая ссылка

### ISSUE THREAD

**Issue by Guria** [bem/bem-forum-content-ru#326]
https://ru.bem.info/libs/bem-core/v2.6.0/
> This README is also available in [English](https://bem.info/libs/bem-core/v2.6.0/).

В ссылке пропал поддомен en.

**Comment by sipayRT** [comment]
@gela-d посмотри, плз - в [bem-core ссылка правильная](https://github.com/bem/bem-core/blob/v2/README.ru.md)

**Comment by gela-d** [comment]
Привет! Спасибо, мы ее пофиксили тут https://github.com/bem/bem-core/pull/949/files, исправится в следующей версии bem-core
