### ISSUE TITLE
Неожиданная инициализация блока

### ISSUE THREAD

**Issue by Guria** [bem/bem-forum-content-ru#334]
Возникла непонятная проблема. Происходит инициализация блока на дом ноде, которой в bemhtml было задано js()(false).
В html всё нормально: класса i-bem нет, аттрибута data-bem тоже. Есть только имя класса блока.
Однако при наступлении live события этой DOM ноде внезапно инициализируется блок, при этом появляются и data-bem и block_js_inited и i-bem.
Пока не удалось локализовать в кусок, который мог бы опубликовать.
Может есть идеи почему так может произойти?

**Comment by Guria** [comment]
Нашёл:
в bemjson
```js
[
{
    block: 'blockB',
    js: true,
    content: {
      block: 'blockA',
      js: false,
      content: {
        block: 'input'
      },
    }
  },
  {
    block: 'blockA',
    js: true,
    content: {
      block: 'input'
    },
  }
]
```
в js
```js
modules.define('blockA', ['i-bem__dom'], function(provide, BEMDOM){
  provide(BEMDOM.decl(this.name, {
    onSetMod: {
      js : {
        inited : function() {
          console.log('init block A');
        }
      }
    }
  },{
    live : function(){
      this.liveInitOnBlockInsideEvent(
        { modName : 'focused', modVal : '*' },
        'input',
        function(){
          console.log('live of blockA');
        });
    }
  }));
});

modules.define('blockB', ['i-bem__dom', 'blockA'], function(provide, BEMDOM, BlockA){
  provide(BEMDOM.decl( {block: this.name, baseBlock:BlockA }, {
    onSetMod: {
      js : {
        inited : function() {
          this.__base();
          console.log('init block B');
        }
      }
    }
  },{
    live: false
  }));
});
modules.require('blockB', function(_){});
```
При клике в первый инпут инициализируется blockA у которого выставленно js(false).
Происходит это только при присутствии на странице другого blockA у которого выставленно js(true).

**Comment by Guria** [comment]
Укоротил:
```js
  {
    block: 'blockA',
    js: false,
    content: {
      block: 'input'
    },
  },
  {
    block: 'blockA',
    js: true,
    content: {
      block: 'input'
    },
  }
]
```

```js
modules.define('blockA', ['i-bem__dom'], function(provide, BEMDOM){
  provide(BEMDOM.decl(this.name, {
    onSetMod: {
      js : {
        inited : function() {
          console.log('init block A');
        }
      }
    }
  },{
    live : function(){
      this.liveInitOnBlockInsideEvent(
        { modName : 'focused', modVal : '*' },
        'input',
        function(){
          console.log('live of blockA');
        });
    }
  }));
});
```

Кажется, это довольно серьёзная бага.

**Comment by tadatuta** [comment]
@dfilatov Дима, подскажи, пожалуйста, это бага или фича?

**Comment by dfilatov** [comment]
Это не бага, это особенность live-блоков. Не может из них часть вдруг оказаться совсем без js. Непонятен реальный кейс такого использования.

**Comment by Guria** [comment]
Понял. Я нарвался на это дело случайно и не уверен, что мне этот кейс действительно нужен.
Более того, в текущем исполнении он явно пахнет. Если внимательно посмотреть первый комментарий можно увидеть, что же я пытался изобразить:
* js blockB отнаследован от js blockA
* bemhtml в blockB внутри вызывает `applyCtx({ block: 'blockA', js: false })`
* фокус работает, пока не появляется на странице { block: 'blockA', js: true }

Тем не менее такое поведение live инициализации показалось довольно нелогичным, хотя бы потому что вообще не ясно каким образом вопреки документации инициализируется блок без i-bem и data-bem.

Я покурил дебаггер и есть вопрос:
BEMDOM._findBlocks() действительно задуман искать все блоки, в том числе без js реализации? Кажется можно дополнить [селектор](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L353) проверкой класса `i-bem`.

**Comment by zxqfox** [comment]
Как-то пахнет, да.

Надо бы посмотреть много ли сломается, если поменять логику. Сложно оценить, стоит ли это менять так сразу.

**Comment by veged** [comment]
@Guria поиск блоков действительно задуман так, что ищутся все блоки, даже без собственного js-представления — это полезно, когда, например, верхнеуровневый блок хочет переставлять модификаторы внутренним, при этом внутренние могут быть без js

а можно рассказать про конкретную задачу — а то, судя по вопросам, кажется, что это можно было бы делать други, более предусмотренным нами, способом ;-)

**Comment by Guria** [comment]
Конечно же мне подходят более предусмотренные способы, которыми я уже восспользовался. Оригинальный вопрос снимается. Остаётся только небольшая недокументированная магия, когда происходит инициализация блока, который на [первый взгляд](https://ru.bem.info/libs/bem-core/v2.6.0/desktop/i-bem/#Синтаксис-привязки-блоков) инициализироваться не должен был.
И ещё сохраняется некоторая неконсистентность: "нежелательной" инициализации не происходило, если на странице не было второго такого же блока, но со включенным `js: true`.

**Comment by veged** [comment]
вообще мы не подразумевали, что инициализация может быть "нежелательной" — на блок либо есть js и тогда он предусматривает и нормально переносит инициализацию, либо js нет и тогда инициализация не создаёт никаких видимых эффектов

если на странице не встретилось ни одного `js: true` блока, то и `live` секция не исполняется — это специальная оптимизация
