### ISSUE TITLE
Как сделать блок из js-библиотеки?

### ISSUE THREAD

**Issue by raulleo** [bem/bem-forum-content-ru#350]
Не пойму как подгружать локальные скрипты и css-файлы сторонних JS-плагинов и библиотек таких, как Fancybox.

Создал ```common.blocks/fancybox/fancybox.js```:
```
modules.define('fancybox', ['jquery'], function(provide, $) {
});
```

А дальше что? Копипастить содержимое ```jquery.fancybox.js``` внутрь функции? Что провайдить? Как подключить ```jquery.fancybox.css```?

**Comment by apsavin** [comment]
[тут](https://github.com/bem/bem-forum-content-ru/issues/288) почитайте
