### ISSUE TITLE
Стили элемента с модификатором

### ISSUE THREAD

**Issue by bradbenetton** [bem/bem-forum-content-ru#381]
Почему не подтягиваются стили элемента с модификатором, если файловая структура блока следующая? Использую project-stub, bem-tools.
```
block/
    __elem/
        _mod
            block__elem_mod_value.css
```
Пример кода BEMJSON:
```
{
    block: 'block',
    content: [{
        elem: 'elem',
        mods: {
            mod: 'value'
        },
        content: 'content'
    }]
}
```

Пример блока https://github.com/bradbenetton/simple-bem-block

Спасибо!

**Comment by zxqfox** [comment]
@bradbenetton скорее всего, проблема с `.deps.js` ;-)

А если серьезно — данных мало, чтобы сказать наверняка.

**Comment by bradbenetton** [comment]
Отредактировал пост, дополнил описание.

**Comment by zxqfox** [comment]
```js
    {
        elem: 'elem',
        elemMods: {
            mod: 'value'
        },
        content: 'content'
    }
```
А так работает? ;-)

/cc @tadatuta Я так и не понял, зачем это разделение на mods и elemMods. Если надо модификаторы к блоку — всегда же можно добавить микс:
```
    {
        elem: 'elem',
        mods: { mods: 'value' },
        mix: { mods: { 'blockmod': 'modvalue' } },
        content: 'content'
    }
```

**Comment by bradbenetton** [comment]
Да, работает =) Спасибо!

**Comment by tadatuta** [comment]
@zxqfox модификаторы нужно различать в предикатах шаблонов, а тут оно сделано для консистентности, насколько я понимаю

**Comment by zxqfox** [comment]
@tadatuta а нельзя починить? или спрятать кишки шаблонизатора назад в пузо?

**Comment by zxqfox** [comment]
https://github.com/bem/bem-method/issues/250 — завел вопрос.

@bradbenetton есть бесполезная кнопка «вопрос решен» ;-), поможет в будущем, когда будет поиск.
