### ISSUE TITLE
Пожелание по документации i-bem

### ISSUE THREAD

**Issue by isuvorov** [bem/bem-forum-content-ru#407]
Есть пожелание расписать по подробнее про передачу js-параметров блоки и то, как с ними работать
например, про то, что в setMode/js/inited  их можно получить из this.params

а то, сейчас новичку вообще не очевидно, как с ними работать
сам понял только на 5+ день изучения, просмотрев  чужие блоки

**Comment by tadatuta** [comment]
@isuvorov спасибо, завел задачу об этом: https://github.com/bem/bem-core/issues/1019

**Comment by tadatuta** [comment]
https://ru.bem.info/technology/i-bem/v2/i-bem-js-params/
