### ISSUE TITLE
Верстка по БЭМ

### ISSUE THREAD

**Issue by badimalex** [bem/bem-forum-content-ru#419]
Изучаю подход к правильному наименованию.
Мастера, гляньте пожалуйста на верстку. что не так, что можно сделать лучше? спасибо.
http://www.codeshare.io/gEwmr
http://www.codeshare.io/0insy

.. можно как то при написании стилей(stylus) избежать дублирования названий ? (не писать __item_active, а вложить _active в __item ) ?
```
&__item
    padding 20px 0
    margin-right 20px
&__item_active
```

**Comment by tadatuta** [comment]
Основное несоответствие, которое я заметил — это то, что используются элементы элементов (`article__line__item`). Так делать не рекомендуется, т.к. затрудняет рефакторинг (при изменении разметки придется менять CSS).

**Comment by badimalex** [comment]
понял. спасибо. я так делал, потому что эти элементы имеют одинаковый отступ. наверное будет лучше если в css заюзаю  extends
