### ISSUE TITLE
Блок без BEMHTML из библиотеки выпадает в ошибку

### ISSUE THREAD

**Issue by bradbenetton** [bem/bem-forum-content-ru#434]
Всем привет!

Создаю свою библиотеку, один из блоков без `BEMHTML` (для него описал только стили). При подключении библиотеки выдается ошибка `ENOENT`, что нет `BEMHTML`. Так и должно быть или это глюк?
Если создать пустой `BEMHTML`, то все работает.
Собираю проект с помощью enb. Кеш скидывал.

**Comment by blond** [comment]
Привет!

> Так и должно быть или это глюк?

Такого быть не должно :)

Давай разбираться:

* Какая версия `enb`?
* Каким пакетом собирается BEMHTML?
* Что указано в опции `levels` к технологии `levels`?
* Как скидываешь кэш?

Если можешь, то расскажи поподробней о том, как воспроизвести ошибку. Например:

1. Создать файл.
2. Запустить сборку.
3. Удалить файл.
4. Запустить сборку.

**Comment by bradbenetton** [comment]
Попробовал на чистом `project-stub`, ошибка не повторилась. Завтра с утра еще посмотрю, отпишусь.

**Comment by bradbenetton** [comment]
И на проекте перестала воспроизводиться, видимо руки кривые.

**Comment by zxqfox** [comment]
Скорее всего, проблема была в кеше: там сохраняется информация о файловой структуре и он по ней ищет файлы, считая что файлы есть.

@blond поправь, если соврал.

**Comment by blond** [comment]
@zxqfox, да, всё так.

**Comment by bradbenetton** [comment]
Ага, я кеш не правильно скидывал.
