### ISSUE TITLE
Gemini для тестирования состояний страницы после взаимодействий в RWD

### ISSUE THREAD

**Issue by plisovyi** [bem/bem-forum-content-ru#443]
Привет.

У меня довольно абстрактно/утилитарный вопрос. Есть проект, responsive web design. 5 breakpoins. На них есть кнопки, вызывающие дейтпикер. 
Задача — провести визуальное тестирование страниц на наборе ширин viewport'а. 
Чего я ищу, по сути — одного теста, но на наборе ширин, и с выполнением "before each" определенных взаимодествий. 

Подскажите пожалуйста, возможно ли это с помощью gemini, и если да — как.

**Comment by sipayRT** [comment]
@SevInf Серега, твой выход :)

**Comment by SevInf** [comment]
Привет.
Если я правильно понял вопрос, то можно обойтис каким-то таким кодом:

```javascript
var sizes = [
   // Перечисляем все нужные размеры
   {width: 1024, height: 768},
   {width: 640, height: 1136},
   {width: 320, height: 480},
]

sizes.forEach(function(size) {
    gemini.suite(size.width + 'x' + size.height, function(suite) {
           suite.before(function(actions) {
                  actions.setWindowSize(size.width, size.height);
           });
          // Ниже пишем наш тест.
    })
});
```

**Comment by maryMariia** [comment]
@SevInf  спасибо за хорошее решение)
