### ISSUE TITLE
Gemini Plugins: query

### ISSUE THREAD

**Issue by plisovyi** [bem/bem-forum-content-ru#445]
Есть довольно распространенный запрос тестировщиков к Gemini — возможность делать селекторы XPath. 
На мой скромный взгляд это очень просто реализовать, глядя например, на существующие query «методы» (sizzle && native), тем не менее хотелось бы услышать мнение, насколько это представляется возможным (в смысле реализации в виде плагина).

**Comment by sipayRT** [comment]
@SevInf это опять к тебе

**Comment by plisovyi** [comment]
@sipayRT может мне его сразу тегать? 
Или прийти в гиттер? А то у меня, я чувствую, будет много ~~глупых~~ вопросов :-)

**Comment by SevInf** [comment]
Добрый день.
API плагинов сейчас довольно скудное, и это с его помощью в данный момент без хаков сделать нельзя. Я открыл задачу gemini-testing/gemini#173, там можно будет следить за прогрессом или предложить свой вариант такого API. Самый быстрый вариант получения нужной функциональности это, как обычно, посылка пулл-реквеста:)
А в вопросы про gemini можно сразу меня звать.

**Comment by tadatuta** [comment]
@plisovyi 
> Или прийти в гиттер?

Лучше на форуме — так ответы окажутся доступны и другим пользователям.
