### ISSUE TITLE
ibem.js и событие onload (для img)

### ISSUE THREAD

**Issue by AndreyGladkov** [bem/bem-forum-content-ru#456]
Собственно вопрос, как  методах экземпляра блока поймать событие загрузки изображения?
```
elem.onload = function(){}
```
не помогает. Думал что как клик работать будет, но что то не работает(

**Comment by Guria** [comment]
elem - это jQuery коллекция. Вам надо либо достать из неё DOM-элемент, например с помощью  elem[0] или [использовать соответствующий метод jQuery](https://api.jquery.com/load-event/)

**Comment by AndreyGladkov** [comment]
да понятно что я обращался к конкретной ноде, метод не срабатывает

**Comment by Guria** [comment]
ну i-bem тут не при чём. см. например:
http://javascript.ru/forum/misc/8772-kogda-srabatyvaet-image-onload.html
http://stackoverflow.com/questions/3877027/jquery-callback-on-image-load-even-when-the-image-is-cached

**Comment by AndreyGladkov** [comment]
ну да, а когда я юзаю блок  не как ibem, тогда все работает)
