### ISSUE TITLE
инициализация по BEM событию

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#457]
https://ru.bem.info/libs/bem-core/v2.6.0/desktop/i-bem/#init-live

> Если необходимо инициализировать экземпляры блока по наступлению DOM- или БЭМ-событий, в теле функции следует выполнить подписку на делегированные события. Возможна инициализация по: 
* DOM-событию на DOM-узле блока и вложенных элементах;
* БЭМ-событию на вложенных блоках.

Хотелось бы увидеть в документации пример ленивой инициализации по BEM событию.

**Comment by Guria** [comment]
https://ru.bem.info/tutorials/bem-js-tutorial/03-live-initialization/
https://github.com/bem/bem-components/search?utf8=%E2%9C%93&q=liveInitOnBlockInsideEvent&type=Code
