### ISSUE TITLE
Теги внутри текста

### ISSUE THREAD

**Issue by mikvys** [bem/bem-forum-content-ru#458]
Здравствуйте. Подскажите, как можно добавить тег внутри текста? Например 
```
block: 'text',
content: 'ТекстТекстТекст<a class='link' href="">Текст</a>ТекстТекстТекстТекстТекстТекст'
```
Можно такого добиться с помощью bemjson как нибудь?

**Comment by Guria** [comment]
Ваш пример был покорёжен парсером, но предложу следующие варианты:
```js
{
    content: [
        'text',
        { tag: 'br' },
        'text',
        { tag: 'a', attrs: { 'href': 'url' }, content: 'text' },
        '<pre>sdfsdfs</pre>'
    ]
}
'''
На выходе получим
```html
<div>text
    <br/>text<a href="url">text</a><pre>sdfsdfs</pre>
</div>
```
Можно воспользоваться песочницами [BH](http://bem.github.io/bh/) или [BEMHTML](https://rozhdestvenskiy.ru/dev/bemhtml/) для просмотра результата в браузере.

**Comment by tadatuta** [comment]
Дополню, что если нужно вставить просто тег, который не является блоком, то можно прямо так и писать:
```js
{
    content: 'Текст<br>текст'
}
```

**Comment by mikvys** [comment]
Спасибо)
