### ISSUE TITLE
Не запускается project-stub

### ISSUE THREAD

**Issue by rtxrulez** [bem/bem-forum-content-ru#461]
Выводит ошибки при обновление страницы.

06:51:29.335 - [failed] [desktop.bundles/index/index.html] html-from-bemjson
RangeError: Maximum call stack size exceeded
    at __$b114 (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:1104:17)
    at applyc (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:111:20)
    at __$b114 (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:1121:5)
    at applyc (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:111:20)
    at __$b114 (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:1121:5)
    at applyc (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:111:20)
    at __$b114 (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:1121:5)
    at applyc (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:111:20)
    at __$b114 (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:1121:5)
    at applyc (/home/rtx/pr/start-project/desktop.bundles/index/index.bemhtml.js:111:20)
06:51:29.706 - [rebuild] [desktop.bundles/index/_index.js] borschik

lubuntu 15.04

Версии:
iojs --version
v1.8.1

npm --version
2.7.4

**Comment by tadatuta** [comment]
@rtxrulez Вчера сломали `xjst` вот [этим коммитом](https://github.com/veged/xjst/commit/b0c8281735c16b7a6b5134e7e06cc186b302bc5b), из-за мягких зависимостей в `bem-xjst` версия подтянулась :(

Сегодня опубликуем исправление.

Прямо сейчас можно решить проблему, если поставить `bem-xjst` по ссылке https://github.com/bem/bem-xjst/archive/master.tar.gz

**Comment by AlesyaLobatch** [comment]
Подскажите пожалуйста, я сегодня первый день постигаю БЭМ и github, так что прошу прощения за глупый вопрос наверно.. когда исправление будет опубликовано - нужно заново будет выполнить сию процедуру
 $ git clone https://github.com/bem/project-stub.git - и проект клонируется уже с исправлением?

**Comment by tadatuta** [comment]
Да. Я отпишу в этот тред, когда исправление будет опубликовано.

**Comment by apsavin** [comment]
@AlesyaLobatch Когда исправление будет опубликовано - не обязательно будет клонировать заново project-stub, можно будет просто обновить bem-xjst в проекте, склонированном ранее. Может быть, это и так понятно, но я решил все-таки написать.)

**Comment by zxqfox** [comment]
Ах вон оно чо.

**Comment by sipayRT** [comment]
одним обновлением поломали половину интернета :)

**Comment by zxqfox** [comment]
не то слово.

кстати, мы тут вчера нашли, что в dev режиме проект собрался без этого.

Если проект на базе project-stub и enb: `BEMHTML_ENV=dev enb make`
Или руками попробуйте пробросить `devMode: true`, пока фикса нет.

**Comment by sipayRT** [comment]
а не проще у себя локально версию xjst откатить?

**Comment by zxqfox** [comment]
@sipayRT при автовыкатках это сильно сложнее)

**Comment by voischev** [comment]
> одним обновлением поломали половину интернета :)
+ 2

**Comment by zxqfox** [comment]
@voischev 3 половины интернета? ;-)

**Comment by AlesyaLobatch** [comment]
@apsavin понятно то понятно, но я же написала, я первый день имею дело вообще со всем этим и я не знаю как обновить эту отдельную папку.

**Comment by zxqfox** [comment]
@AlesyaLobatch найдите у себя эту строчку

**Comment by AlesyaLobatch** [comment]
@zxqfox премного благодарствую!:)

**Comment by sipayRT** [comment]
Или так:
```
cd node_modules/enb-bemxjst/node_modules/bem-xjst
npm i xjst@1.5.0
cd ../../../../
```

@zxqfox но твой способ как-то проще выглядит ;)

**Comment by zxqfox** [comment]
@sipayRT стоит заметить, что они разные) для продакшна лучше твой использовать)

**Comment by tadatuta** [comment]
@zxqfox @sipayRT @AlesyaLobatch @voischev @rtxrulez @apsavin всё ребят, фикс выехал. Простите за упячку, постараемся подстелить в этом месте соломку, чтобы не повторялось впредь.

**Comment by zxqfox** [comment]
@tadatuta 
![image](https://cloud.githubusercontent.com/assets/677518/8235449/bbe00a4a-15ea-11e5-9cec-a8d1b38c4486.png)

**Comment by sipayRT** [comment]
@zxqfox @tadatuta все, закрываем костыльную фабрику до следующего факапа :) было весело, всем спасибо
