### ISSUE TITLE
Импорт страницы

### ISSUE THREAD

**Issue by OlgaVoz** [bem/bem-forum-content-ru#465]
Ребята, помогите решить задачку, хочется сделать по уму:

У меня есть две страницы в bundles: page1 и page2. Эти страницы очень похожи, разница в том, что page2 немного более расширена ( добавляются информационные блоки). В результате нужно иметь две страницы с чистым исходным кодом ( чтобы дополнительные блоки были только на странице page2).

Так как дизайн дорабатывается, да и для удобства поддержки, не хочется дублировать одинаковые на этих двух страницах вещи. Одинаковый блок, кроме текста, содержит ещё компоненты ( как стандартные из bem-components, так и самописные), да и вообще, представляет собой внушительную портянку.

Как сделать правильнее? Я пока вижу такие варианты:

1. создать блок common_page и в bemhtml прописать там всю информацию для общей информации. После этого, подключать этот блок на странице page1 и page2. Отсюда возникают вопросы, правильно ли писать столько html в данном случае ( в bemjson около 1500 строк кода ) и будут ли работать стандартные и самописные компоненты? Ну и, конечно, переписывать 1500 строк кода совсем не хочется.

2. придумать что-то типа @import(page1) для страницы page2. Возможно ли такая реализация?

3. попытаться решить через модификатор ( расширенная страница - page2 или обычная - page1). Но при этом у меня должно в bundles так и остаться 2 физические страницы с чистым кодом. Как тогда организовать работу модификатора?

**Comment by zxqfox** [comment]
В `bemjson.js` бандла можно использовать `require('fs').readFileSync('your-common-parts.js')`, т.к. это javascript
И в файле `your-common-parts.js` написать нужны контент примерно так:
```
module.exports = {
  block: 'hola!',
  content: '...'
};
```

**Comment by tadatuta** [comment]
Подробности обсуждали в https://ru.bem.info/forum/214/#comment-73360939

**Comment by OlgaVoz** [comment]
Спасибо за ответы! Буду разбираться.

**Comment by OlgaVoz** [comment]
Попробовала оба варианта и столкнулась с проблемами:

1. Вариант от @zxqfox:
Мои две странички: page1 и page2. Параллельно к ним добавилась папка page-common, c файлом page-common.js. 
Сформировала файл как в примере, перенеся свою портянку в контент. В файле ошибка на строку: module.exports ( Unresolved variable or type module).
Файл бандла выглядит так:
                ...
                {
                    block: 'left',
                    content: require('../page-common/page-common.js').append([
                        { block : 'hole', content: 'additional content here' }
                    ])
                    /*content: перенесенная портянка*/
                    ...
                 },...
Страница не собирается, ругается на require.


2. Вариант от @tadatuta:
Мне подходит вариант под номером 3.3, т.к. в моем случае правильнее оставить контент в bejson, а не перегонять его в html. 
- правлю расширения для страницы page1 с bemjson.js на bemdecl.js
- добавляю настройки для ENB ( правлю папку .enb, package.json)
- исправляю бандл под вид:
                    block: 'left',
                    exports.blocks = [
                        {
                            "name": "page-common"
                        } 
                    ];
Данная конструкция выдает ошибки в написании exports.blocks, проект не собирается.


Пробовала заклонить и собрать проект с этого коммита: https://github.com/tadatuta/bem-bemtree-static-project-stub/commit/5f19a54dac7fa09ea0ee8575cd6f2f026447416a , но проект тоже не запустился ( выдается ошибка: Error: ENOENT, no such file or directory '.../project-stub/desktop.blocks . Файл index.bemdecl.js лежит по пути: desktop.bundles/index)

Какие есть пути решения? В чём ошибка?

**Comment by tadatuta** [comment]
@OlgaVoz

В обоих случаях есть ошибки в коде.

В варианте с `require` важно учитывать, что BEMJSON должен экспортироваться как `CommonJS` модуль (начинаться с `module.exports = { block: 'page', /* ... */ }`) и что `require('../page-common/page-common.js')` вернет объект, который экспортируется в данном файле, метода `append` у него, конечно, нет.

Проблема с `bem-bemtree-static-project-stub` (git не умеет версионировать пустые папки и папка `desktop.blocks` изначально не попала в репозиторий) была исправлена в последующих коммитах, стоит использовать последний актуальный.

Но в приведенном сниппете кода все равно есть ошибка. В `bemdecl.js` ожидается строго
```js
exports.blocks = [
    {
        "name": "имя-блока"
    },
    {
        "name": "имя-блока-2"
    },
];
```
чтобы просто перечислить используемые блоки, которые затем попадут в сборку, он не предназначен для генерации HTML. Чтобы сгенерировать HTML, потребуется выполнить BEMTREE-шаблоны, которые вернут BEMJSON, а уже из него получится HTML.

Если нужно, могу записать поясняющие видео, как начать разрабатываться с любым из вариантов.

**Comment by zxqfox** [comment]
> метода append у него, конечно, нет.

Если это будет массив — то метод append будет ;-)

**Comment by tadatuta** [comment]
@zxqfox, ты, наверное, про `push`?

**Comment by zxqfox** [comment]
@tadatuta Ок, я наркоман. Не `.append`, а `.concat`. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

**Comment by OlgaVoz** [comment]
@tadatuta , спасибо большое, было бы просто здорово! 

Я остановилась на первом варианте, который предложил @zxqfox. Пока у меня выглядит всё так:

Общий файл  ( Unresolved variable or type module):
        module.exports = {
            block: 'wk1lesson',
            content: [...]
        };

Бандл с подключением (Exspression statement is not assignment or call): 
       {
                    elem: 'left',
                    content: require('../../common.blocks/wk1lesson/wk1lesson.js')
       }

При сборке выдается ошибка: Error: Option "sourceTech" is required for technology "deps-by-tech-to-bemdecl".

Может мне необходимо подключать дополнительные скрипты в bower.json и/или отредактировать make.js?

**Comment by tadatuta** [comment]
Самый важный момент — прямо сейчас версия `bem-tools` с поддержкой `require` все еще не выпущена (ее можно поставить из ветки, но лучше использовать `ENB`).

Чтобы описанное выше заработало для ENB, для текущей версии `project-stub` потребуется вот такой дифф https://github.com/bem/project-stub/compare/require?expand=1

Если использование `bem-tools` принципиально важно, в принципе могу попробовать завтра таки выпустить версию. Но так или иначе это будет последняя версия, поддерживающая `bem make`, дальше `bem-tools` перейдет на использование `ENB` под капотом в любом случае.

**Comment by OlgaVoz** [comment]
@tadatuta, нет, совсем не принципиально, ENB вполне устраивает. 
Спасибо большое, всё получилось!
