### ISSUE TITLE
b-layout-table преобразовывается в div, а не table

### ISSUE THREAD

**Issue by ggcstop** [bem/bem-forum-content-ru#467]
Собственно b-layout-table преобразовывается в div, а не table. Примеры даже с документации копировал, все равно на выходе из json получаю div. то я делаю не так?

**Comment by apsavin** [comment]
Не написали шаблон для блока?
Написали его неправильно?
Неправильно настроили сборку?
Опечатались в имени блока?

Очень абстрактное описание проблемы. Выложите код на гитхаб, что ли, а то так долго можно гадать.

**Comment by tadatuta** [comment]
`b-layout-table` — это блок из `bem-bl`. Предположу, что используется проект на основе `bem-core`, где этого блока в принципе нет.

**Comment by ggcstop** [comment]
@tadatuta действительно, проблема была в этом. Только изучаю БЭМ, не понимал еще этого. Спасибо.
