### ISSUE TITLE
Ошибка в документации

### ISSUE THREAD

**Issue by apsavin** [bem/bem-forum-content-ru#472]
Вот здесь https://ru.bem.info/technology/i-bem/v2/i-bem-js/#%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0-%D0%B2-%D0%B4%D0%B5%D0%BA%D0%BB%D0%B0%D1%80%D0%B0%D1%86%D0%B8%D0%B8

Вместо `modules.define('button', ['i-bem'], function(provide, Button) {`

Должно быть `modules.define('button', function(provide, Button) {`

Не нашел репозиторий bem.info, чтобы поправить самому. Почему нету на него ссылки нигде на сайте? Или какой-нибудь штуки типа "нашли ошибку?".

**Comment by tadatuta** [comment]
Привет! Спасибо за репорт!
Прямо сейчас дорабатываем [новую версию референса по i-bem.js](https://github.com/bem/bem-core/pull/1029), похоже, что там этой ошибки уже нет.

> Почему нету на него ссылки нигде на сайте? Или какой-нибудь штуки типа "нашли ошибку?".
Мы не так давно оторвали ссылку на prose.io, которая была на каждой странице в пользу просто приглашения писать об ошибках на почту (на форум — тоже ок). Причина в том, что у нас немалая часть документации публикуется к определенным версиям библиотек (т.е. по коммиту, на котором установлен тег) и зачастую автоматически сложно вычислить, в какую ветку предлагать фикс.
Я надеюсь, что рано или поздно дойдут руки решить эту проблему и вернуть ссылку. А пока могу лишь сказать, что большая часть контента лежит bem.info берется из https://github.com/bem/bem-method/, референсы из репозитория bem-core, а документация на инструменты — из репозиториев соответствующих инструментов.
