### ISSUE TITLE
БЭМ и  PHP

### ISSUE THREAD

**Issue by Zidcov** [bem/bem-forum-content-ru#478]
Подскажите пожалуйста, возможно ли я и как это сделать.
Допустим я использую технологии i-bem.js, BH  и др для формирования HTML+CSS.
а я могу вариант данной верстки использовать с php? Или вся верстка  динамически формируется только с помощью Node.js?

**Comment by Guria** [comment]
https://github.com/bem/bh-php
cc @zxqfox

**Comment by Zidcov** [comment]
Спасибо, Guria

**Comment by zxqfox** [comment]
@Zidcov https://github.com/bem/bem-components-php — кажется, этого для начала должно хватить. Баг репорты принимаются, PR — тем более ;-)

**Comment by Zidcov** [comment]
Благодарю, zxqfox
