### ISSUE TITLE
Добавить необходимость замены `elemName` на `elem` руководстве по миграции

### ISSUE THREAD

**Issue by h4** [bem/bem-forum-content-ru#506]
В процессе миграции на `bem-core` обнаружил, что метод `liveBindTo` больше не принимает объект с ключом `elemName`, а ожидает строго `elem`. В руководстве по миграции об этом не указано, к сожалению.

**Comment by innabelaya** [comment]
Миша, спасибо за фидбек! Добавили в migration guide: https://github.com/bem/bem-core/blob/v2/MIGRATION.ru.md#Метод-livebindto. Скоро появится на сайте.
