### ISSUE TITLE
Добавить в руководство по миграции изменение сигнатуры метода findElem

### ISSUE THREAD

**Issue by h4** [bem/bem-forum-content-ru#509]
При миграции на bem-core больше нельзя указать контекст для поиска элемента строкой. Нужно обязательно передать jQuery-объект. Ну да, лучше так вообще не делать ;)

https://github.com/bem/bem-bl/blob/support/2.x/blocks-common/i-bem/__dom/i-bem__dom.js#L791 vs https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L725

Было:
```
var nestedElem = this.findElem('parent-elem', 'nested-elem');
```
Стало:
```
var nestedElem = this.findElem(this.findElem('parent-elem'), 'nested-elem'),
    oneMoreElem = this.findElem(this.elem('another-elem'), 'nested-elem');
```

**Comment by tadatuta** [comment]
cc @innabelaya

**Comment by innabelaya** [comment]
@h4 Миша, спасибо, добавим!

**Comment by innabelaya** [comment]
Миша, спасибо за фидбек! Добавили в migration guide: https://github.com/bem/bem-core/blob/v2/MIGRATION.ru.md#Метод-findelem. Скоро появится на сайте.
