### ISSUE TITLE
Модификатор на «внучатый» элемент

### ISSUE THREAD

**Issue by rodweb** [bem/bem-forum-content-ru#513]
Всем привет! Такой у меня вопрос:

Есть блок `aside`, он располагается сбоку и в общем случае выглядит вот так: [ссылка на картинку](http://joxi.ru/NDrlJ47u1aKX2P.png)
Логотип вынесен в отдельный блок `logo`, у него есть текстовые элементы `logo__bold`, `logo__thin` и `logo__desc`.
У `aside` есть модификатор `--collapsed`, который делает его узким: [ещё ссылка на картинку](http://joxi.ru/gV2VzZRsn6GD2v.png)

Как тут можно грамотно распространить влияние модификатора `aside--collapsed` на элементы блока `logo`?
Как `.aside--collapsed .logo__desc { display: none; }`, но в контексте БЭМ.

**Comment by tadatuta** [comment]
Вариант `.aside--collapsed .logo__desc { display: none; }` вполне годный, см. https://ru.bem.info/method/faq/#Почему-нежелательно-использовать-вложенные-селекторы

**Comment by rodweb** [comment]
Спасибо! Подумал, что это может негативно сказаться на независимости блоков, например, если со временем блок `logo` мутирует во что-то другое, а стили для него останутся.

**Comment by tadatuta** [comment]
Общая идея в том, что родитель может знать о потомках, а потомки о родителе знать не должны. И, соответственно, весь код, который знает про `aside`, нужно хранить рядом с `aside`, даже если он в результате влияет на `logo`. Тогда стили логотипа всегда буду независимыми, а вот боковая панель, которая умеет сжиматься, будет вынуждена знать про то, как она сжимает то, что в нее вложено.
Впрочем, в данном конкретном случае можно попробовать ко всем вложенным в `aside` блокам и/или элементам, которые следует прятать при `aside--collapsed`, [примиксовать](https://ru.bem.info/method/definitions/#%D0%9C%D0%B8%D0%BA%D1%81) элемент самого блока `aside`. Получится что-то типа:

```html
<div class="aside">
    <div class="logo">
        <div class="logo__desc aside__item"></div>
    </div>
</div>
```
и аналогично для остальных скрываемых элементов.
Тогда в стилях достаточно будет:
```css
.aside--collapded .aside__item {
    display: none;
}
```
