### ISSUE TITLE
доопределение live

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#533]
Имеется блок в базовой реализации и с модификатором.
У базового блока есть свойство live в котором выполняется подписка на события.
В тот же блок с модификатором. Код в `live` выполняется, но блок на новые события не реагирует. В чем может быть причина?

**Comment by tadatuta** [comment]
есть возможность где-нибудь опубликовать код, на котором воспроизводится проблема?

**Comment by kompolom** [comment]
Записал в декларации блока полностью

````
 {block: 'myblock', modName: 'editable', modVal: true}
````

И все стало работать. Странно, потому что в других случаях писал только модификатор и значение, и все было Ок... 
@tadatuta, есть какие то нюансы, в том когда нужно полностью декларацию блока писать?

**Comment by tadatuta** [comment]
@kompolom должно работать без явного указания имени блока для модификатора.
Чтобы разобраться все-таки нужен тест-кейс, на котором бы я смог воспроизвести.
