### ISSUE TITLE
проблема с css

### ISSUE THREAD

**Issue by rush777** [bem/bem-forum-content-ru#541]
Добры день. У меня проблема с подключением css блока. В styl файле прописываю стили, но на выходе в _index.css получается следущее:

/* ../../libs/bem-components/common.blocks/popup/popup.styl:begin */
.popup {
  position: absolute;
}
/* ../../libs/bem-components/common.blocks/popup/popup.styl:end */
/* ../../common.blocks/popup/popup.styl:begin */
.popup {
  position: absolute;
}

Правила не меняются. Никак. Можно разве что удалить блок.... bem make -m clean делал, .enb/tmp/ удалял. В чем может быть проблема? Подскажите пожалуйста

**Comment by blond** [comment]
Это ошибка кэширования в `stylus` — https://github.com/stylus/stylus/issues/1951. Ошибка была решена в `stylus@0.52.0`.

**Comment by blond** [comment]
Если речь о сборке с помощью ENB, то обновление до `stylus@0.52.0` будет в `enb-stylus@2.0.0`.

Пока не вышла стабильная версия можно воспользоваться `enb-stylus@2.0.0-rc`.

**Comment by rush777** [comment]
Заработало, спасибо)
