### ISSUE TITLE
jsdoc якоря на сайте

### ISSUE THREAD

**Issue by Guria** [bem/bem-forum-content-ru#563]
При переходе по ссылке без указания языка не происходит пролистывание страницы до положения якоря. Например:
https://bem.info/libs/bem-core/v2.7.0/desktop/i-bem/jsdoc/#jsdoc-init-1

**Comment by blond** [comment]
У меня сработало правильно =) Может в браузере дело?

**Comment by Guria** [comment]
Похоже. В инкогнито сработало нормально.
