### ISSUE TITLE
Проблемы с шаблоном

### ISSUE THREAD

**Issue by c1n1k** [bem/bem-forum-content-ru#605]
есть bemjson:
{
                            block : 'magazine',
                            content : {
                                elem : 'list',
                                content : [
                                    { 
                                        name : 'Знамя Зенита #4', 
                                        count : '10', 
                                        imgUrl : 'img/zz4.jpg', 
                                        date : 'Октябрь, 1995', 
                                        redaction : 'ЗЗ' 
                                    },
                                    { 
                                        name : ' Name 2', 
                                        count : '11', 
                                        imgUrl : 'img/zz3.jpg', 
                                        date : 'Сентябрь, 1995', 
                                        redaction : 'ЗЗ' 
                                    }
}

есть bemhtml:
block('magazine')(
    
    elem('list')(
        tag()('ul'),
        content()(function() {
            // var data = this.ctx.content;

            return this.ctx.content.map(function(item) {
                return {
                    elem : 'list-item',
                    content : [
                        {
                            elem : 'img',
                            content : {
                                block : 'image',
                                url : item.imgUrl
                            }
                        },
                        {
                            elem : 'meta',
                            content : [
                                {
                                    elem : 'meta-title',
                                    content : item.name
                                },
                                {
                                    tag : 'div',
                                    content : [
                                        {
                                            elem : 'meta-item',
                                            content : item.date
                                        },
                                        {
                                            elem : 'meta-item',
                                            content : item.redaction
                                        },
                                        {
                                            elem : 'meta-link',
                                            content : 'Перейти'
                                        }
                                    ]
                                },
                                {
                                    elem : 'meta-count',
                                    content : 'Статей: ' + item.count
                                }
                            ]
                        }
                    ]
                };
            });
        })
    ),
…

Все преобразуется в html, стили из 
из папок __img, __meta не цепляются. Что делаю не так?

**Comment by apsavin** [comment]
Может быть, вы забыли прописать зависимости от этих элементов в deps-файле?

**Comment by c1n1k** [comment]
я не забыл… я их вообще не прописал:) ладно попробую прописать, а вот только почему если в bemjson прописываю элементы блока то все ок?

**Comment by tadatuta** [comment]
@c1n1k Сборщик умеет автоматически строить зависимости по BEMJSON, т.к. после исполнения это просто JS-объект, а вот достроить их по шаблонам в общем случае очень сложно, т.к. там может быть произвольная логика на JS с конкатенацией строк, ветвлением и т.п.
