### ISSUE TITLE
Form label в bem-components

### ISSUE THREAD

**Issue by just-boris** [bem/bem-forum-content-ru#652]
У меня есть вот такой контрол
![image](https://cloud.githubusercontent.com/assets/812240/10602051/c3c739dc-771e-11e5-9fc9-2d78968c92c8.png)
Блок select я нашел, а вот label – нет. Какой рекомендованный способ создавать такие контролы? Как согласовать размер соседних блоков, чтобы оба получали 'S', 'M', 'L', ...

Я пользуюсь библиотекой в dist-сборке

**Comment by tadatuta** [comment]
Привет!

> Блок select я нашел, а вот label – нет. Какой рекомендованный способ создавать такие контролы?

На данный момент готового решения для лейблов нет :(

> Как согласовать размер соседних блоков, чтобы оба получали 'S', 'M', 'L', ...

Необходимо каждому контролу указать соответствующий модификатор. Если ты используешь `dist`, то либо вручную, либо эта задача ложится на используемый шаблонизатор.

**Comment by just-boris** [comment]
Ясно, спасибо за ответ.
Тогда я создам свой блок label, а также оберну его в блок form-control, который будет проставлять size дочерним блокам, чтобы он у них был одинаковый.
Так правильно?

**Comment by just-boris** [comment]
Также нашел https://github.com/bem-incubator/bem-forms, может это чем-то поможет мне

**Comment by tadatuta** [comment]
> Тогда я создам свой блок label, а также оберну его в блок form-control, который будет проставлять size дочерним блокам, чтобы он у них был одинаковый.
Так правильно?

Да, именно так и [предполагалось](https://github.com/bem/bem-components/issues/538#issuecomment-44641736).

> Также нашел bem-forms, может это чем-то поможет мне

Лейбл в `bem-forms` есть, но эта библиотека развивается силами комьюнити и пока не предоставляет `dist`-версию.
