### ISSUE TITLE
Установить стандартную тему

### ISSUE THREAD

**Issue by just-boris** [bem/bem-forum-content-ru#658]
Каждый блок имеет модификатор theme. И во всех примерах он пишется непосредственно к блоку
```js
{
  block: 'button',
  mods: {type: 'submit', theme: 'islands', size: 'l'},
  text: 'Search'
}
```

Хочу чтобы все контролы в проекте получили тему islands по умолчанию. Как это сделать?

**Comment by tadatuta** [comment]
При использовании шаблонов можно сделать что-то вроде
```js
block('*').def()(function() {
    this.mods.theme || (this.mods.theme = 'islands');
    return applyNext();
});
```

**Comment by just-boris** [comment]
Я все еще пользуюсь dist-сборкой. Куда мне это написать?

**Comment by just-boris** [comment]
Например, что нужно добавить в этот fiddle: http://jsfiddle.net/z1cLLt4w/9/

**Comment by vithar** [comment]
Например, можно в postcss оторвать тему совсем и не задавать её в HTML.

**Comment by just-boris** [comment]
@vithar а что делать если css грузится с yastatic, как в fiddle?

**Comment by tadatuta** [comment]
твой шаблонизатор не может проставлять дополнительные классы?

**Comment by just-boris** [comment]
@tadatuta я пользуюсь Handlebars. Куда и как он должен проставлять дополнительные классы?

Еще у меня есть хелпер `renderBem`
```
function renderBem(el, bemjson) {
    modules.require(['i-bem__dom', 'BEMHTML'], function(BEMDOM, BEMHTML) {
    	BEMDOM.append(el, BEMHTML.apply(bemjson));
	});
}
```

Могу в него добавить принудительное выставление theme для bemjson: http://jsfiddle.net/z1cLLt4w/12/

Но я не уверен, что так делать правильно

**Comment by tadatuta** [comment]
Твой вариант с `renderBem` вполне годный.

**Comment by just-boris** [comment]
@tadatuta на самом деле нет, потому что он не работает, если у блока в `content` будут другие блоки.

Может есть способ зарегистрировать общий шаблон из [этого коммента](https://github.com/bem/bem-forum-content-ru/issues/658#issuecomment-150162486)

**Comment by tadatuta** [comment]
Для диста такая возможность появится после https://github.com/bem/bem-components/issues/1691 (задачу планирую сделать на этой неделе, версию выпустим в обозримом будущем).

**Comment by just-boris** [comment]
@tadatuta добрый день!

Issue по ссылке уже закрыта, в этой задаче что-нибудь поменялось?

**Comment by tadatuta** [comment]
@just-boris Ага, прости, что сразу не отписался :(

http://jsfiddle.net/tadatuta/cgx2dz84/1/

**Comment by just-boris** [comment]
@tadatuta спасибо!

Я правильно понимаю что match всех блоков по `*` работает только в bemhtml?

А в bh это возможно?

**Comment by tadatuta** [comment]
Кажется, https://github.com/bem/bh/blob/master/lib/bh.js#L687-L698 должно помочь.

**Comment by just-boris** [comment]
Помогло. Последний вопрос: правильно ли я делаю, чтобы модификатор ставился только для блока, без элементов?

```
bh.beforeEach(function(ctx, json) {
    if(json.block && !json.elem) {
        if(!json.mods.size) {
            ctx.mod('size', 'm');
        }
        ctx.mod('theme', 'islands');
    }
});
```

**Comment by tadatuta** [comment]
да, в `bem-components` тема указывается только блокам

**Comment by just-boris** [comment]
Вопрос решен. Спасибо за советы!
