### ISSUE TITLE
Как не тестировать лишний html

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#660]
Есть огромный блок в котором куча разных вложненных блоков разного размера. В `tmpl-spec` хочется проверить что у блока есть нужные вложенные, при этом хочется чтобы `html-differ` **не проверял содержмое** эти вложенных блоков. Знаю, что у `html-differ` есть регулярки, но почему-то не получается с ними подружитсья: что не пишу, все равно красная простыня в diff.

**Comment by tadatuta** [comment]
Ты ведь для тестов сам пишешь исходный BEMJSON, его нельзя написать так, чтобы внутренние блоки оказались пустыми?

**Comment by kompolom** [comment]
@tadatuta нет, к сожалению так не получится.

**Comment by kompolom** [comment]
@tadatuta пробую [тут](https://regex101.com/) регулярку - работает. В html-differ - не работает. Может там какие-то особенности?

**Comment by tadatuta** [comment]
cc @eGavr

**Comment by eGavr** [comment]
@kompolom 

Давай на реальных примерах, дай HTML эталонный и сгенерированный и укажи, какую часть должна захватить регулярка.

**Comment by eGavr** [comment]
@kompolom Заведи лучше issue в html-differ и там все обсудим.

**Comment by kompolom** [comment]
@eGavr [вот пример](https://gist.github.com/kompolom/19e70ff1c336463a1a71)

**Comment by kompolom** [comment]
завел  issue https://github.com/bem/html-differ/issues/134
