### ISSUE TITLE
Элемент googlefont блока page для подключения гуглошрифтов на страницу

### ISSUE THREAD

**Issue by vitkarpov** [bem/bem-forum-content-ru#665]
Сделал на проектном уровне переопределения специальный элемент `googlefont` блока `page` для [асинхронного подключения гуглошрифтов](https://www.google.com/fonts#QuickUsePlace:quickUse)

В `bemjson`:

```
    block : 'page',
    head : [
        ...
        { elem : 'css', url : 'index.min.css' },
        { elem : 'googlefont', families: 'PT+Serif:400,700:latin,cyrillic' }
    ]
```

В результате наложения шаблона для такого элемента в разметке, в секции `head`, появится:

```js
<script type="text/javascript">
  WebFontConfig = {
    google: { families: [ 'PT+Serif:400,700:latin,cyrillic' ] }
  };
  (function() {
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
      '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
  })();
</script>
```

Кто как подключает шрифты? Может нужен такой элемент в стандартной библиотеке?

**Comment by JiLiZART** [comment]
На самом деле будет круто если вот такой способ http://habrahabr.ru/company/paysto/blog/268771/ появится для загрузки любых шрифтов, не только с google fonts

**Comment by tadatuta** [comment]
Соглашусь с @JiLiZART с тем, что хочется более общего решения. При этом подключение с google через `families` может быть просто модификатором универсального блока `font`.
И через опции можно поддержать всякую магию про прелоад, куки и локалсторадж.
Такой блок вполне тянет на отдельную полезную библиотеку.

**Comment by vitkarpov** [comment]
Ага, понятно. Спасибо!
