### ISSUE TITLE
как тестировать промисы

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#678]
Подскажите, как в `spec.js` тестировать промисы. Нужно что то дополнительно ставить? Есть пакет `should-promised` но он же в сборку все равно не попадет...

**Comment by apsavin** [comment]
Это же мока, она умеет из коробки с промисами работать.

Или что значит "тестировать промисы"?

**Comment by kompolom** [comment]
@apsavin Да. Похоже что то в [доке](http://shouldjs.github.io/#assertion-promise) не то написали. 

````
(new Promise(function(resolve, reject) { resolve(10); })).should.be.a.Promise(); 
````

говорит `TypeError: promise.should.be.a.Promise is not a function` 
В общем, заработало так:

````
(new Promise(function(resolve, reject) { resolve(10); })).should.be.a.Promise; 
````

**Comment by apsavin** [comment]
Вообще, spec.js использует не should.js, а chai. [пруф](https://github.com/narqo/bem-pr/tree/master/spec.blocks)

**Comment by kompolom** [comment]
@apsavin Так то да...
тут https://ru.bem.info/tools/bem/enb-bem-specs/readme/ написано что should.js ну я и поверил наслово...

**Comment by apsavin** [comment]
Заведи им ишью или поправь и сделай ПР) А то вводят в заблуждение...

**Comment by kompolom** [comment]
Похоже из коробки все же не работает... 

Беру пример из http://mochajs.org/
````
return promise.should.eventually.have.length(3);
````
отвечает:
````
TypeError: Cannot read property 'be' of undefined
````

**Comment by apsavin** [comment]
Там же написано - (The latter example uses Chai as Promised for fluent promise assertions.)

**Comment by apsavin** [comment]
мока из коробки позволяет из `it` возвращать промисы. Вот я о чем говорил.

**Comment by kompolom** [comment]
@apsavin возможно я дико туплю, но таки нужно дополнительно пакет ставить? (изначально этот вопрос я и задавал).

**Comment by apsavin** [comment]
Если нужен функционал вот [такой](https://github.com/domenic/chai-as-promised/) - поставьте этот пакет.

**Comment by kompolom** [comment]
@apsavin Спасибо. 
Теперь самое интересное. То, что я его поставил - не означает, что все заработает. В сборку то он не попадет. Как быть дальше?

**Comment by apsavin** [comment]
Сделать [так же](https://github.com/narqo/bem-pr/blob/master/spec.blocks/chai/chai.js), как в bem-pr подключается chai

**Comment by kompolom** [comment]
@apsavin Спасибо! Оказалось проще чем я думал!
