### ISSUE TITLE
Удаление подписки на БЭМ события

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#695]
> Удаление подписки на БЭМ-события выполняется автоматически при уничтожении экземпляра блока. 

````javascript
this.findBlockInside('button').on('click', this.save, this);
````

При том что блок `button` может быть удален из DOM, затем снова вставлен, и несколько раз. Будет ли автоматически удалены подписки на БЭМ события? Иными словами, при уничтожении какого блока подписки будут удалены автоматически, того который подписался, или того на события которого сделана подписка?

**Comment by tadatuta** [comment]
Будут удалены события блока `button`.
И в данном случае он сам подписывается на свои события. Код выше можно представить следущим образом:
```js
var button = this.findBlockInside('button');

button.on('click', this.save, this); // подписка вызывается у блока button, а не у родителя.
```

Вот как это происходит:
1. Удаление блоков вызывается методами [destruct](https://ru.bem.info/libs/bem-core/v2.8.0/desktop/i-bem/jsdoc/#jsdoc-destruct-1), `update` или `replace`. При этом последние внутри себя [вызывают](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L1058) все тот же `destruct`.
2. destruct [вызывает](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L915) метод `un` без аргументов.
3. `un` [наследуется](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.vanilla.js#L145) i-bem-блоками от `Emitter` из модуля [events](https://github.com/bem/bem-core/blob/v2/common.blocks/events/events.vanilla.js). Его реализация при вызове без аргументов [удаляет весь объект с событиями](https://github.com/bem/bem-core/blob/v2/common.blocks/events/events.vanilla.js#L198-L200) для данного блока. Кроме того, `i-bem__dom` доопределяет `un` дополнительным умением прибивать специальные подписки на `window` и `document`.

**Comment by kompolom** [comment]
@tadatuta

>  button.on('click', this.save, this); // подписка вызывается у блока button, а не у родителя. 

Хочу уточнить. Поправь если не так. Блок `button` сам подписывается на свои события и обрабатывает их в контексте родителя, по-сути вызывая его методы. То есть, при удалении button.domElem все ок - нет лишних подписок.

**Comment by tadatuta** [comment]
Все так. Но важно, чтобы удаление происходило с помощью методов `BEMDOM`, а не `button.domElem.remove()`.

**Comment by kompolom** [comment]
Спасибо!
