### ISSUE TITLE
enb-bem-specs: не нужная сборка тестов со всех уровней

### ISSUE THREAD

**Issue by voischev** [bem/bem-forum-content-ru#700]
Привет. Как запускать тесты только со своего уровня библиотеки? 

Получается так что для наших тестов нужны шаблоны и js из bem-core, bem-comprnents. Соответственно эти уровни есть в конфиге для тестов. Сейчас как минимум в консоль валятся репорты со всех уровней. 

Второй вопрос.
Сейчас некоторые тесты валятся, но эти тесты валятся если мы запускаем `enb make specs` со своего уровня библиотеки. если запускать внутри либ то все проходят нормально. Вопрос — как дебажить такое поведение?

**Comment by tadatuta** [comment]
`levels` и `sourceLevels` (https://github.com/bem/bem-components/blob/v2/.enb/make.js#L330-L331) не решают эту задачу?

**Comment by voischev** [comment]
Да! Спасибо.
