### ISSUE TITLE
Сборка спрайтов Борщиком

### ISSUE THREAD

**Issue by vitkarpov** [bem/bem-forum-content-ru#722]
Привет!

Некоторое время назад [обсуждалась](https://ru.bem.info/forum/-278/) возможность научить борщик склеивать картинки в спрайты. В итоге, сейчас это есть?

**Comment by tadatuta** [comment]
Вроде нет. Похоже, что всем хватило возможности инлайнить картинки.

**Comment by vitkarpov** [comment]
Ага, видимо, этого достаточно. Спасибо.
