### ISSUE TITLE
Помогите с deps.js

### ISSUE THREAD

**Issue by nejtr0n** [bem/bem-forum-content-ru#749]
Здравствуйте. Есть проблема, не получается решить (
Корневой блок `page` имеет модификатор `theme`.
В файле `theme.styl` указана переменная `borderColor1 = #A9A9A9`
Дальше по коду есть блок `search`, у которого цвет бордера берётся 
из этой переменной. Но он не применяется
```
.search__header
  & .control-group
    background-color borderColor1
```
В файле `deps.js` блока `search` прописан блок `page`
```js
({
    mustDeps: {
        block: 'page',
    }
})
```
Где то туплю, но не пойму где (
Помогите пожалуйста!

**Comment by tadatuta** [comment]
Если речь идет о том, что в сборку должен попасть именно модификатор `theme` блока `page`, то необходимо, чтобы:
1. На файловой системе он назывался строго `page/_theme/page_theme.styl`.
2. В зависимостях блока `search` был прописан именно модификатор:
```js
({
    mustDeps: {
        block: 'page',
        mods: { theme: true }
    }
})
```

**Comment by nejtr0n** [comment]
Всё равно не подтягивает ...
Вот проект на гитхаб (там всего 3 блока пока)
https://github.com/nejtr0n/bem-test

**Comment by tadatuta** [comment]
Причина в том, что сейчас зависимость от `page` прописана для `search`, а на самом деле она требуется для `search__header`. В результате код `search__header` импортируется ниже, чем объявляется переменная.

Чтобы исправить, достаточно добавить файл `common.blocks/search/__header/search__header.deps.js` с таким содержанием:
```js
({
    mustDeps: {
        block: 'page',
        mods: { theme: true }
    }
})
```

**Comment by nejtr0n** [comment]
Огромное спасибо! Разобрался!
