### ISSUE TITLE
Не могу применить шаблон bemhtml :(

### ISSUE THREAD

**Issue by karalkou** [bem/bem-forum-content-ru#750]
Помогите, пожалуйста. Я новичок в вёрстке. В компании, в которую удалось устроиться, велась разработка портала на БЭМ.
Предыдущий разработчик переехал в другой город. В итоге, тяжеловато связываться с ним.
Сверстал страницу, но не получается завершить задачу.

На странице есть псевдо-селект с несколькими псевдо-элементами ( на них примиксованы блоки .certificate-change ).
certificate-change.js
http://pastebin.com/U10aafcD

certificate-change.deps.js
http://pastebin.com/nkMy9uRh

Каждому псевдоэлементу c .certificate-change соответствует блок .tiles-certificate со своим содержимым.
Содержимое хранится в data-bem .certificate-change под именем newBemJSON, для которого есть bemhtml шаблон.

объект newBemJSON
http://pastebin.com/Mnn72NNR

tiles-certificate.bemhtml
http://pastebin.com/LkAuJxja

Родителем .tiles-certificate является блок .tiles-control, который и управляет заменой блока .tiles-certificate.
Он слушает клик на .certificate-change, вытаскивает из него newBemJSON, прогоняет через шаблонизатор и аппендит в себя.
tiles-control.js
http://pastebin.com/beNxWMUw

tiles-control.deps.js
http://pastebin.com/BSZ0U5Qr

Проблема в том, что не срабатывает шаблонизатор. Т.е. на страницу просто вставляется div с классом .tiles-certificate.

**Comment by zxqfox** [comment]
Кажется, что tiles-certificate.bemhtml должен быть .bemhtml.js

**Comment by tadatuta** [comment]
Предположу, что проблема кроется в http://pastebin.com/BSZ0U5Qr — дважды встречается секция mustDeps, вторая перетирает первую и в результате в сборку не попадает блок `i-bem` с базовыми шаблонами.

**Comment by zxqfox** [comment]
Там, кстати, `tech: 'bemhtml'` — вроде бы, не нужно это.

**Comment by tadatuta** [comment]
@zxqfox
> Там, кстати, `tech: 'bemhtml'` — вроде бы, не нужно это.

Почему, речь ведь о шаблонизации на клиенте?

**Comment by zxqfox** [comment]
> > Там, кстати, tech: 'bemhtml' — вроде бы, не нужно это.

> Почему, речь ведь о шаблонизации на клиенте?

Потому что депсы так не умеют. Поищу пруф...

Кстати, вот интересная штука: https://github.com/bem/bem-components/blob/v2/common.blocks/menu-item/_type/menu-item_type_link.deps.js#L7

Кажется, это от того, что depsByTech не самая понятная штука.

**Comment by zxqfox** [comment]
@tadatuta 
https://github.com/enb-bem/enb-bem-techs/blob/master/techs/deps-by-tech-to-bemdecl.js#L108 вот тут есть условие про destTech
Видимо, информация устарела и уже все ок. Спасибо за наводку ;-)

**Comment by tadatuta** [comment]
@zxqfox [вот](https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L64-L89) же

**Comment by zxqfox** [comment]
@tadatuta Есть инфа, что раньше tech внутри не нужен был, а сейчас, если убрать `destTech: 'bemhtml'`, то подгрузятся все технологии по depsByTech.

**Comment by tadatuta** [comment]
Похоже, я ничего не знаю про это раньше.

**Comment by karalkou** [comment]
@tadatuta
изменил структуру таким образом http://pastebin.com/UDHEMLTy. Но всё-равно не собирается. Может быть есть ещё идеи?

**Comment by tadatuta** [comment]
Все остальное выглядит правильно. Если есть возможность запушить на github пример, на котором воспроизводится проблема — помогу.

**Comment by karalkou** [comment]
@tadatuta
Залил. Вот ссылка на репозиторий https://github.com/karalkou/some-project

**Comment by karalkou** [comment]
@tadatuta
Залил. Вот ссылка на репозиторий https://github.com/karalkou/some-project
Привязано на клик по "Объединенная авиастроительная коропорация".
gulp перекладывает в pages/

**Comment by tadatuta** [comment]
@karalkou не хватало mustDeps-зависимости от `i-bem` в `desktop.blocks/tiles-certificate/tiles-certificate.deps.js`, но я пока разбирался, поправил несколько других моментов, сейчас пришлю PR с комментариями.

**Comment by karalkou** [comment]
@tadatuta спасибо

**Comment by tadatuta** [comment]
@karalkou https://github.com/karalkou/some-project/pull/1
