### ISSUE TITLE
Повторная инициализация блока.

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#759]
Возможно ли 

 1. Повторно запустить инициализацию блока.
 2. Заменить блок `BEMDOM.replace()` сохранив существующие связи блока (подписки на события).

**Comment by tadatuta** [comment]
см.
https://github.com/bem/bem-forum-content-ru/issues/641
https://github.com/bem/bem-core/issues/1222

**Comment by kompolom** [comment]
@tadatuta Если резюмировать по первому пункту - то такого нет?

**Comment by kompolom** [comment]
Может я не там решение ищу. Задача следующая: 
Модифицирую блок `select` из bem-components. Нужно получить селект меню которого будет изменяться в рантайме.
По факту сделал замену меню через

````javascript
BEMDOM.replace(
  select._menu.domElem,
  BEMHTML.apply({block: 'select', 'elem' : 'menu'})
)
````

**Comment by kompolom** [comment]
На память:  У `menu` есть метод `setContent()`

**Comment by voischev** [comment]
@kompolom красавчик ;) курил сорцы?)
