### ISSUE TITLE
откуда отступ в popup

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#767]
Заметил что в `popup_target_anchor` `directions: [bottom-left]` присутствует отступ от `anchor` даже если задать `mainOffset :  0 ` в css никаких отступов не задано. Получается отступ появляется при расчете позиции попапа. В чем может быть причина?

**Comment by tadatuta** [comment]
Это свойство темы `islands`: https://github.com/bem/bem-components/blob/v2/design/common.blocks/popup/_theme/popup_theme_islands.js#L8

Можно аналогично сбросить в 0 на уровне проекта.
