### ISSUE TITLE
Атрибут required для input

### ISSUE THREAD

**Issue by vitkarpov** [bem/bem-forum-content-ru#775]
Есть потребность добавлять required для input (с точки зрения реализации атрибут должен быть у input__control). Может имеет смысл добавить соответствующее специализированное поле блока для input?

**Comment by tadatuta** [comment]
Обсуждали, договорились, что пока расширять API возможностями, которые не поддерживаются во всех браузерах из списка совместимости следует на стороне пользователей, которые будут сами за это отвечать.

**Comment by vitkarpov** [comment]
Понял, спасибо!

**Comment by DjonyBastone** [comment]
Добрый день!
Пробовал добавить  `required` для `input` в `input__control.bemhtml.js` - не получилось

Вариант 1:

```
block('input').elem('control')(
    tag()('input'),

    attrs()(function() {
        var input = this._input,
            attrs = {
                id : input.id,
                name : input.name,
                value : input.val,
                maxlength : input.maxLength,
                tabindex : input.tabIndex,
                placeholder : input.placeholder,
                required : input.required
            };

        input.autocomplete === false && (attrs.autocomplete = 'off');
        this.mods.disabled && (attrs.disabled = 'disabled');

        return attrs;
    })
);

Вариант 2:

```
block('input').elem('control')(
    tag()('input'),

    attrs()(function() {
        var input = this._input,
            attrs = {
                id : input.id,
                name : input.name,
                value : input.val,
                maxlength : input.maxLength,
                tabindex : input.tabIndex,
                placeholder : input.placeholder
            };

        input.required === true && (attrs.required = true);
        input.autocomplete === false && (attrs.autocomplete = 'off');
        this.mods.disabled && (attrs.disabled = 'disabled');

        return attrs;
    })
);
```

Пожалуйста направьте в нужном направлении. Что сделать то надо, для того чтобы появился required?

**Comment by DjonyBastone** [comment]
Временно решил добавлением модификатора:
`input_required.bemhtml.js`:

```
block('input').mod('required').elem('control').attrs()(function() {
    return this.extend(applyNext(), { required : true });
});
```

Как то не очень нравится, добавляется лишний класс - input_required. Подскажите, как будет более правильно?

**Comment by tadatuta** [comment]
Без модификатора можно так (важно положить код в `input/__control/input__control.bemhtml.js`, чтобы сохранился порядок):
```js
block('input')(
    def()(function() {
        this._required = this.ctx.required; // прокидываем значение поля потомкам
        return applyNext();
    }),
    elem('control').attrs()(function() {
        return this.extend(applyNext(), { required: this._required });
    })
);
```

**Comment by DjonyBastone** [comment]
@tadatuta спасибо большое.

Вопрос: а если атрибут имеет тире, то его шаблонизатор `bemhtml` не сможет скушать? 

К примеру `aria-invalid` в `bemhtml` выдает ошибку, и даже если я его указываю как - строку или объект

**Comment by tadatuta** [comment]
должно работать: https://goo.gl/jghrHm

**Comment by DjonyBastone** [comment]
Только вот, атрибут нужен для элемента, который находится в блоке с модификатором.

[http://bem.github.io/bem-xjst/?template=block(%27input%27)(%0A%20%20%20%20mod(%7B%27type%27%3A%20%27tel%27%7D)(%0A%20%20%20%20%20%20%20%20elem(%27control%27)(%0A%20%20%20%20%20%20%20%20%20%20%20%20attrs()(%7B%27aria-invalid%27%3A%20%27false%27%7D)%0A%20%20%20%20%20%20%20%20)%0A%20%20%20%20)%0A)%3B%0A%0A&bemjson=(%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20block%3A%20%27input%27%2C%0A%20%20%20%20%20%20%20%20mods%3A%20%7Btype%3A%20%27tel%27%7D%2C%0A%20%20%20%20%20%20%20%20content%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20elem%3A%20%27control%27%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20block%3A%20%27input%27%2C%0A%20%20%20%20%20%20%20%20mods%3A%20%7Btype%3A%20%27text%27%7D%2C%0A%20%20%20%20%20%20%20%20content%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20elem%3A%20%27control%27%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%5D)](url)

А как в прошлом примере прокинуть `.extend` не получается. 
Рыл документацию - Синтаксис шаблона, не нашел подобного примера

**Comment by tadatuta** [comment]
```js
block('input').mod('type', 'tel')(
    elem('control')(
        attrs()({'aria-invalid': 'false'})
    )
);
```

**Comment by DjonyBastone** [comment]
@tadatuta спасибо

по этой схеме это тоже пробовал, но видимо где то была синтаксическая ошибка.
Главное, что вопрос закрылся со всеми атрибутами aria, теперь можно любой назначить.
