### ISSUE TITLE
Есть ли возможность переопределять способ открытия блока popup

### ISSUE THREAD

**Issue by Sergei-b84** [bem/bem-forum-content-ru#798]
Всем привет! Есть ли возможность переопределять эффект открытия блока popup. Хочу сделать так, чтобы он не выезжал снизу вверх, а раскрывался из центра как здесь http://codepen.io/pen?  Какой файл править?

**Comment by tadatuta** [comment]
https://github.com/bem/bem-components/blob/v2/design/common.blocks/popup/_theme/popup_theme_islands.styl#L29
