### ISSUE TITLE
Почему сократился bower.json в новой версии project-stub?

### ISSUE THREAD

**Issue by Sergei-b84** [bem/bem-forum-content-ru#800]
Всем привет! В своем проекте использую заготовку project-stub (ветка i18n)/ Подскажите, почему в ветке i18n bower.json такой https://github.com/bem/project-stub/blob/i18n/bower.json , а в версии project-stub 1.4.0 такой https://github.com/bem/project-stub/blob/bem-core/bower.json . Будет ли ошибкой? если я обновлю bem-components с 2.3.0 до 2.4.0 и оставлю bower.json как в project-stub?

**Comment by apsavin** [comment]
Рекомендую разобраться, как работает bower.

bem-components зависит от определенной версии bem-core. Если не указывать в bower.json зависимость от bem-core, то bem-core будет установлена той версии, которую хотят bem-components.

**Comment by tadatuta** [comment]
Причина расхождений простая — я не успеваю поддерживать все ветки в актуальном состоянии.

В плане свежести стоит ориентироваться на ветку `bem-core`, т.е. можно смело обновляться до https://github.com/bem/project-stub/blob/bem-core/bower.json

А еще я принимаю пулл-реквесты ;)

**Comment by blond** [comment]
@tadatuta удали уже все ветки и оставь только `master` ;)

**Comment by Sergei-b84** [comment]
>Если не указывать в bower.json зависимость от bem-core, то bem-core будет установлена той версии, которую хотят bem-components.

Спасибо, @apsavin. Так и предполагал. Просто решил переспросить.

>А еще я принимаю пулл-реквесты ;)
 Спасибо, @tadatuta. Буду иметь ввиду.

**Comment by tadatuta** [comment]
@blond Ты уверен, что совсем без ветки `i18n` лучше, чем с чуть отстающей веткой `i18n`? ;)

**Comment by JiLiZART** [comment]
@tadatuta в разных ветках много интересных и нужных примеров, которые возможно было бы лучше объединить в ветке 'master', нежели поддерживать все ветки, например в папке examples?

**Comment by blond** [comment]
> @blond Ты уверен, что совсем без ветки i18n лучше, чем с чуть отстающей веткой i18n? ;)

Я то как раз уверен, что если понимать как собирается `project-stub`, то и довкрутить `i18n` не составит. Но тут я нерепрезентативен :)
