### ISSUE TITLE
Блок dropdown внутри control-group

### ISSUE THREAD

**Issue by Sergei-b84** [bem/bem-forum-content-ru#802]
Всем привет! Вчера я объединил между собой две ветки, ветку i18n и ветку suggest, так как нужны обе. Все блоки отображаются корректно, все работает, кроме одного. У меня возникла проблема с блоком dropdown (switcher : 'button',) вложенного в блок control-group, а именно, почему-то не прилетает свойство last-child. Если заменяю dropdown на обычную кнопку, все ок. Вот скрины:
http://i.imgur.com/DAMqGDb.png
http://i.imgur.com/4r0bQ5g.png

**Comment by tadatuta** [comment]
Проблема связана с тем, что кнопка в случае с `dropdown` не является last-child, пока `popup` не переместится перед закрывающим `</body> при первом появлении.

Заведу баг в bem-components, а пока предложу закостылять на уровне проекта.

**Comment by Sergei-b84** [comment]
Спасибо. Буду ждать. а вообще, для информации, как быстро решаются проблемы подобного рода? От версии к версии?

**Comment by tadatuta** [comment]
По-хорошему — да. Но на свой страх и риск можно обновляться до коммита, в котором исправлена проблема.

**Comment by tadatuta** [comment]
https://github.com/bem/bem-components/issues/1741
