### ISSUE TITLE
Как подключить все значения модификатора в deps.js

### ISSUE THREAD

**Issue by adinvadim** [bem/bem-forum-content-ru#803]
Допутим у кнопки есть модификатор `type` со значениями `primary` `clear`
Что написать в .deps.js, чтобы подключить блок со всеми значениями модификатора `type`, просто перечислить?

**Comment by tadatuta** [comment]
```js
({
    shouldDeps: { mods: { type: ['primary', 'clear'] } }
})
```

**Comment by adinvadim** [comment]
О, можно масив значений передавать, супер спасибо!
