### ISSUE TITLE
БЭМ и  CSS спрайты

### ISSUE THREAD

**Issue by Sergei-b84** [bem/bem-forum-content-ru#805]
Ребята, подскажите есть ли какие-то готовые инструменты  для динамического создания CSS спрайтов (CSS sprites) внутри вашей технологии? Что лучше взять 
https://www.npmjs.com/package/node-sprite
https://npmjs.org/package/spritesmith
https://npmjs.org/package/stylus-sprite 
?

**Comment by tadatuta** [comment]
В сборке спрайтов нет никакой БЭМ-специфики. Можно использовать любое решение.
