### ISSUE TITLE
Шаблон для элемента в зависимости от модификатора блока

### ISSUE THREAD

**Issue by adinvadim** [bem/bem-forum-content-ru#808]
Есть блок `block` с модификатором `type` у которога два значения `val1` `val2`
Как лучше написать шаблон элемента блока `block__info`, чтобы в зависимости от модификатора блока, он выводил разный контент

Как я понял такие конструкции работать не будут

```
block('block`)(
    elem('info')(
        mod('type', 'val1')( ... ),
        mod('type', 'val1')( ... )
    )
)
```
```
block('block`)(
    mod('type','val1').elem('info')( ... ),
    mod('type','val2').elem('info')( ... ),
)
```

**Comment by tadatuta** [comment]
@adinvadim Оба варианта правильные и должны работать.

**Comment by adinvadim** [comment]
@tadatuta Упс, ошибка была в другом, понял, спасибо!
