### ISSUE TITLE
Как связать элемент формы radio с подписью через идентификатор

### ISSUE THREAD

**Issue by Sergei-b84** [bem/bem-forum-content-ru#814]
Как связать элемент формы radio с подписью через идентификатор.
Пробовал устанавливать id, for в подписи не появился.
    
    <span class="checkbox__text" role="presentation">TEXT</span>

**Comment by tadatuta** [comment]
Нужно более полное описание задачи в виде кода: что на входе и чего хочется в результате.

**Comment by Sergei-b84** [comment]
на входе обычный checkbox

    
    {
        block : 'checkbox',
        mods : { theme : 'horiz', size : 'm' },
         id: 'english_uk',
         text : 'English (UK)'
    }

на выходе хочу чтобы подпись была такой
    
    <span class="checkbox__text"  role="presentation"  for="english_uk" >English (UK)</span>

**Comment by tadatuta** [comment]
Не очень понимаю, зачем это нужно, ведь а) клик по подписи и так переключает чекбокс, т.к. родительский элемент всего чекбокса представлен тегом `label` б) `for` работает только для `label` а подпись рендерится `span`-ом.

Но если это действительно нужно, то:
В `checkbox.bemhtml.js`
```js
block('checkbox')(def()(function() { return applyNext({ _checkboxId: this.ctx.id }); }));
```
и в `__text/checkbox__text.bemhtml.js`
```js
block('checkbox').elem('text').match(function() { return this._checkboxId; }).attrs()(function() {
     return this.extend(applyNext(), { id: this._checkboxId });
});
```
