### ISSUE TITLE
svg и BH

### ISSUE THREAD

**Issue by Defite** [bem/bem-forum-content-ru#821]
Есть такой код:

```js
{
    block: 'donut-pie',
    tag: 'svg',
    attrs: {
        width: '45px',
        height: '45px'
    }
}
```

Все классно отрисовывается, а в консоль кидает: `Uncaught TypeError: domNode.className.match is not a function`.

Если сделать так:

```
{
    block: 'donut-pie',
    content: {
        tag: 'svg',
        attrs: {
            width: '45px',
            height: '45px'
        }
    }
}
```

Так ошибки нет. Почему?

**Comment by tadatuta** [comment]
@Defite в песочнице [не воспроизводится](http://bem.github.io/bh/#?inputBemjson=%7B%0A%20%20%20%20block:%20'donut-pie',%0A%20%20%20%20tag:%20'svg',%0A%20%20%20%20attrs:%20%7B%0A%20%20%20%20%20%20%20%20width:%20'45px',%0A%20%20%20%20%20%20%20%20height:%20'45px'%0A%20%20%20%20%7D%0A%7D&inputMatchers=), видимо, проблема в чем-то другом.

**Comment by Defite** [comment]
Кажется, отловил ошибку. Блоку donut-pie ставлю `js: true`, затем добавляю клиентский js:

```javascript
modules.define('donut-pie',
    ['i-bem__dom', 'jquery'],

    function (provide, BEMDOM, jQuery) {

        provide(BEMDOM.decl(this.name, {

            onSetMod: {
                js: {
                    inited: function () {

                        console.log('init');

                    }
                }
            }
        }));
    }
);

```

И вот после этого ошибка появляется. Если убрать скрипт или закомментить `js: true`, все снова в порядке.

**Comment by tadatuta** [comment]
```js
document.querySelector('body').className.match) // function
document.querySelector('svg').className.match // undefined
```
т.к. для SVG `className` является не строкой, а инстансом [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString).

Так что если нужна JS-функциональность, стоит завернуть SVG в какую-нибудь обертку. Ну либо пропатчить места, где используется `className.match` и подобные (например, на `classList`).

**Comment by Defite** [comment]
А, понял. Я видел как оно используется в bem-components, сделаю так же.

**Comment by Bot8** [comment]
@Defite
А можешь подсказать направит к решению? а то я с тем же самым столкнулся

**Comment by Defite** [comment]
@Bot8 Получилось как-то так:
`{
            block: 'donut-pie',
            content: 
                {
                    tag: 'svg',
                    mix: {
                        block: 'donut-pie',
                        elem: 'svg'
                    },
                    attrs: {
                        xmlns: 'http://www.w3.org/2000/svg',
                        width: '50',
                        height: '50'
                    }
               }
}`

**Comment by Bot8** [comment]
Понял. Но у меня не получится так. У меня svg блок внутри svg контейнера. Если  обернуть дочерний svg блок в div, то он из контейнера вываливается. Пока извратился так
```javascript
 BEMDOM.prototype._extractModVal
....
if (domNode.className instanceof SVGAnimatedString) {
    var className = domNode.className.baseVal;
} else {
    var className = domNode.className;
}
``` 
ошибка Uncaught TypeError: domNode.className.match is not a function.
исчезла появилась еще хуже
TypeError: b is undefined из jQuery

нужно еще думать

**Comment by Bot8** [comment]
```javascript 
TypeError: b is undefined
```
это я натупил
