### ISSUE TITLE
Создание библиотеки блоков

### ISSUE THREAD

**Issue by Oopscurity** [bem/bem-forum-content-ru#835]
Каким образом можно оформить блоки в виде библиотеки, чтобы на уровне проекта их реализацию возможно было частично переопределить?

**Comment by tadatuta** [comment]
Достаточно просто сложить в отдельную папку и подключить ее в сборку по аналогии с другими уровнями переопределения (https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L23-L32)
