### ISSUE TITLE
Для чего в bem-components вместо селектора :hover используется модификатор

### ISSUE THREAD

**Issue by adinvadim** [bem/bem-forum-content-ru#839]
Для чего в bem-components вместо селектора `:hover` используется модификатор `_hovered`?

**Comment by voischev** [comment]
Как минимум это тоже состояние блока. Мы с помощью BEMHTML можем на это состояние написать шаблон, а так же на этот класс можно так же декларативно написать и браузерный JS. "Слушать" изменения этого класса в DOM. С псевдо элементами мы это и многое другое теряем

**Comment by adinvadim** [comment]
Спасибо, понял!

> Мы с помощью BEMHTML можем на это состояние написать шаблон

Я правильно понимаю, чтобы работал шаблон для `_hovered` нужно слушать изменения этого класса и тогда рендерить клиентский шаблон?

**Comment by tadatuta** [comment]
> Я правильно понимаю, чтобы работал шаблон для _hovered нужно слушать изменения этого класса и тогда рендерить клиентский шаблон?

Да.
