### ISSUE TITLE
Доклад "Полный стек технологий БЭМ", нужны ваши отзывы

### ISSUE THREAD

**Issue by alexbaumgertner** [bem/bem-forum-content-ru#858]
На PiterJS рассказал о стеке технологий БЭМ.

Было мало времени на подготовку, но я старался.

Видео: http://bit.ly/bem-full__video
Доклад: http://bit.ly/bem-full

Буду рад вашим вопросам и предложениям!

Пишите: https://github.com/alexbaumgertner/presentation-bem-stack/issues

Спасибо!

**Comment by JiLiZART** [comment]
Человеку вообще не знакомому с BEMTREE, BEMJSON, BEMHTML вообще ничего понятно не будет. По мне небольшое введение в терминологию и структуру в начале очень важно.

По докладу, по мне так тут 3 доклада, но очень сжатых, без деталей.
1. Трехзвездная архитектура БЭМ BEMTREE, BEMHTML BEMJSON
2. БЭМ на клиенте, i-bem.js, создание блоков, определение зависимостей их сборка
3. БЭМ и sailsjs

А в целом, все круто, полный БЭМ в массы, это хорошо :)
