### ISSUE TITLE
Активная radio button в табах

### ISSUE THREAD

**Issue by romamilkovic** [bem/bem-forum-content-ru#873]
Скопировал себе на проект эти табы https://github.com/bem-contrib/hackaton/tree/master/common.blocks/tabs

BEMJSON:
```javascript
{
            block : 'tabs',
            mods : { theme : 'islands', type : 'button', size : 'm' },
            tabs : [
                {
                    title : 'First',
                    content : 'First tab content'
                },
                {
                    title : 'Second',
                    content : 'Second tab content'
                },
                {
                    title : 'Third',
                    content : 'Third tab content',
                    checked : true
                }
            ]
        }
```
В итоге генерируется все верно, есть radio кнопки, есть вкладки с контентом. Вкладка указанная становится активной, а вот radio кнопка нет, что нужно указать или исправить? Спасибо.

**Comment by tadatuta** [comment]
Я взял за основу `project-stub`, скопировал и у меня проблема не воспроизводится — все работает правильно.

**Comment by romamilkovic** [comment]
@tadatuta Тоже сейчас взял project-stub, такая картина:

Ни одна радио кнопка не активна...

![image](https://cloud.githubusercontent.com/assets/10784316/13089663/4a843de0-d524-11e5-9017-b2ca9a19aac3.png)

**Comment by romamilkovic** [comment]
@tadatuta Ни одна радио кнопка не активна... У вас также?
Они становятся активными только после клика.

**Comment by tadatuta** [comment]
@romamilkovic извиняюсь, сначала неправильно понял о чем речь.

закоммитил исправление: https://github.com/bem-contrib/hackaton/commit/37cc97d8ba161ebb2c55b9c45ca510c9f8c69b28

**Comment by DjonyBastone** [comment]
Пожалуйста подскажите, что бы эти табы заработали с последней версией `project-stub`, достаточно переписать клиентский JS ?
Или все внутренности перетряхивать нужно?

**Comment by tadatuta** [comment]
@DjonyBastone переписывания клиентского js должно быть достаточно.

**Comment by tadatuta** [comment]
Я опубликовал примерно такие же примитивные табики из более-менее «свежего» проекта: https://github.com/tadatuta/bem-bricks/blob/master/common.blocks/tabs/tabs.md, предлагаю заиспользовать их.
