### ISSUE TITLE
PhpStorm 9.0.2 сыпет ошибку плагину для bemhtml

### ISSUE THREAD

**Issue by alexanderbondarchuk** [bem/bem-forum-content-ru#896]
Начал делать первый практический проект на БЭМ, используя руководство https://ru.bem.info/tutorials/start-with-project-stub/

Работаю через приложение PhpStorm 9.0.2 
Вот что валится

20:13:53 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:13:54 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:13:57 AbstractMethodError: update failed for AnAction with ID=CopyReference: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:13:59 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:14:02 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:14:04 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:14:20 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:14:21 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:14:26 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:14:28 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:14:31 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:15:11 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:20:53 AbstractMethodError: null
20:20:55 AbstractMethodError: null
20:20:58 AbstractMethodError: null
20:21:03 AbstractMethodError: null
20:21:05 AbstractMethodError: null
20:21:11 AbstractMethodError: null
20:21:13 AbstractMethodError: null
20:21:36 AbstractMethodError: null
20:22:51 AbstractMethodError: null
20:22:52 AbstractMethodError: null
20:23:07 AbstractMethodError: null
20:24:58 AbstractMethodError: null
20:25:04 AbstractMethodError: null
20:25:06 AbstractMethodError: null
20:25:10 AbstractMethodError: null
20:25:12 AbstractMethodError: null
20:25:14 AbstractMethodError: null
20:25:16 AbstractMethodError: null
20:25:21 AbstractMethodError: null
20:25:23 AbstractMethodError: null
20:25:24 AbstractMethodError: null
20:25:29 AbstractMethodError: null
20:25:45 AbstractMethodError: null
20:25:46 AbstractMethodError: null
20:25:50 AbstractMethodError: null
20:25:58 AbstractMethodError: null
20:26:01 AbstractMethodError: null
20:32:25 AbstractMethodError: null
20:32:35 AbstractMethodError: null
20:32:49 AbstractMethodError: null
20:32:51 AbstractMethodError: null
20:32:57 AbstractMethodError: null
20:33:17 AbstractMethodError: null
20:33:25 AbstractMethodError: null
20:34:39 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:34:50 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:34:59 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:35:28 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:35:41 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:36:00 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:36:07 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:36:18 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:37:00 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:37:56 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:38:01 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z
20:38:30 AbstractMethodError: bem.idea.bemhtml.lang.psi.impl.BemHtmlAsgnExprImpl.isValidHost()Z

**Comment by alexanderbondarchuk** [comment]
Это сообщение появляется в Event Log после установки предложенного PhpStorm плагина для bemhtml

**Comment by zxqfox** [comment]
Кажется, что для js-синтаксиса bemhtml плагин не нужен. Нужен ли плагин вообще? /cc @tadatuta

**Comment by tadatuta** [comment]
Плагин действительно стоит закопать.
// cc @afelix

**Comment by alexanderbondarchuk** [comment]
Гуру. Прошу прощения, мне что делать - удалить его?

**Comment by felixthedev** [comment]
Его стоило удалить уже пару лет назад. API у IDE заметно поменялись, а плагин никто не поддерживал.

// afelix

**Comment by alexanderbondarchuk** [comment]
// @felixthedev Так я только сегодня БЭМ начал пробовать в полном стеке, да ещё через PHP Storm. Как мог удалить его раньше? )

**Comment by alexanderbondarchuk** [comment]
На всякий случай

![2016-02-28 21-39-51](https://cloud.githubusercontent.com/assets/1752818/13381105/d7172f40-de63-11e5-80f9-adf200329caa.png)

**Comment by zxqfox** [comment]
Да, стоит удалить, чтобы не путать людей.

Кстати, если у вас PHP, то может вам и не нужен BEMHTML.

**Comment by alexanderbondarchuk** [comment]
@zxqfox Алексей, как раз про PHP и BH.php суть понял лазя по форуму. В одной из веток говорите, что можно не стесняться и задавать конкретные вопросы вам по этой теме). Если предложение актуально, то подписался на вас, буду пытать)

А в целом, конечно на сайте bem.info сделать бы вам в обучалке разделение, с маленьким опросничком и по его итогам направления человека на конкретную статью. Ато я вот получается общую инфу читал, сидел бесился над BEMHTML и уже мысленно думал в дальнейшем его в BEMJSON пихать полностью, в случаях когда шаблонизация не нужна. А оно вон что оказывается - BH.php ))))) 

А по поводу опросничка - можно было бы что-то вроде "оцените свои знания технологий", перечислить ASP.NET, PHP, Node.js и т.д., а на основании проставленных галочек дать ссылки на статьи. Много времени начинающим БЭМщикам сэкономите)

**Comment by zxqfox** [comment]
Технически, BH.php отличается от BH только синтаксисом. С последним можно поиграться на http://bem.github.io/bh/

Шаблоны для bem-components есть в пакете https://github.com/bem/bem-components-php, подключаются вместе с bem-components, аналогично базируются на bem-core-php, которое базируется на bem-core ;-).

Технически, есть поддерживаемые решения только для Node.js, по возможности я смотрю за PHP веткой, и все ;-).

Можно задавать мне. Еще есть люди, которые почти используют в продакшне, говорят, что ок — поэтому, лучше, все-таки, задавать на форуме.

А по поводу опросничка лучше сразу к @tadatuta

**Comment by tadatuta** [comment]
> А по поводу опросничка лучше сразу к @tadatuta

Идея отличная, но дойдут ли до нее руки — вопрос.

Был бы признателен за подобные подборки от сообщества. Вроде «Я знаю PHP и разрабатываюсь на Window, когда начинал знакомиться с БЭМ, мне очень помогли такие-то статьи». Для начала можно их публиковать прямо на форуме со специальным тегом, ссылку на которой прикрутить в навигацию bem.info.

**Comment by alexanderbondarchuk** [comment]
Спасибо за подробные ответы. Особенно приятно их получить в вечер воскресенья. 

Со своей стороны постараюсь подготовить подобный материал-подборку для начинающих как только успешно реализую первый проект, суть которого заключается в переносе PHP+HTML+CSS+JS+AJAX+JQUERY на PHP+ [БЭМ и его друзья].
