### ISSUE TITLE
Не запилить ли синтаксический сахар для установки модификаторов по событиям

### ISSUE THREAD

**Issue by a-x-** [bem/bem-forum-content-ru#907]
Вполне может быть, что я преувеличиваю частоту этого кейса,
но хочется всё равно поделиться :)

https://gist.github.com/a-x-/e0d60f23ee16021decc5

**Comment by tadatuta** [comment]
Безотносительно сути вопроса, в приведенном примере будет сильно меньше букв, если использовать функции-стрелки,

**Comment by a-x-** [comment]
Отличное замечание!
Надеюсь, скоро удастся найти время и перейти на es6

**Comment by zxqfox** [comment]
> Вполне может быть, что я преувеличиваю частоту этого кейса,
> но хочется всё равно поделиться :)

ты хочешь редукс, или я ничо не понял?

**Comment by a-x-** [comment]
Если деструкторы i-bem научатся наконец-то  сами делать un на любые типы событий, то вот:
```js
BEM.DOM.decl('b-page', {

    bindEvents: function() {
        this.__base.apply(this, arguments);

        BEM.blocks['pane2-api']
            .on('fullscreen:change', (e)=>
            	this.setMod('fullscreen', e.data === 'enter' ? 'yes' : 'no'));

        return this;
    }

});
```

**Comment by a-x-** [comment]
@zxqfox,
Про Redux мало пока знаю, где хорошо и быстро понять концепцию?

**Comment by zxqfox** [comment]
@a-x- Как и я ;-)

Пацаны говорят, что redux это более совершенный flux, а реализация флюкса есть на базе bem-core: https://github.com/bem-contrib/bem-flux
