### ISSUE TITLE
Описание сущностей, именование, структура на конкретном примере

### ISSUE THREAD

**Issue by alexanderbondarchuk** [bem/bem-forum-content-ru#918]
Всем привет.

В качестве примера для разбора поставлена задача описать сущность "человек". Человек может быть "европеец", "азиат", "африканец". У человека есть "рука" (левая, правая), "нога" (левая, правая).

Структура получилась следующая:
Человек - блок `.people`
У человека есть модификаторы - европеец `.people_europe`, азиат `.people_asia,` африканец `.people_africa`
У человека есть элементы - руки `.people__hand` и ноги `.people__leg`
У рук человека есть модификаторы левая `.people__hand_left`, правая `.people__hand_right`
У ног человека есть модификаторы левая `.people__leg_left`, правая `.people__leg_right`

Далее начали усложнять пример - надо добавить тело. С одной стороны тело это элемент, но по структуре страницы руки и ноги должны лежать внутри (быть неотъемлемой частью тела), что уже противоречит концепции бэм. Получается тело надо превращать в блок?

В качестве второго усложнения интересует сделать европейцу руки "толстыми" - по моему тут уже нужен микс.

Подскажите начинающему как быть.

**Comment by awinogradov** [comment]
1 - Вложенность элементов никак не противоречит методологии ;)
``` 
.people
    .people__body
        .people__hand
        .people__leg
```
2 - Каскад от модификатора на элементы
```
.people_europe .people__hand {
   width: 200px;
}
```

**Comment by alexanderbondarchuk** [comment]
@awinogradov спасибо. Но читал где-то в методологии и в обучающих роликах, что методология исключает применение каскадов. Или это касается только вложенности и наследования? Где бы прям ясно об этом прочитать?

**Comment by awinogradov** [comment]
Каскад внутри блока вполне норм. Иначе ты не выживешь:) посмотри стили компонентов;)

**Comment by tadatuta** [comment]
Про вложенные селекторы для модификаторов написано в [FAQ на bem.info](https://ru.bem.info/faq/#Почему-нежелательно-использовать-вложенные-селекторы).
