### ISSUE TITLE
Правильное именование

### ISSUE THREAD

**Issue by APrinciple** [bem/bem-forum-content-ru#931]
Всем шалом!

На днях читал, как ни странно, советы от гугл по оптимизации, там увидел БЭМ (чтобы не допускать каскадность), и дабы не терять время, я решил освоить его, я тут. И у меня вопрос:

Существуют повторяющиеся html5 теги, например  header-ы, footer-ы, nav-ы, и вообще, я всё правильно разметил? :))

Пример:
```html
<header class="header-main">
  <nav class="nav-main">
    <li class="nav-main__item">
      <a class"nav-main__link" href="/">Я обычная ссылка</a>
    </li>
    <li class="nav-main__item">
      <a class"nav-main__link nav-main__link_active" href="/">А я активная ссылка</a>
    </li>
  </nav>
  <form class="form-header">
    <input class="form-header__login" type="text">
    <input class="form-header__email" type="email">
    <button class="form-header__button   form-header__button_red" type="reset"></button>
    <button class="form-header__button   form-header__button_blue" type="submit"></button>
  </form>
</header>

<article class="any-class ">
  <header class="header-post"> это же блок, не элемент?
    <h3 class="header-post__title"></h3>
    <a class="header-post__link"></a>
  </header>

  <footer class="footer-post">
    <div class="footer-post__any-element "></div>
    <a class"footer-post__link " href="/">сайт</a>
  </footer>
<article>

<nav class="navigation-pages">
  <ul class="navigation-pages__ul">
    <li class="navigation-pages__item">
       <a class="navigation-pages__link"></a>
       <a class="navigation-pages__link_current">Текущая</a>
    </li>
  </ul>
</nav>

<footer class="footer" class="footer-bottom" или class"cellar">
  <a class="footer-bottom__link">Ссылка подвала</a>
</footer>
```
Я могу разделять главный `<header>` и для поста `<header>` вот так: 
```html
<header class="header header_main"> с модификатором
  <a class="header__link"></a> 
</header>

<article>
  <header class="header header_article"> другой модификатор
   <a class="header__link "></a> могу я тут писать "header_article__link", чтобы различать с ссылкой в главной header (<header class="header header_main">) нельзя писать header c модификатором, а потом элемент - "header_article__link"?
  </header>
</article>
```
Сей (2-й) подход с разными модификаторами ещё потребует каскад в CSS, в таком случае нужно в одинаковых html5 тегах и в тегах типо `<form>`, писать разные классы, а не разные модификаторы?

Пытался с исходниках яндекс-проектов смотреть код, смотрел на DNS-yandex, punto-switcher, там только на дивах, меня интересовали html5 теги и `nav > ul > li > a`, понимаю, что можно опустить html5 теги, которые повторяются, навигацию просто через `<div> <a>`, опуская nav, ul и li, и т.д. но интересует c многими вложенностями и повторяющиеся.

И ещё на счёт каскадности, смотрел исходник DNS-yandex, там в классах "static-text" есть h2, h3, h4, без классов, соответственно - есть каскад, так каскад простителен? Его можно не всегда избегать?
На гугл в советах по оптимизации написано, используйте методологию БЭМ, дабы избежать каскадности, чтобы увеличить скорость, говорилось, что каскадность - плохо для оптимизации. 
В связи с тем, что БЭМ на независимостях строится, чтобы не было конфликтов, а на яндекс-днс опустили классы в h2, h3, h4, ибо уверены, что конфликтов не будет, и опустили классы, сверстали на каскады - static-text h2.
Но в чём тогда профит, в независимости, в оптимизации (не допускать каскады, где это можно), от чего плясать?

И есть тут, кто может дать ссылки на свои работы, дабы посмотреть примеры вёрстки по БЭМ. 

Пардон за много букв. Заранее благодарю.

**Comment by tadatuta** [comment]
Привет, @APrinciple!
На форуме действует markdown-разметка, я пару раз пытался поправить форматирование, но ты  продолжаешь менять текст, так что у меня ничего не получилось.

Либо добавь форматирование (код нужно класть в три бектика (`) и название языка — в данном случае HTML), либо остановись, я сам расставлю.

**Comment by APrinciple** [comment]
Пардон, не знал, просто вносил заметку, чтобы отображает при выводе по-другому, когда два нижних подчёркивания.

**Comment by tadatuta** [comment]
Форматирование поправил.

Теперь по сути вопроса:
1. Проблема в разметке сейчас не на стороне БЭМ, а в том, что она невалидная: `li` лежат в `nav`, хотя должны быть в `ul`. Впрочем, добиваться валидности ради валидности не обязательно ;)
2. Следующий момент, который нужно понимать: семантика по спеке зачастую достаточно слабо связана с реальной жизнью и почти никак не связана с SEO. Семантика, которую предлагает БЭМ гораздо выразительнее и ближе к реальным задачам. Ну т.е. добавление лишних `header` мало что даст браузеру, поисковику или самому разработчику, а правильно подобранные БЭМ-сущности делают код надежным и читабельным сами по себе.
3. Не нужно априори бояться вложенных селекторов. Да, чем их меньше, тем CSS проще в поддержке. Но, скажем, в случае с каскадом от модификатора ничего плохого нет. Этот же пример [описан в FAQ](https://ru.bem.info/faq/#Почему-нежелательно-использовать-вложенные-селекторы) на bem.info.

По поводу `header-main` и `header-article` VS `header header_main` и `header header_article` следует руководствоваться такими размышлениями: если у разных `header` есть что-то  общее, то это общее можно записать в `.header`, а отличия в соответствующие модификаторы — это позволит избавиться от копипаста.
Если же они совершенно не похожи друг на друга, их действительно стоит сделать разными блоками. Но тут тогда возникает вопрос, точно ли в их названиях должно присутствовать слово `header` (тег `header` можно сохранить независимо от имени класса)?

Отдельно про исходники на сервисах Яндекса. БЭМ — это как полезные советы про то, что нужно заниматься спортом, правильно питаться и поменьше смотреть телевизор. А в реальной жизни люди зачастую ведут себя наоборот, хотя знают, что сигареты — вредно, а овсянка и бег — полезно. Вот и с сервисами Яндекса примерно такая же история ;)

**Comment by APrinciple** [comment]
1. Во втором примере - <nav class="navigation-pages">, я не забыл про ul :) 
2. Понял.
3. Я понял, но — (последний пример) 2 одинаковых<a class="header__link "> в двух разных (по модификатору) header header_main и header header_article. Как мне присваивать <a> уникальность, могу указывать(писать) элемент, после модификатора — header_main__link и header_article__link?

**Comment by kompolom** [comment]
Какскад плох не только тем что он медленней обрабатывается, но и тем, что его сложно поддерживать. Когда мы пишем код каскадом, мы завязываемся на вложенность элементов. и когда через пару месяцев ее придется поменять, все может рухнуть

**Comment by vithar** [comment]
> Как мне присваивать уникальность, могу указывать(писать) элемент, после модификатора — header_main__link и header_article__link?

Нет, так нельзя. @tadatuta это тоже надо в FAQ добавить.

**Comment by APrinciple** [comment]
И как тогда быть в таких случаях, например form-ы, которые в примере указываются. Их может быть 2-3.
1.
```
<form class="form form_login form_theme_forest">
  <input class="form__input">
  <input class="form__submit form__submit_disabled">
</form>
```
2. 
```<form class="form form_ANY">
  <input class="form__input">
  <input class="form__submit form__submit_disabled">
</form>
```

В CSS могу каскад: form_ANY .form__input {style;} Или как мне уникальность добавлять в таких случаях? Как мне правильно присвоить уникальность инпутам к form_ANY, чтобы без каскада.
Я могу инпутам во 2-й форме добавить модификаторы, чтобы отличать от инпутов в 1-й форме, но как их правильно указать, чтобы понимать, что они относятся (логически связаны) именно к form_ANY? (Если не использовать каскад).

**Comment by tadatuta** [comment]
> Создавать во 2-й форме 2 блока, а не блок + модификатор?


Да, это правильный вариант. См. https://ru.bem.info/method/key-concepts/#Микс

**Comment by zxqfox** [comment]
@APrinciple не совсем правильный. `form-ANY__input` лучше все же заменить на `form__input`. Верно, @tadatuta ?

**Comment by tadatuta** [comment]
@zxqfox да, конечно

**Comment by APrinciple** [comment]
И как тогда присваивать инпутам, которые в форме form form-ANY, другие стили, которые отличаются от инпутов в другой форме?
Писать каскад form-ANY .form__input? или писать инпутам во 2-й форме модификатор — form__input form__input_any?

**Comment by vithar** [comment]
Правильно использовать миксы:

form__input form-ANY__my-shiny-input

**Comment by APrinciple** [comment]
```
<form class="form form-login">
  <input class="form__input">
  <input class="form__submit form__submit_disabled">
</form>

.form__input {
  width: 100px;
}

<form class="form form-ANY">
  <input class="form__input form-ANY__input">
  <input class="form__submit form__submit_disabled form-ANY__submit">
</form>

.form-ANY__input {
  width: 500px;
  height: 50px;
}
```

Верно? Такой подход даёт избегать повторение стилей для каждой формы, общие стили задаются классу ```.form```, а потом миксом - добавляю нужные мне различия (изменения) добавляя класс ```.form-ANY__input```

**Comment by vithar** [comment]
Да. В случае использования bem-components будет не form__input, а просто input:

input form-ANY__input

**Comment by vithar** [comment]
form-ANY__input можно использовать и отдельно, если так надо.

**Comment by APrinciple** [comment]
Для таких новичков, как я, советую сию статью, там вся документация в куче — https://habrahabr.ru/company/yandex/blog/276035/

И ещё вышел фреймворк — Aleut.css на Sass, который ориентирован на БЭМ.
Aleut.css — статический фреймворк на Sass, с идеями BEM, OOCSS и нацеленностью на производительность и масштабирование.

Только там именование модификаторов основывается на альтернативном методе (--).
