### ISSUE TITLE
Failed to capture the element because it is positioned outside of the captured body

### ISSUE THREAD

**Issue by alexpts** [bem/bem-forum-content-ru#936]
Только начал использовать gemini для тестирования. Буквально сразу же столкнулся с ошибкой вида:

Failed to capture the element because it is positioned outside of the captured body. Most probably you are trying to capture an absolute positioned element which does not make body height to expand. To fix this place a tall enough <div> on the page to make body expand.
Element position: 0, 2912; size: 2070, 92. Page screenshot size: 2100, 1514. 

Я пытаюсь снять скриншот footer тега, который находится внизу страницы и до него нужно доскролить.
Методов в api gemini для скролинга не нашел. Пытался через click метод проскролить или через js код.

Мой тест выглядит сейчас так:

`````javascript
suite
  .setUrl('/') // https://alexpts.ru
  .before(function(actions, find){
    actions.click(find('footer'));
    actions.executeJS(function(window) {
      window.scrollBy(999, 999999)
    });
  })
  .setCaptureElements('footer')
  .capture('footer', function(actions, find){
    actions.click(find('footer'));
    actions.executeJS(function(window) {
      window.scrollBy(0, 999999)
    });
  });
`````
При этом я тестирую в реальном браузере chrome и в нем видно, что страница прокручивается, но происходит это, видимо, слишком поздно. Пробовал и через actions и через метод before.

Можете подсказать как прокрутить страницу и захватить footer тег?

**Comment by tadatuta** [comment]
cc @sipayRT

**Comment by sipayRT** [comment]
привет. тебе не нужно хотеть самому скролить страницу - gemini сам за тебя это сделает. Твой тест должен выглядеть примерно так:

```
suite
  .setUrl('/') // https://alexpts.ru
  .setCaptureElements('footer')
  .capture('footer');
```

**Comment by alexpts** [comment]
Привет.

Весь файл теста выглядит так cайчас
`````javascript
var gemini = require('gemini');

gemini.suite('alexpts footer', function(suite) {

  suite
    .setUrl('/')
    .setCaptureElements('footer')
    .capture('footer');
});
`````


Файл с конфигом выглядит так:
`````
rootUrl: https://alexpts.ru
tolerance: 3.5

browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome

sets:
  alexpts.ru:
    files:
      - ./test/
`````

Запускаю selenium у себя локально через npm пакет  selenium-standalone 5.0.0 и затем запускаю тесты командой node_modules/.bin/gemini gather test 

В результате в консоле выводится:
```
Failed to capture the element because it is positioned outside of the captured body. Most probably you are trying to capture an absolute positioned element which does not make body height to expand. To fix this place a tall enough <div> on the page to make body expand.
Element position: 0, 2912; size: 2070, 92. Page screenshot size: 2100, 1514.
```

Делается скриншот всей страницы после скрола, а не только тега footer.

Может что-то прислать еще, чтобы воспроизвести ошибку и найти причину, почему так происходит?

**Comment by sipayRT** [comment]
для начала пришли скриншот, который у тебя получился

**Comment by alexpts** [comment]
Вот ссылка на скриншот - https://www.dropbox.com/s/3jedo7ps3oitm2u/chrome.png?dl=0

**Comment by alexpts** [comment]
Получается воспроизвести такое состояние?

**Comment by sipayRT** [comment]
заведи, плз, про это ишью в [gemini](https://github.com/gemini-testing/gemini) - там посмотрим.

**Comment by alexpts** [comment]
Ок

**Comment by alexpts** [comment]
Проблема решилась обновление до версии gemini 3.
