### ISSUE TITLE
как задать булев атрибут в html-differ?

### ISSUE THREAD

**Issue by kompolom** [bem/bem-forum-content-ru#984]
Может быть `aria-hidden="true"`  или `aria-hidden`. Как попросить диффер считать записи эквивалентными?

**Comment by tadatuta** [comment]
Кажется, что ты хочешь плохого.

С точки зрения спеки для булевого атрибута (например, `disabled`) значение `true` не является правильным (да, браузеры это съедят, но это невалидно).

А `aria-hidden` по спеке таки должен иметь значение `true`.
