### ISSUE TITLE
mod или mix?

### ISSUE THREAD

**Issue by Yura-ka** [bem/bem-forum-content-ru#992]
Я бы хотел спросить, как правильнее по bem методологии.
Имеется bh блок table для таблицы, нужно задать фиксированную ширину колонок только для этой таблицы, есть два способа mix и mod, 
mix больше кода, у элементов больше на один класс, но зато весь внешний вид в блоке 'orders-table'
mod наверное правильнее по методологии, но не явно видно в проекте для дальнейшей поддержки, к тому же будут ещё несколько таблиц со своими размерами. 

## mix:
    {
        block: 'table',
        mix:[{block: 'orders-table'}],
        content:[
        {
            elem: 'colgroup',
            content: [
                {
                    elem: 'col',
                    mix: [{block: 'orders-table', elem: 'col', mods: {column: 'one'}}],
                },
                {
                    elem: 'col',
                    mix: [{block: 'orders-table', elem: 'col', mods: {column: 'two'}}],
                }
                ....код таблицы....
        }
    ]}

---
## mod:
    {
        block: 'table',
        mods: {orders:true},
        content:[
        {
            elem: 'colgroup',
            content: [
                {
                    elem: 'col',
                    mods: {'orders-column':'one'},
                },
                {
                    elem: 'col',
                    mods: {'orders-column':'two'},
                }
                ....код таблицы....
        }
    ]}

**Comment by tadatuta** [comment]
Я бы подходил к вопросу так: если разные по смыслу таблицы могут иметь одинаковую фиксированную ширину, то это модификатор (его можно переиспользовать независимо от того, о чем каждая конкретная таблица), а если только таблица с заказами обладает таким поведением, то это микс с `orders-table` — т.е. свойство привязываем не к абстрактной таблице, а к конкретной.
